function selezione(id,label,lista,v,cls){ return '<div class="field'+(cls?" "+cls:"")+'"><label for="'+id+'">'+label+'</label><select id="'+id+'">'+opts(lista,v)+'</select></div>'; }
function datalist(id,lista){ return '<datalist id="'+id+'">'+lista.map(function(x){ return '<option value="'+esc(x)+'">'; }).join("")+'</datalist>'; }

/* ---------- elenco scali ---------- */
function elencoScali(){ var lst=listaScali(), anni={}; lst.forEach(function(s){ anni[anno(s.eta||s.creato)]=1; }); var A=Object.keys(anni).sort().reverse();
  var q=upper(S.q), ris=lst.filter(function(s){ if(S.anno==="range"?!perOk(s.eta||s.creato,"range",S.scDa,S.scA):(S.anno&&anno(s.eta||s.creato)!==S.anno)) return false; var st=statoScalo(s), ge=giorni(oggi(),s.eta), gd=s.etd?giorni(oggi(),s.etd):null;
    if(S.filtro==="aperti"&&st.c!=="no"&&st.c!=="warn") return false; if(S.filtro==="prev"&&st.t!=="preventivo") return false; if(S.filtro==="saldati"&&st.t!=="saldato") return false;
    if(S.filtro==="porto"&&!(ge!==null&&ge>=0&&ge<=45&&(gd===null||gd<=0))) return false; if(S.filtro==="attesi"&&!(ge!==null&&ge<0&&ge>=-30)) return false;
    if(!q) return true; var t=upper([s.prot,s.nave,s.imo,s.cliente,s.carico,s.ricevitore,s.operazione,s.provenienza,s.note,s.intestazione].join(" ")); return q.split(/\s+/).every(function(w){ return t.indexOf(w)>=0; }); });
  var O=S.ordScali||{k:"",d:-1}; if(O.k){ var numK={prot:1,gt:1,pda:1,fda:1,inc:1}; ris.sort(function(a,b){ var va,vb; if(O.k==="prot"){ va=parseInt(a.prot,10)||0; vb=parseInt(b.prot,10)||0; } else if(O.k==="pda"){ va=totPda(a); vb=totPda(b); } else if(O.k==="fda"){ va=totFda(a); vb=totFda(b); } else if(O.k==="inc"){ va=incassato(a); vb=incassato(b); } else if(O.k==="gt"){ va=num(a.gt)||0; vb=num(b.gt)||0; } else if(O.k==="stato"){ va=statoScalo(a).t; vb=statoScalo(b).t; } else { va=upper(a[O.k]||""); vb=upper(b[O.k]||""); }
    var c=numK[O.k]?(va-vb):String(va).localeCompare(String(vb)); return c*O.d||(b.eta||"").localeCompare(a.eta||""); }); }
  function thS(k,l,cls){ var c=[cls||"",O.k===k?(O.d>0?"on up":"on"):""].filter(Boolean).join(" "); return '<th'+(c?' class="'+c+'"':'')+' data-sort="'+k+'" title="Ordina per '+esc(l)+'">'+l+'</th>'; }
  var h='<div class="top"><h1>Scali</h1><span class="stato">'+ris.length+' su '+lst.length+'</span><div class="spacer"></div><button class="btn primary" id="nuovoScalo">+ Nuovo scalo</button></div>';
  h+='<div class="panel"><div class="panel-h"><div class="field" style="flex:1;min-width:180px"><input id="q" placeholder="Cerca nave, IMO, cliente, carico, prot…" value="'+esc(S.q)+'" aria-label="Cerca"></div>'+
     '<div class="field"><select id="fAnno" aria-label="Anno">'+opt("","tutti gli anni",S.anno)+A.map(function(y){ return opt(y,y,S.anno); }).join("")+optRange(S.anno)+'</select></div>'+campiPeriodo("scPer",S.anno,S.scDa,S.scA)+
     '<div class="chips">'+[["","tutti"],["porto","in porto"],["attesi","in arrivo"],["aperti","da incassare"],["prev","preventivi"],["saldati","saldati"]].map(function(c){ return '<button class="chipbtn'+((S.filtro||"")===c[0]?" on":"")+'" data-filtro="'+c[0]+'">'+c[1]+'</button>'; }).join("")+'</div></div>';
  if(!lst.length) h+='<div class="panel-b"><p>Nessuno scalo in archivio. Crea il primo con <strong>+ Nuovo scalo</strong>, oppure importa i dati esistenti da <strong>Impostazioni → Archivio</strong> (backup di Pratiche di Scalo, CSV del Mastrino Approdi).</p></div>';
  else{ h+='<div class="scroll"><table><thead><tr>'+thS("prot","Prot.")+thS("eta","ETA")+thS("etd","ETD")+thS("nave","Nave")+thS("gt","GT","num")+thS("cliente","Cliente")+thS("operazione","Operazione / carico")+thS("pda","PDA","num")+thS("fda","FDA","num")+thS("inc","Incassato","num")+thS("stato","Stato")+'</tr></thead><tbody>';
    ris.forEach(function(s){ var st=statoScalo(s), p=totPda(s), f=totFda(s); h+='<tr class="row'+(S.hl===s.id?" hl":"")+'" data-sc="'+s.id+'"><td>'+esc(s.prot)+'/'+String(s.annoProt||anno(s.eta)).slice(2)+'</td><td>'+dIt(s.eta)+'</td><td>'+dIt(s.etd)+'</td><td><strong>'+esc(s.nave)+'</strong>'+(s.flag?'<div class="sub">'+esc(s.flag)+(s.tipo?" · "+esc(s.tipo):"")+'</div>':"")+'</td><td class="num">'+(s.gt?Number(s.gt).toLocaleString("it-IT"):"")+'</td><td>'+esc(s.cliente)+'</td><td>'+esc(s.operazione)+(s.carico?'<div class="sub">'+esc(s.carico)+(s.quantita?" "+esc(s.quantita):"")+'</div>':"")+'</td><td class="num">'+eur(p)+'</td><td class="num">'+(f?eur(f):"—")+(f&&p&&Math.abs(f-p)>0.5?'<div class="sub '+(f>p?"pos":"neg")+'">'+(f>p?"+":"")+eur(f-p)+'</div>':"")+'</td><td class="num">'+(incassato(s)?eur(incassato(s)):"—")+'</td><td><span class="chip '+st.c+'">'+st.t+'</span></td></tr>'; });
    h+='</tbody></table></div>'; }
  return h+'</div>'; }

/* ---------- scheda scalo ---------- */
function scheda(sc){ var st=statoScalo(sc), tabs=[["nave","Nave & viaggio"],["intest","Intestazione"],["pda","PDA preventivo"],["spese","Fatture fornitori ("+speseDi(sc.id).length+")"],["conto","Conto PDA / FDA"],["incassi","Incassi"]];
  var h='<div class="top"><button class="btn" id="indietro">‹ Scali</button><h1>'+esc(sc.nave||"Nuovo scalo")+' <span class="sub">prot. '+esc(sc.prot)+'/'+esc(sc.annoProt||anno(sc.eta))+'</span></h1><span class="chip '+st.c+'">'+st.t+'</span>'+(sc.updatedAt?'<span class="sub">modificato '+dIt(String(sc.updatedAt).slice(0,10))+(sc.updatedByName?' da '+esc(sc.updatedByName):'')+'</span>':'')+'<div class="spacer"></div>'+
    '<div class="acts"><button class="btn" data-doc="pda">Stampa PDA</button><button class="btn" data-doc="fda">Stampa FDA</button><button class="btn" id="duplica">Duplica scalo</button><button class="btn danger small" id="elimina">Elimina</button></div></div>';
  h+='<div class="tiles"><div class="tile"><div class="k">PDA preventivo</div><div class="v">€ '+eur(totPda(sc))+'</div><div class="s">'+(sc.pda.inviato?"inviato il "+dIt(sc.pda.inviato):"calcolato dalle tariffe")+'</div></div>'+
     '<div class="tile"><div class="k">FDA consuntivo</div><div class="v">'+(haFda(sc)?'€ '+eur(totFda(sc)):'—')+'</div><div class="s">'+(function(){ var rf=fdaRif(sc), ns=vociNsConto(sc); return (rf.numero?'fattura n. '+esc(rf.numero)+(rf.data?' del '+dIt(rf.data):'')+(rf.daNs?' (ns fattura)':'')+' · ':'')+speseDi(sc.id).length+' fatture registrate'+(ns.n?' · ns fattura € '+eur(ns.tot):''); })()+'</div></div>'+
     (function(){ var ft=0,nf=0; speseDi(sc.id).forEach(function(x){ if(isNs(x)) return; ft+=num(x.totale)||0; nf++; }); ft=r2(ft); var cs=cassaSpeseDi(sc.id), inc=incassato(sc), saldo=r2(inc-ft-cs.tot), f=totFda(sc);
       return '<div class="tile '+(nf||inc||cs.n?(saldo<-0.005?"warn":"ok"):"")+'"><div class="k">Saldo fatture / incassi</div><div class="v">'+(saldo<-0.005?"− € "+eur(-saldo):"€ "+eur(saldo))+'</div><div class="s">incassi € '+eur(inc)+' − fatture fornitori € '+eur(ft)+(nf?' ('+nf+')':'')+(cs.n?' − cassa € '+eur(cs.tot)+' ('+cs.n+')':'')+(haFda(sc)?' · FDA − fatture € '+eur(r2(f-ft-cs.tot)):'')+'</div></div>'; })()+
     '<div class="tile '+st.c+'"><div class="k">Incassato</div><div class="v">€ '+eur(incassato(sc))+'</div><div class="s">'+(totFda(sc)-incassato(sc)>0.005?"residuo € "+eur(totFda(sc)-incassato(sc)):"nessun residuo")+'</div></div></div>';
  h+='<div class="panel"><div class="subtabs" role="tablist">'+tabs.map(function(t){ return '<button role="tab" data-tab="'+t[0]+'" aria-selected="'+(S.tab===t[0])+'">'+t[1]+'</button>'; }).join("")+'</div><div class="panel-b">';
  if(S.tab==="nave") h+=formNave(sc); else if(S.tab==="intest") h+=formIntest(sc); else if(S.tab==="pda") h+=formPda(sc); else if(S.tab==="spese") h+=vistaSpese(sc); else if(S.tab==="conto") h+=vistaConto(sc); else h+=vistaIncassi(sc);
  return h+'</div></div>'; }
function pannelloPS(sc){ var D=psDati(), h='<div class="panel pspanel" style="margin-bottom:12px"><div class="panel-h"><b>Dati nave da Pratiche di Scalo</b><span class="sub">carica il file di <em>Per Portolano</em> di una nave (PORTOLANO_NAVE_*.json, con il PDA inviato: entra da solo in questo scalo) oppure quello di tutto l\'archivio (Archivio → <em>Estrai dati</em> = PORTOLANO_DATI_*.json, Impostazioni → <em>Esporta archivio</em> = BACKUP_PRATICHE_*.json) e scegli la pratica: nave, viaggio e PDA si compilano da soli.</span><div class="spacer"></div>'+
    '<label class="btn'+(D?"":" primary")+'">'+(D?"Altro file":"Carica file da Pratiche di Scalo")+' <input type="file" id="psFile" accept=".json,application/json" hidden></label>'+(D?'<button class="btn'+(S.psPick?"":" primary")+'" id="psApri">'+(S.psPick?"Chiudi elenco":"Scegli la pratica ("+D.dati.pratiche.length+")")+'</button>':'')+'</div>';
  if(D&&S.psPick){ var L=D.dati.pratiche, q=upper(S.psQ||""), nome=upper(sc.nave||""), imo=String(sc.imo||"").trim();
    var pun=function(p){ var s=0; if(imo&&String(p.imo||"").trim()===imo) s+=4; if(nome&&upper(p.nave)===nome) s+=3; if(sc.eta&&isoData(p.eta)===sc.eta) s+=2; else if(sc.eta&&isoData(p.eta)){ var g=Math.abs(giorni(sc.eta,isoData(p.eta))||99); if(g<=3) s+=1; } return s; };
    var lst=L.filter(function(p){ return !q||cercaOk(q,[p.nave,p.imo,p.agente,p.ormeggio,p.operazione,p.carico,p.provenienza,p.prossimo,p.consignee,p.pda&&p.pda.cliente,dIt(isoData(p.eta))]); }).map(function(p){ return {p:p,s:pun(p)}; }).sort(function(a,b){ return (b.s-a.s)||(isoData(b.p.eta)||"").localeCompare(isoData(a.p.eta)||""); });
    h+='<div class="panel-b"><div class="acts" style="margin-bottom:8px"><div class="field" style="flex:1;min-width:180px"><input id="psQ" placeholder="Cerca nave, IMO, cliente, data…" value="'+esc(S.psQ||"")+'" aria-label="Cerca pratica"></div><label class="sub" style="display:flex;align-items:center;gap:6px"><input type="checkbox" id="psPda"'+(S.psNoPda?"":" checked")+' style="width:auto"> anche il PDA</label><label class="sub" style="display:flex;align-items:center;gap:6px"><input type="checkbox" id="psVuoti"'+(S.psVuoti?" checked":"")+' style="width:auto"> solo i campi vuoti</label><span class="sub">file '+esc(D.file||"")+(D.quando?' · caricato il '+dIt(D.quando.slice(0,10)):'')+' · '+L.length+' pratiche'+(D.dati.tipo==="dati"?" (Estrai dati)":D.dati.tipo==="nave"?" (Per Portolano)":" (backup)")+'</span><div class="spacer"></div><button class="btn small" id="psTutte" title="Crea o aggiorna nell\'archivio uno scalo per ogni pratica del file">Importa tutte nell\'archivio</button></div>';
    if(!lst.length) h+='<p class="sub">Nessuna pratica corrisponde alla ricerca.</p>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Nave</th><th>IMO</th><th>ETA / ETD</th><th>Agente</th><th>Viaggio</th><th>PDA</th><th></th></tr></thead><tbody>';
      lst.slice(0,60).forEach(function(x){ var p=x.p, q=p.pda||{}; h+='<tr'+(x.s>=3?' class="hl"':'')+'><td data-l="Nave"><span><strong>'+esc(p.nave)+'</strong>'+(p.flag||p.tipo?'<div class="sub">'+esc([p.flag,p.tipo].filter(Boolean).join(" · "))+(p.gt?' · GT '+esc(p.gt):'')+'</div>':'')+'</span></td><td data-l="IMO">'+esc(p.imo||"")+'</td><td data-l="ETA / ETD"><span>'+(p.eta?dIt(isoData(p.eta)):"—")+(p.etd?'<div class="sub">'+dIt(isoData(p.etd))+'</div>':'')+'</span></td><td data-l="Agente">'+esc(p.agente||"")+'</td><td data-l="Viaggio"><span>'+esc([p.ormeggio,p.operazione].filter(Boolean).join(" · "))+(p.carico?'<div class="sub">'+esc(p.carico)+(p.quantita?" "+esc(p.quantita):"")+'</div>':'')+(p.provenienza||p.prossimo?'<div class="sub">'+esc([p.provenienza?"da "+p.provenienza:"",p.prossimo?"per "+p.prossimo:""].filter(Boolean).join(" · "))+'</div>':'')+'</span></td><td data-l="PDA"><span>'+(q.cliente?esc(q.cliente):(q.items&&Object.keys(q.items).length?'<span class="sub">sì</span>':'—'))+(q.totale?'<div class="sub">€ '+eur(q.totale)+'</div>':'')+'</span></td><td><button class="btn small primary" data-pscarica="'+p.idx+'">'+(x.s>=3?"Carica (stessa nave)":"Carica")+'</button></td></tr>'; });
      h+='</tbody></table></div>'+(lst.length>60?'<p class="sub">Mostrate le prime 60: restringi con la ricerca.</p>':'')+'</div>'; } }
  return h+'</div>'; }
function formNave(sc){ var L=S.cfg.liste;
  return pannelloPS(sc)+'<div class="grid">'+campo("n_prot","Prot.",sc.prot)+campo("n_annoProt","Anno prot.",sc.annoProt||anno(sc.eta),"number")+selezione("n_agente","Agente",L.agenti,sc.agente)+
   campo("n_nave","Nave",sc.nave,"text",{cls:"w2",list:"dl_navi"})+campo("n_imo","IMO",sc.imo)+campo("n_callSign","Call sign",sc.callSign)+campo("n_flag","Bandiera",sc.flag,"text",{list:"dl_flag"})+campo("n_tipo","Tipo nave",sc.tipo,"text",{list:"dl_tipi"})+
   campo("n_gt","GT",sc.gt,"number")+campo("n_nt","NT",sc.nt,"number")+campo("n_dwt","DWT",sc.dwt,"number")+campo("n_loa","LOA (m)",sc.loa,"number")+campo("n_pescaggio","Pescaggio (m)",sc.pescaggio,"number")+campo("n_yob","Anno costruzione",sc.yob)+campo("n_master","Comandante",sc.master)+
   campo("n_eta","ETA",sc.eta,"date")+campo("n_etaOra","Ora ETA",sc.etaOra,"time")+campo("n_etd","ETD",sc.etd,"date")+campo("n_provenienza","Porto di provenienza",sc.provenienza,"text",{list:"dl_porti"})+campo("n_prossimo","Prossimo porto",sc.prossimo,"text",{list:"dl_porti"})+
   campo("n_ormeggio","Ormeggio",sc.ormeggio,"text",{list:"dl_orm"})+campo("n_operazione","Operazione",sc.operazione,"text",{list:"dl_op"})+campo("n_carico","Carico",sc.carico)+campo("n_quantita","Quantità (MT)",sc.quantita)+campo("n_ricevitore","Ricevitore / caricatore",sc.ricevitore)+
   campo("n_cliente","Cliente (armatore / noleggiatore)",sc.cliente,"text",{cls:"w2",list:"dl_clienti"})+
   '<div class="field full"><label for="n_note">Note</label><textarea id="n_note">'+esc(sc.note)+'</textarea></div>'+
   '<div class="field"><label>&nbsp;</label><label style="text-transform:none;font-size:13px;color:var(--ink)"><input type="checkbox" id="n_pagDir" style="width:auto"'+(sc.pagDir?" checked":"")+'> il cliente paga i fornitori direttamente (PAG DIR)</label></div></div>'+
   datalist("dl_navi",naviNote())+datalist("dl_flag",L.bandiere)+datalist("dl_tipi",L.tipi)+datalist("dl_porti",L.porti)+datalist("dl_orm",L.ormeggi)+datalist("dl_op",L.operazioni)+datalist("dl_clienti",clientiNoti())+
   '<div class="acts" style="margin-top:14px"><button class="btn primary" id="salvaNave">Salva</button><span class="sub">Con la stessa nave già in archivio, GT/NT e dati si ripropongono automaticamente quando scrivi il nome.</span></div>'; }
function naviNote(){ var m={}; listaScali().forEach(function(s){ if(s.nave) m[upper(s.nave)]=1; }); naviPS().forEach(function(n){ m[n]=1; }); return Object.keys(m).sort(); }
function clientiNoti(){ var m={}; listaScali().forEach(function(s){ if(s.cliente) m[s.cliente]=1; }); return Object.keys(m).sort(); }
function leggiNave(sc){ var o=Object.assign({},sc); ["prot","agente","imo","callSign","flag","tipo","yob","master","eta","etaOra","etd","provenienza","prossimo","ormeggio","operazione","carico","quantita","ricevitore","cliente","note"].forEach(function(k){ o[k]=val("n_"+k); });
  o.nave=upper(val("n_nave")); o.flag=upper(o.flag); o.tipo=upper(o.tipo); ["gt","nt","dwt","loa","pescaggio"].forEach(function(k){ o[k]=num(val("n_"+k)); }); o.annoProt=parseInt(val("n_annoProt"),10)||new Date().getFullYear(); o.pagDir=val("n_pagDir"); return o; }
function intestazioniNote(){ var m={}; listaScali().forEach(function(s){ var t=String(s.intestazione||"").trim(); if(t) m[t]=1; }); return Object.keys(m).sort(); }
function formIntest(sc){ var B=S.cfg.banche, note=intestazioniNote();
  var h='<p class="sub" style="max-width:70ch">L\'intestazione del cliente (Messrs) compare in testa a PDA e FDA insieme alla carta intestata dell\'agenzia, che si imposta una volta sola in <strong>Impostazioni → Intestazione</strong>. Qui si scrive ragione sociale, indirizzo e P.IVA / VAT del destinatario del conto, riga per riga.</p>';
  h+='<div class="grid"><div class="field w2"><label for="i_intest">Intestazione conto (Messrs)</label><textarea id="i_intest" style="min-height:110px" placeholder="Ragione sociale&#10;Indirizzo&#10;Città, Paese&#10;P.IVA / VAT">'+esc(sc.intestazione||"")+'</textarea></div>'+
    '<div class="field"><label for="i_riusa">Riprendi da uno scalo precedente</label><select id="i_riusa">'+opt("","—","")+note.map(function(t){ return opt(t,t.split("\n")[0].slice(0,60),""); }).join("")+'</select>'+
    '<label for="i_banca" style="margin-top:10px">Banca sul documento</label><select id="i_banca">'+B.map(function(b){ return opt(b.id,b.nome+" – "+b.iban,sc.banca); }).join("")+'</select>'+
    '<label for="i_attn" style="margin-top:10px">Att.ne / riferimento</label><input id="i_attn" value="'+esc(sc.attn||"")+'" placeholder="Attn: Operations dept.">'+
    '<label for="i_firma" style="margin-top:10px">Timbro e firma sul documento</label><select id="i_firma">'+opt("si","Sì – timbro e firma di "+agenteFirmatario(sc,"pda"),sc.firma||"si")+opt("no","No – senza timbro e firma",sc.firma||"si")+'</select><span class="sub">La firma è quella dell\'agente dello scalo (nel FDA, dell\'agente scelto nel Conto FDA); si carica in Impostazioni → Timbro e firme.</span></div></div>';
  h+='<div class="acts" style="margin-top:14px"><button class="btn primary" id="salvaIntest">Salva</button><button class="btn" data-doc="pda">Anteprima PDA</button></div>';
  return h; }
/* ---------- PDA preventivo: parametri e voci ---------- */
function formPda(sc){ var p=sc.pda, C=S.cfg, gt=num(sc.gt)||0;
  var h='<h3>Parametri del calcolo</h3><div class="grid" style="margin-top:8px">'+
    '<div class="field"><label>GT / NT nave</label><div style="padding:7px 0" class="num">'+(gt?Number(gt).toLocaleString("it-IT"):"<span class='pos'>GT mancante</span>")+' / '+(sc.nt?Number(sc.nt).toLocaleString("it-IT"):"—")+'</div></div>'+
    campo("p_nPil","Prestazioni piloti",p.nPil,"number")+campo("p_nOrm","Prestazioni ormeggiatori",p.nOrm,"number")+campo("p_nTug","Prestazioni rimorchio",p.nTug,"number")+campo("p_tugs","N. rimorchiatori",p.tugs,"number")+
    '<div class="field"><label for="p_transfer">Trasferimento rimorchiatori</label><select id="p_transfer">'+opt("0","no",p.transfer?"1":"0")+opt("1","sì, con 2 rimorchiatori (€ "+eur(C.transfer)+")",p.transfer?"1":"0")+'</select></div>'+
    '<div class="field w2"><label for="p_anc">Tassa d\'ancoraggio</label><select id="p_anc">'+ANC_TIPI.map(function(a){ return opt(a[0],a[0]?a[1].replace(/\(.*\)/,"(€/NT "+C.anc[a[0]]+")"):a[1],p.anc); }).join("")+'</select></div>'+
    '<div class="field"><label for="p_chim">Chimico di porto</label><select id="p_chim">'+opt("","nessuno",p.chim)+Object.keys(C.chim).map(function(k){ return opt(k,k+" (€ "+eur(C.chim[k])+")",p.chim); }).join("")+'</select></div>'+
    campo("p_stamp","Marche da bollo / stamp (€)",p.stamp,"number")+campo("p_inviato","PDA inviato il",p.inviato,"date")+'<div class="field w2"><label for="p_notes">Notes (in fondo al PDA)</label><textarea id="p_notes" rows="3">'+esc(p.notes||"")+'</textarea></div></div>';
  h+='<div class="sub" style="margin:6px 0 14px" id="pdaTar">Tariffe piloti € '+eur(rate(C.pil,gt))+' · ormeggiatori € '+eur(rate(C.orm,gt))+' · rimorchiatore € '+eur(rate(C.tug,gt))+' per prestazione a questo GT (scaglioni modificabili in Impostazioni → Tariffe).</div>';
  if(p.fontePS) h+='<div class="warnbox" style="background:var(--paper2);border-color:var(--line2);margin-bottom:10px">Importi come nel <strong>PDA inviato da Pratiche di Scalo</strong>'+(p.inviato?' il '+dIt(p.inviato):'')+': le voci che coincidono con tariffe e importi standard restano automatiche, le altre sono segnate come manuali.</div>';
  h+='<h3>Voci del preventivo</h3><p class="sub">Le voci in corsivo color ottone sono calcolate dalle tariffe o dagli importi standard: scrivi un importo per forzarle, svuota la casella per tornare al calcolo automatico.</p>';
  h+='<div class="scroll"><table><thead><tr><th>Voce</th><th class="num">Importo €</th><th>Origine</th></tr></thead><tbody>';
  S.cfg.voci.forEach(function(v){ var x=pdaVoce(sc,v), man=num((p.items||{})[v.k])!==null;
    h+='<tr><td>'+esc(v.label)+(v.opz?' <span class="chip grey">opzionale</span>':"")+'</td><td class="num" style="width:150px"><input class="num'+(man?"":" auto")+'" data-pv="'+v.k+'" value="'+(man?esc(p.items[v.k]):(x.val?eur(x.val):""))+'" placeholder="'+(x.val?eur(x.val):"0,00")+'" aria-label="'+esc(v.label)+'"></td><td class="sub">'+(man?"manuale":x.orig==="tariffa"?"tariffa: "+esc(x.nota||""):x.orig==="standard"?"importo standard":"")+'</td></tr>'; });
  (p.extra||[]).forEach(function(e,i){ h+='<tr><td><input data-pxd="'+i+'" value="'+esc(e.d)+'" placeholder="descrizione voce aggiuntiva"></td><td class="num" style="width:150px"><input class="num" data-pxv="'+i+'" value="'+esc(e.v)+'"></td><td><button class="btn small" data-pxdel="'+i+'">togli</button></td></tr>'; });
  var t=totali(sc,"pda");
  h+='<tr><td colspan="3"><button class="btn small" id="pdaExtra">+ voce aggiuntiva</button></td></tr>';
  h+='<tr class="tot"><td>Totale esborsi</td><td class="num" id="pdaSub">'+eur(t.sub)+'</td><td></td></tr><tr id="pdaStampRow"'+(t.stamp?"":" hidden")+'><td>Stamp</td><td class="num" id="pdaStamp">'+eur(t.stamp)+'</td><td></td></tr><tr class="tot"><td>TOTALE PDA</td><td class="num" id="pdaTot">'+eur(t.tot)+'</td><td></td></tr></tbody></table></div>';
  h+='<div class="acts" style="margin-top:14px"><button class="btn primary" id="salvaPda">Salva PDA</button><button class="btn" data-doc="pda">Stampa / PDF</button><button class="btn" id="pdaAzzera">Azzera importi manuali</button></div>';
  return h; }
function aggiornaPda(sc){ sc.pda=leggiPda(sc); var t=totali(sc,"pda"), C=S.cfg, gt=num(sc.gt)||0;
  S.cfg.voci.forEach(function(v){ var i=document.querySelector('[data-pv="'+v.k+'"]'); if(!i) return; if(i.value.trim()==="") i.classList.add("auto"); if(!i.classList.contains("auto")) return; var x=pdaVoce(sc,v); i.value=x.val?eur(x.val):""; i.placeholder=x.val?eur(x.val):"0,00";
    var td=i.closest("tr").querySelector("td.sub"); if(td) td.textContent=x.orig==="tariffa"?"tariffa: "+(x.nota||""):x.orig==="standard"?"importo standard":""; });
  var e=function(id,v){ var el=document.getElementById(id); if(el) el.textContent=v; }; e("pdaSub",eur(t.sub)); e("pdaStamp",eur(t.stamp)); e("pdaTot",eur(t.tot)); var r=document.getElementById("pdaStampRow"); if(r) r.hidden=!t.stamp;
  e("pdaTar","Tariffe piloti € "+eur(rate(C.pil,gt))+" · ormeggiatori € "+eur(rate(C.orm,gt))+" · rimorchiatore € "+eur(rate(C.tug,gt))+" per prestazione a questo GT (scaglioni modificabili in Impostazioni → Tariffe)."); }
function leggiPda(sc){ var p=Object.assign({},sc.pda); ["nPil","nOrm","nTug","tugs","anc","chim","stamp","inviato","notes"].forEach(function(k){ p[k]=val("p_"+k); }); p.transfer=val("p_transfer")==="1"; p.items={};
  document.querySelectorAll("[data-pv]").forEach(function(i){ var v=i.value.trim(); if(v!==""&&!i.classList.contains("auto")) p.items[i.getAttribute("data-pv")]=v; else if(v!==""&&i.classList.contains("auto")&&i.value!==i.placeholder) p.items[i.getAttribute("data-pv")]=v; });
  p.extra=[]; document.querySelectorAll("[data-pxd]").forEach(function(i){ var idx=i.getAttribute("data-pxd"), vv=document.querySelector('[data-pxv="'+idx+'"]'); p.extra.push({d:i.value.trim(),v:vv?vv.value.trim():""}); });
  return p; }

/* ---------- fatture fornitori ---------- */
function vistaSpese(sc){ var sp=speseDi(sc.id), F=tuttiFornitori(), e=S.bozza||(S.editSpesa==="nuova"?{id:"",fornitore:"",voce:"",voceLibera:"",numFattura:"",dataFattura:"",totale:"",scadenza:"",descrizione:"",dataPagamento:"",modo:"",note:""}:(S.editSpesa?S.spese[S.editSpesa]:null));
  var h='<div class="acts" style="margin-bottom:10px"><button class="btn primary" id="nuovaSpesa">+ Registra fattura</button><span class="sub">Ogni fattura fornitore va su una voce del conto: il FDA si compone da qui.</span></div>';
  var da=speseDaAbbinare(); if(da.length&&!e){ h+='<details class="warnbox" style="background:var(--paper2);border-color:var(--line2)"><summary>'+da.length+' fatture registrate in <strong>Fatture</strong> in attesa di approdo — abbina a questo scalo</summary><div class="scroll"><table><thead><tr><th>Fornitore</th><th>N. fattura</th><th>Data</th><th class="num">Totale €</th><th>Descrizione</th><th></th></tr></thead><tbody>'+
    da.map(function(s){ return '<tr><td><strong>'+esc(s.fornitore)+'</strong></td><td>'+esc(s.numFattura)+'</td><td>'+dIt(s.dataFattura)+'</td><td class="num">'+eur(s.totale)+'</td><td class="sub">'+esc([s.descrizione,s.note].filter(Boolean).join(" · "))+'</td><td><button class="btn small" data-abbq="'+s.id+'">abbina a questo scalo</button></td></tr>'; }).join("")+'</tbody></table></div></details>'; }
  if(e){ h+='<div class="panel" style="background:var(--paper2)"><div class="panel-b"><div class="grid">'+
    '<div class="field w2"><label for="s_forn">Fornitore</label><input id="s_forn" list="dl_forn" value="'+esc(e.fornitore)+'" placeholder="PILOTI, ORMEGGIATORI, DIRITTI CAPITANERIA…"></div>'+datalist("dl_forn",F)+
    '<div class="field w2"><label for="s_voce">Voce del conto</label><select id="s_voce">'+opt("","(automatica dal fornitore)",e.voce)+S.cfg.voci.map(function(v){ return opt(v.k,v.label,e.voce); }).join("")+opt("libera","Altra voce (scrivi a mano)…",e.voce)+'</select></div>'+
    '<div class="field w2" id="s_voceBox"'+(e.voce==="libera"?"":" hidden")+'><label for="s_voceTesto">Nome della voce (a mano libera)</label><input id="s_voceTesto" list="dl_vlib" value="'+esc(e.voceLibera||"")+'" placeholder="es. Noleggio gru, Spese cantiere, Trasporto…"></div>'+datalist("dl_vlib",vociLibere())+
    '<div class="field"><label for="s_tipo">Documento</label><select id="s_tipo">'+opt("fattura","Fattura",e.tipo||"fattura")+opt("nc","Nota di credito",e.tipo||"fattura")+opt("comm","Ns fattura di commissione al fornitore",e.tipo||"fattura")+'</select></div>'+'<div class="field"><label for="s_fda">Nel FDA</label><select id="s_fda">'+opt("si","Inserisci nel FDA",e.fuoriFda?"no":"si")+opt("no","Non inserire nel FDA",e.fuoriFda?"no":"si")+'</select></div>'+campo("s_num","N. fattura",e.numFattura)+campo("s_data","Data fattura",e.dataFattura,"date")+campo("s_scad","Scadenza",e.scadenza,"date")+
    campo("s_imp","Imponibile €",e.imponibile,"number")+campo("s_ivap","IVA %",e.ivaPerc,"number",{ph:String(S.cfg.conta.ivaDefault||22)})+campo("s_iva","IVA €",e.iva,"number")+campo("s_rit","Ritenuta €",e.ritenuta,"number")+campo("s_tot","Totale fattura €",e.totale,"number")+campo("s_descr","Descrizione",e.descrizione,"text",{cls:"w2"})+
    campo("s_pag","Pagata il",e.dataPagamento,"date")+campo("s_modo","Modo pagamento",e.modo,"text",{ph:"bonifico, RID, contanti…"})+campo("s_note","Note",e.note,"text",{cls:"w2"})+campo("s_all","Allegato (link o riferimento)",e.allegato,"text",{cls:"w2",ph:"link Drive/mail, nome del file…"})+'<div class="field w2" id="s_allBox" data-sp-id="'+esc(e.id||"")+'"></div>'+
    (function(){ if(!S.pagTmp||S.pagTmpFor!==("s:"+(S.editSpesa||"nuova"))){ S.pagTmp=clone(pagamentiDi(e)); S.pagTmpFor="s:"+(S.editSpesa||"nuova"); } return formPagamenti("s_",e); })()+'</div>';
    h+=notaComm("s_commNota",e.tipo==="comm");
    if(S.dupWarn) h+='<div class="warnbox"><strong>Attenzione: fattura già registrata?</strong><ul style="margin:6px 0">'+S.dupWarn.lista.map(function(d){ var o=S.scali[d.s.scalo]||{}; return '<li>'+esc(d.m)+' — prot. '+esc(o.prot)+' '+esc(o.nave)+', '+esc(d.s.fornitore)+(d.s.numFattura?' n. '+esc(d.s.numFattura):"")+' del '+dIt(d.s.dataFattura)+' € '+eur(d.s.totale)+'</li>'; }).join("")+'</ul><div class="acts"><button class="btn" id="dupComunque">Registra comunque</button><button class="btn" id="dupAnnulla">Annulla</button></div></div>';
    h+='<div class="acts" style="margin-top:12px"><button class="btn primary" id="salvaSpesa">Salva fattura</button><button class="btn" id="annullaSpesa">Chiudi</button>'+(e.id?'<button class="btn danger small" id="eliminaSpesa">Elimina</button>':"")+'</div></div></div>'; }
  if(!sp.length) h+='<p class="sub">Nessuna fattura registrata per questo scalo.</p>';
  else{ h+='<div class="scroll"><table><thead><tr><th>Fornitore</th><th>Voce</th><th>N. fattura</th><th>Data</th><th class="num">Totale €</th><th>Pagata</th><th>Note</th></tr></thead><tbody>'; var t=0;
    sp.forEach(function(s){ var v=voce(s.voce); t+=num(s.totale)||0; h+='<tr class="row'+(S.hl===s.id?" hl":"")+'" data-sp="'+s.id+'"><td><strong>'+esc(s.fornitore)+'</strong>'+chipDoppia(s)+'</td><td class="sub">'+esc(nomeVoce(s))+(s.fuoriFda?' <span class="chip grey">fuori FDA</span>':'')+'</td><td>'+esc(s.numFattura)+'</td><td>'+dIt(s.dataFattura)+'</td><td class="num">'+eur(s.totale)+'</td><td>'+chipPag(s)+'</td><td class="sub">'+esc([s.descrizione,s.note].filter(Boolean).join(" · "))+'</td></tr>'; });
    var tf=0; sp.forEach(function(s){ if(s.fuoriFda) tf+=num(s.totale)||0; });
    h+='</tbody><tfoot><tr><td colspan="4">Totale fatture'+(tf?' <span class="sub">(di cui fuori FDA € '+eur(tf)+': nel FDA € '+eur(r2(t-tf))+')</span>':'')+'</td><td class="num">'+eur(t)+'</td><td colspan="2"></td></tr></tfoot></table></div>'; }
  var CS=cassaDi(sc.id); h+='<div class="acts" style="margin-top:14px"><h3 style="margin:0">Spese di cassa dello scalo'+(CS.length?' ('+CS.length+')':'')+'</h3><button class="btn small" id="nuovaCassaScalo">+ Spesa di cassa</button><span class="sub">Contanti spesi per questo scalo (bolli, taxi, varchi…): si registrano nella Prima nota cassa; con «addebita nel FDA» entrano nel consuntivo sulla voce scelta.</span></div>';
  if(CS.length){ var tcs=0; h+='<div class="scroll"><table><thead><tr><th>Data</th><th>Movimento</th><th>Descrizione</th><th>Categoria</th><th class="num">Importo €</th><th>Nel FDA</th></tr></thead><tbody>';
    CS.forEach(function(m){ var u=m.tipo==="uscita"; if(u) tcs+=num(m.importo)||0; h+='<tr class="row" data-cs="'+m.id+'"><td>'+dIt(m.data)+'</td><td>'+(u?'<span class="chip warn">uscita</span>':'<span class="chip ok">entrata</span>')+'</td><td>'+esc(m.descr||"")+(m.fornitore?' <span class="sub">'+esc(m.fornitore)+'</span>':'')+'</td><td class="sub">'+esc(m.categoria||"")+'</td><td class="num">'+eur(m.importo)+'</td><td>'+(u?(m.fda?'<span class="chip ok">nel FDA · '+esc(voce(m.voce)?voce(m.voce).label:(m.descr||"voce libera"))+'</span>':'<span class="chip grey">fuori FDA</span>'):'')+'</td></tr>'; });
    h+='</tbody><tfoot><tr><td colspan="4">Totale uscite di cassa</td><td class="num">'+eur(tcs)+'</td><td></td></tr></tfoot></table></div>'; }
  var cm=commissioniDi(sc.id); if(cm.length){ var tc=0; h+='<h3 style="margin-top:14px">Ns fatture di commissione ai fornitori</h3><p class="sub">Emesse da '+esc(nomeAzienda())+' ai fornitori per questo scalo: non sono costi del FDA; vanno in avere nell\'estratto conto del fornitore.</p><div class="scroll"><table><thead><tr><th>Fornitore</th><th>N. ns fattura</th><th>Data</th><th class="num">Totale €</th><th>Incassata</th><th>Note</th></tr></thead><tbody>';
    cm.forEach(function(s){ tc+=num(s.totale)||0; h+='<tr class="row'+(S.hl===s.id?" hl":"")+'" data-sp="'+s.id+'"><td><strong>'+esc(s.fornitore)+'</strong></td><td>'+esc(s.numFattura)+'</td><td>'+dIt(s.dataFattura)+'</td><td class="num">'+eur(s.totale)+'</td><td>'+chipPag(s)+'</td><td class="sub">'+esc([s.descrizione,s.note].filter(Boolean).join(" · "))+'</td></tr>'; });
    h+='</tbody><tfoot><tr><td colspan="3">Totale ns commissioni</td><td class="num">'+eur(tc)+'</td><td colspan="2"></td></tr></tfoot></table></div>'; }
  return h; }
function notaComm(id,mostra){ return '<p class="sub" id="'+id+'" style="margin:8px 0 0"'+(mostra?'':' hidden')+'><strong>Ns fattura di commissione</strong>: fattura emessa da '+esc(nomeAzienda())+' al fornitore indicato (provvigione). Il totale va in <em>avere</em> nell\'estratto conto di quel fornitore e riduce quanto gli dobbiamo; l\'incasso (o la compensazione) si registra in <em>Pagata il</em> / pagamenti. Non è un costo dello scalo e non entra nel FDA; in Contabilità sta fra le fatture emesse.</p>'; }
function leggiSpesa(sc){ var e=S.editSpesa==="nuova"?{id:nuovoId("sp"),scalo:sc.id}:Object.assign({},S.spese[S.editSpesa]);
  e.fornitore=upper(val("s_forn")); e.numFattura=val("s_num"); e.dataFattura=val("s_data"); e.totale=num(val("s_tot")); e.scadenza=val("s_scad"); e.descrizione=val("s_descr"); e.dataPagamento=val("s_pag"); e.modo=val("s_modo"); e.note=val("s_note");
  e.tipo=val("s_tipo")||"fattura"; e.fuoriFda=val("s_fda")==="no"; e.imponibile=num(val("s_imp")); e.ivaPerc=num(val("s_ivap")); e.iva=num(val("s_iva")); e.ritenuta=num(val("s_rit")); e.allegato=val("s_all"); if(e.tipo==="nc"&&e.totale!==null&&e.totale>0) e.totale=-e.totale;
  e.voce=e.tipo==="comm"?"commissione":(val("s_voce")||vocePerFornitore(e.fornitore,e.descrizione)); e.voceLibera=e.voce==="libera"?val("s_voceTesto"):""; return leggiPagamentiForm("s_",e); }

/* ---------- Fatture: registrazione fatture fornitori e abbinamento all'approdo ---------- */
function speseDaAbbinare(){ var out=[]; for(var k in S.spese){ var s=S.spese[k]; if(!s.scalo||!S.scali[s.scalo]) out.push(s); } out.sort(function(a,b){ return (b.dataFattura||"").localeCompare(a.dataFattura||"")||(a.fornitore||"").localeCompare(b.fornitore||""); }); return out; }
function etichettaScalo(sc){ return (sc.prot||"?")+"/"+String(sc.annoProt||anno(sc.eta)||"").slice(2)+" · "+(sc.nave||"")+(sc.eta?" · ETA "+dIt(sc.eta):"")+(sc.cliente?" · "+sc.cliente:""); }
function giorni(a,b){ if(!a||!b) return null; var d=(new Date(a)-new Date(b))/86400000; return isNaN(d)?null:Math.round(d); }
/* approdi candidati per una fattura: prima gli scali della nave citata in descrizione/note, altrimenti quelli con ETA vicina alla data fattura (da 5 giorni dopo a 45 prima), i più vicini in cima */
function candidatiScalo(s){ var L=listaScali(), t=" "+upper((s.descrizione||"")+" "+(s.note||"")).replace(/[^A-Z0-9]+/g," ")+" ", dataF=s.dataFattura;
  function dist(sc){ var g=giorni(dataF,sc.eta); return g===null?999:Math.abs(g-7); }
  var nave=L.filter(function(sc){ var n=upper(sc.nave||"").replace(/[^A-Z0-9]+/g," ").trim(); return n.length>=4&&t.indexOf(" "+n+" ")>=0; });
  if(nave.length){ nave.sort(function(a,b){ return dist(a)-dist(b); }); return {lista:nave,tipo:"nave",label:"Scali della nave indicata nella descrizione"}; }
  var vic=L.filter(function(sc){ var g=giorni(dataF,sc.eta); return g!==null&&g>=-5&&g<=45; }); vic.sort(function(a,b){ return dist(a)-dist(b); });
  return {lista:vic,tipo:"data",label:"Approdi vicini alla data fattura (i più probabili in cima)"}; }
function optScali(sel,cand){ var L=listaScali(), vid={}; cand.lista.forEach(function(sc){ vid[sc.id]=1; });
  var h=opt("","— scegli l'approdo —",sel);
  if(cand.lista.length) h+='<optgroup label="'+esc(cand.label)+'">'+cand.lista.map(function(sc){ return opt(sc.id,etichettaScalo(sc),sel); }).join("")+'</optgroup>';
  return h+'<optgroup label="Tutti gli scali">'+L.map(function(sc){ return opt(sc.id,etichettaScalo(sc),vid[sc.id]?"":sel); }).join("")+'</optgroup>'; }
function vistaFatture(){ var F=tuttiFornitori(), lst=speseDaAbbinare(), mod=!!(S.editSpesa&&S.editSpesa!=="nuova"&&S.spese[S.editSpesa]);
  var e=S.bozza||(mod?S.spese[S.editSpesa]:{id:"",fornitore:(S.ultimaFatt||{}).fornitore||"",voce:"",voceLibera:"",numFattura:"",dataFattura:(S.ultimaFatt||{}).dataFattura||oggi(),totale:"",scadenza:"",descrizione:"",dataPagamento:"",modo:"",note:""});
  var h='<div class="top"><h1>Fatture fornitori</h1><span class="stato">'+(lst.length?lst.length+' da abbinare':'nessuna in attesa')+'</span></div>';
  h+='<div class="panel"><div class="panel-h"><b>1. Registra la fattura</b><span class="sub">Inserisci le fatture appena arrivano, anche senza sapere ancora lo scalo: l\'approdo si sceglie al passo 2.</span></div><div class="panel-b"><div class="grid">'+
    '<div class="field w2"><label for="f_forn">Fornitore</label><input id="f_forn" list="dl_forn" value="'+esc(e.fornitore)+'" placeholder="PILOTI, ORMEGGIATORI, DIRITTI CAPITANERIA…"></div>'+datalist("dl_forn",F)+
    '<div class="field w2"><label for="f_voce">Voce del conto</label><select id="f_voce">'+opt("","(automatica dal fornitore)",e.voce)+S.cfg.voci.map(function(v){ return opt(v.k,v.label,e.voce); }).join("")+opt("libera","Altra voce (scrivi a mano)…",e.voce)+'</select></div>'+
    '<div class="field w2" id="f_voceBox"'+(e.voce==="libera"?"":" hidden")+'><label for="f_voceTesto">Nome della voce (a mano libera)</label><input id="f_voceTesto" list="dl_vlib" value="'+esc(e.voceLibera||"")+'" placeholder="es. Noleggio gru, Spese cantiere, Trasporto…"></div>'+datalist("dl_vlib",vociLibere())+
    '<div class="field"><label for="f_tipo">Documento</label><select id="f_tipo">'+opt("fattura","Fattura",e.tipo||"fattura")+opt("nc","Nota di credito",e.tipo||"fattura")+opt("comm","Ns fattura di commissione al fornitore",e.tipo||"fattura")+'</select></div>'+'<div class="field"><label for="f_fda">Nel FDA</label><select id="f_fda">'+opt("si","Inserisci nel FDA",e.fuoriFda?"no":"si")+opt("no","Non inserire nel FDA",e.fuoriFda?"no":"si")+'</select></div>'+campo("f_num","N. fattura",e.numFattura)+campo("f_data","Data fattura",e.dataFattura,"date")+campo("f_tot","Totale fattura €",e.totale,"number")+campo("f_descr","Descrizione",e.descrizione,"text",{cls:"w2",ph:"nave, servizio, periodo…"})+'</div>'+
    (function(){ if(!S.pagTmp||S.pagTmpFor!==("f:"+(S.editSpesa||"nuova"))){ S.pagTmp=clone(pagamentiDi(e)); S.pagTmpFor="f:"+(S.editSpesa||"nuova"); }
      var apri=S.fMore!==undefined&&S.fMore!==null?S.fMore:!!(mod||e.scadenza||e.imponibile||e.iva||e.ritenuta||e.dataPagamento||e.modo||e.note||e.allegato||(S.pagTmp&&S.pagTmp.length));
      return '<details class="more" id="f_more"'+(apri?" open":"")+'><summary>Altri dati: imponibile e IVA, ritenuta, scadenza, pagamenti, note, allegato</summary><div class="grid">'+campo("f_scad","Scadenza",e.scadenza,"date")+
        campo("f_imp","Imponibile €",e.imponibile,"number")+campo("f_ivap","IVA %",e.ivaPerc,"number",{ph:String(S.cfg.conta.ivaDefault||22)})+campo("f_iva","IVA €",e.iva,"number")+campo("f_rit","Ritenuta €",e.ritenuta,"number")+
        campo("f_pag","Pagata il",e.dataPagamento,"date")+campo("f_modo","Modo pagamento",e.modo,"text",{ph:"bonifico, RID, contanti…"})+campo("f_note","Note",e.note,"text",{cls:"w2"})+campo("f_all","Allegato (link o riferimento)",e.allegato,"text",{cls:"w2",ph:"link Drive/mail, nome del file…"})+'<div class="field w2" id="s_allBox" data-sp-id="'+esc(e.id||"")+'"></div>'+
        formPagamenti("f_",e)+'</div></details>'; })();
  h+=notaComm("f_commNota",e.tipo==="comm");
  if(S.dupWarn) h+='<div class="warnbox"><strong>Attenzione: fattura già registrata?</strong><ul style="margin:6px 0">'+S.dupWarn.lista.map(function(d){ var o=S.scali[d.s.scalo]||{}; return '<li>'+esc(d.m)+' — '+(o.prot?'prot. '+esc(o.prot)+' '+esc(o.nave):'ancora da abbinare')+', '+esc(d.s.fornitore)+(d.s.numFattura?' n. '+esc(d.s.numFattura):"")+' del '+dIt(d.s.dataFattura)+' € '+eur(d.s.totale)+'</li>'; }).join("")+'</ul><div class="acts"><button class="btn" id="dupComunque">Registra comunque</button><button class="btn" id="dupAnnulla">Annulla</button></div></div>';
  h+='<div class="acts" style="margin-top:12px"><button class="btn primary" id="f_salva">'+(mod?"Salva modifiche":"+ Aggiungi alla lista")+'</button>'+(mod?'<button class="btn" id="f_annulla">Annulla</button><button class="btn danger small" id="f_elimina">Elimina</button>':'<span class="sub">La fattura viene salvata subito nell\'archivio e compare qui sotto.</span>')+'</div></div></div>';
  h+='<div class="panel"><div class="panel-h"><b>2. Abbina all\'approdo</b><span class="sub">Scegli lo scalo di ogni fattura e premi <em>Abbina</em>: la fattura entra nelle fatture e nel conto FDA di quello scalo.</span><div class="spacer"></div>'+(lst.length>1?'<button class="btn" id="f_abbinaTutte">Abbina tutte le selezionate</button>':'')+'</div>';
  if(!lst.length) h+='<div class="panel-b sub">Nessuna fattura in attesa di approdo.</div>';
  else{ h+='<div class="scroll"><table><thead><tr><th>Fornitore</th><th>N. fattura</th><th>Data</th><th class="num">Totale €</th><th>Descrizione</th><th style="min-width:260px">Approdo</th><th></th></tr></thead><tbody>'; var t=0;
    lst.forEach(function(s){ var v=voce(s.voce); t+=num(s.totale)||0; var cand=candidatiScalo(s), vic=cand.lista, pre=(vic.length===1||(cand.tipo==="nave"&&vic.length&&giorni(s.dataFattura,vic[0].eta)!==null))?vic[0].id:"";
      h+='<tr'+(S.hl===s.id?' class="hl"':'')+'><td><button class="btn lnk" data-fmod="'+s.id+'" title="Modifica la fattura"><strong>'+esc(s.fornitore)+'</strong></button>'+chipDoppia(s)+(isComm(s)?' <span class="chip grey">ns commissione</span>':'')+'<div class="sub">'+esc(nomeVoce(s))+'</div></td><td>'+esc(s.numFattura)+'</td><td>'+dIt(s.dataFattura)+'</td><td class="num">'+eur(s.totale)+'</td><td class="sub">'+esc([s.descrizione,s.note].filter(Boolean).join(" · "))+'</td>'+
        '<td><select data-fsc="'+s.id+'" aria-label="Approdo">'+optScali(pre,cand)+'</select>'+(pre?'<div class="sub">proposto: '+(cand.tipo==="nave"?"nave citata nella descrizione"+(vic.length>1?", scalo più vicino alla data fattura":""):"unico scalo vicino alla data fattura")+' — controlla e premi Abbina</div>':vic.length?'<div class="sub">'+vic.length+' scali vicini alla data fattura in cima all\'elenco</div>':'')+'</td><td><button class="btn primary small" data-fabb="'+s.id+'">Abbina</button></td></tr>'; });
    h+='</tbody><tfoot><tr><td colspan="3">'+lst.length+' fatture da abbinare</td><td class="num">'+eur(t)+'</td><td colspan="3"></td></tr></tfoot></table></div>'; }
  return h+'</div>'; }
function leggiFattura(){ var mod=!!(S.editSpesa&&S.editSpesa!=="nuova"&&S.spese[S.editSpesa]), e=mod?Object.assign({},S.spese[S.editSpesa]):{id:nuovoId("sp"),scalo:""};
  e.fornitore=upper(val("f_forn")); e.numFattura=val("f_num"); e.dataFattura=val("f_data"); e.totale=num(val("f_tot")); e.scadenza=val("f_scad"); e.descrizione=val("f_descr"); e.dataPagamento=val("f_pag"); e.modo=val("f_modo"); e.note=val("f_note");
  e.tipo=val("f_tipo")||"fattura"; e.fuoriFda=val("f_fda")==="no"; e.imponibile=num(val("f_imp")); e.ivaPerc=num(val("f_ivap")); e.iva=num(val("f_iva")); e.ritenuta=num(val("f_rit")); e.allegato=val("f_all"); if(e.tipo==="nc"&&e.totale!==null&&e.totale>0) e.totale=-e.totale;
  e.voce=e.tipo==="comm"?"commissione":(val("f_voce")||vocePerFornitore(e.fornitore,e.descrizione)); e.voceLibera=e.voce==="libera"?val("f_voceTesto"):""; return leggiPagamentiForm("f_",e); }
async function abbina(id,scId){ var s=S.spese[id], sc=S.scali[scId]; if(!s||!sc) return false; s.scalo=scId; await scriviSpesa(s); return true; }

/* ---------- conto: PDA / FDA / confronto ---------- */
