function vistaConto(sc){ var mode=S.contoMode, r=righeConto(sc,mode==="pda"?"pda":"fda"), tp=totali(sc,"pda"), tf=totali(sc,"fda"), f=sc.fda, nz=S.cfg.doc.nascondiZero;
  var h='<div class="acts" style="margin-bottom:12px"><div class="modes">'+[["pda","PDA preventivo"],["fda","FDA consuntivo"],["confronto","Confronto"]].map(function(m){ return '<button data-mode="'+m[0]+'" aria-pressed="'+(mode===m[0])+'">'+m[1]+'</button>'; }).join("")+'</div><div class="spacer"></div><button class="btn" data-doc="'+(mode==="pda"?"pda":"fda")+'">Stampa / PDF</button></div>';
  if(mode==="fda"){ var NS=vociNsConto(sc); h+='<p class="sub">Il consuntivo rispecchia le fatture registrate e assegnate a questo scalo: quelle dei fornitori voce per voce e la ns fattura '+esc(nomeAzienda())+' scomposta nelle sue voci (agency fees, ISPS, bolli…). Dove c\'è una fattura l\'importo non si può forzare: si corregge la fattura. '+(NS.n?'Ns fattura assegnata: € '+eur(NS.tot)+(NS.n>1?' ('+NS.n+' documenti)':'')+'; le voci interne che non compaiono in fattura valgono zero.':'Senza ns fattura assegnata, le voci interne senza fattura (H.Master, informer, ISPS, bolli…) restano come nel PDA e un importo scritto qui forza la voce.')+'</p>'; }
  h+='<div class="scroll"><table><thead><tr><th>Voce</th>'+(mode==="confronto"?'<th class="num">PDA €</th><th class="num">FDA €</th><th class="num">Diff. €</th><th>Origine FDA</th>':'<th class="num">'+(mode==="pda"?"PDA":"FDA")+' €</th><th>Origine</th>')+'</tr></thead><tbody>';
  r.forEach(function(x){ var pv=x.pda.val, fv=x.fda.val; if(nz&&!pv&&!fv&&!x.extra) return; var orig=mode==="pda"?x.pda:x.fda;
    if(mode==="confronto"){ var d=r2(fv-pv); h+='<tr><td>'+esc(x.label)+'</td><td class="num">'+(pv?eur(pv):"—")+'</td><td class="num">'+(fv?eur(fv):"—")+'</td><td class="num '+(d>0.005?"pos":d<-0.005?"neg":"")+'">'+(Math.abs(d)>0.005?(d>0?"+":"")+eur(d):"")+'</td><td class="sub">'+esc(x.fda.orig==="fatture"?x.fda.nota:x.fda.orig)+'</td></tr>'; }
    else if(mode==="fda"&&!x.extra){ var fat=orig.orig==="fatture", man=!fat&&num((f.items||{})[x.k])!==null; h+='<tr><td>'+esc(x.label)+'</td><td class="num" style="width:150px"><input class="num'+(man?"":" auto")+(fat?" ro":"")+'" data-fv="'+x.k+'"'+(fat?' readonly title="Importo dalle fatture registrate: per cambiarlo modifica la fattura"':'')+' value="'+(man?esc(f.items[x.k]):(fv?eur(fv):""))+'" placeholder="'+(fv?eur(fv):"0,00")+'"></td><td class="sub">'+(man?"manuale":fat?esc(orig.nota)+(orig.manuale!==null&&orig.manuale!==undefined&&Math.abs(orig.manuale-fv)>0.005?' <span class="chip warn">importo manuale € '+eur(orig.manuale)+' non usato</span>':''):orig.orig==="standard"?"come da PDA":esc(orig.orig||""))+'</td></tr>'; }
    else h+='<tr><td>'+esc(x.label)+'</td><td class="num">'+eur(mode==="pda"?pv:fv)+'</td><td class="sub">'+esc(orig.nota||orig.orig||"")+'</td></tr>'; });
  if(mode==="fda"){ (f.extra||[]).forEach(function(e,i){ h+='<tr><td><input data-fxd="'+i+'" value="'+esc(e.d)+'" placeholder="voce aggiuntiva"></td><td class="num" style="width:150px"><input class="num" data-fxv="'+i+'" value="'+esc(e.v)+'"></td><td><button class="btn small" data-fxdel="'+i+'">togli</button></td></tr>'; });
    h+='<tr><td colspan="3"><button class="btn small" id="fdaExtra">+ voce aggiuntiva</button></td></tr><tr><td>Stamp</td><td class="num"><input class="num" id="f_stamp" value="'+esc(f.stamp)+'"></td><td></td></tr>'; }
  var cols=mode==="confronto"?[tp.tot,tf.tot]:[mode==="pda"?tp.tot:tf.tot];
  if(mode==="confronto"){ var dd=r2(tf.tot-tp.tot); h+='<tr class="tot"><td>TOTALE</td><td class="num">'+eur(tp.tot)+'</td><td class="num">'+eur(tf.tot)+'</td><td class="num '+(dd>0?"pos":dd<0?"neg":"")+'">'+(dd>0?"+":"")+eur(dd)+'</td><td class="sub">'+(tp.stamp||tf.stamp?"incl. stamp":"")+'</td></tr>'; }
  else h+='<tr class="tot"><td>TOTALE '+(mode==="pda"?"PDA":"FDA")+'</td><td class="num">'+eur(cols[0])+'</td><td></td></tr>';
  h+='</tbody></table></div>';
  if(mode==="fda") h+='<div class="grid" style="margin-top:12px">'+campo("f_inviato","FDA inviato il",f.inviato,"date")+campo("f_numero","N. fattura (FDA emesso)",f.numero||"","text",{ph:fdaRif(sc).daNs?"da ns fattura: "+fdaRif(sc).numero:""})+campo("f_dataFatt","Data fattura",f.data||"","date")+'<div class="field"><label>&nbsp;</label><button class="btn small" id="fdaNum" title="Assegna il prossimo numero progressivo dell\'anno">assegna il prossimo numero</button></div></div><div class="acts" style="margin-top:12px"><button class="btn primary" id="salvaFda">Salva FDA</button><span class="sub">Il numero compare sul documento FDA e nel registro <em>Fatture emesse</em> della Contabilità.</span></div>';
  if(mode==="fda"){ var SP=speseDi(sc.id); if(SP.length){ var tIn=0,tOut=0; h+='<h3 style="margin-top:16px">Fatture di questo scalo: nel FDA o fuori</h3><p class="sub">Una fattura <strong>fuori FDA</strong> non viene addebitata al cliente ma resta nel registro, nello scadenzario, nell\'estratto conto del fornitore e nella prima nota. Si cambia anche qui, senza riaprire la fattura.</p><div class="scroll"><table><thead><tr><th>Fornitore</th><th>Voce</th><th>N. fattura</th><th>Data</th><th class="num">Totale €</th><th>Nel FDA</th></tr></thead><tbody>';
      SP.forEach(function(x){ var fuori=!!x.fuoriFda; if(fuori) tOut+=num(x.totale)||0; else tIn+=num(x.totale)||0; h+='<tr class="'+(fuori?"":"")+'"><td><strong>'+esc(x.fornitore)+'</strong></td><td class="sub">'+esc(nomeVoce(x))+'</td><td>'+esc(x.numFattura)+'</td><td>'+dIt(x.dataFattura)+'</td><td class="num">'+eur(x.totale)+'</td><td>'+(fuori?'<span class="chip grey">fuori FDA</span> <button class="btn small" data-fdatog="'+x.id+'">rimetti nel FDA</button>':'<span class="chip ok">nel FDA</span> <button class="btn small" data-fdatog="'+x.id+'">togli dal FDA</button>')+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="4">Nel FDA € '+eur(tIn)+(tOut?' · fuori FDA € '+eur(tOut):'')+'</td><td class="num">'+eur(r2(tIn+tOut))+'</td><td></td></tr></tfoot></table></div>'; } }
  if(mode==="confronto"){ var c=r.filter(function(x){ return Math.abs(x.fda.val-x.pda.val)>0.5; }).length; h+='<p class="sub" style="margin-top:10px">'+(c?c+" voci si scostano dal preventivo oltre 50 centesimi.":"Consuntivo allineato al preventivo.")+' Le differenze positive (rosso) sono costi in più rispetto al PDA inviato al cliente.</p>'; }
  return h; }
function leggiFda(sc){ var f=Object.assign({},sc.fda); f.items={}; document.querySelectorAll("[data-fv]").forEach(function(i){ var v=i.value.trim(); if(v!==""&&(!i.classList.contains("auto")||i.value!==i.placeholder)) f.items[i.getAttribute("data-fv")]=v; });
  f.extra=[]; document.querySelectorAll("[data-fxd]").forEach(function(i){ var idx=i.getAttribute("data-fxd"), vv=document.querySelector('[data-fxv="'+idx+'"]'); f.extra.push({d:i.value.trim(),v:vv?vv.value.trim():""}); }); f.stamp=val("f_stamp"); f.inviato=val("f_inviato"); f.numero=val("f_numero"); f.data=val("f_dataFatt"); return f; }

/* ---------- incassi ---------- */
function vistaIncassi(sc){ var B=S.cfg.banche, inc=sc.incassi||[], tot=incassato(sc), res=r2(totFda(sc)-tot);
  var h='<div class="grid">'+campo("c_importo","Importo bonifico €","","number")+campo("c_data","Data",oggi(),"date")+'<div class="field"><label for="c_banca">Banca</label><select id="c_banca">'+B.map(function(b){ return opt(b.id,b.nome,sc.banca); }).join("")+opt("cassa","Cassa (contanti)",sc.banca)+'</select></div>'+campo("c_note","Riferimento",'',"text",{cls:"w2",ph:"es. acconto PDA, saldo FDA"})+'</div>'+
    '<div class="acts" style="margin-top:10px"><button class="btn primary" id="addIncasso">Registra incasso</button><span class="sub">'+(res>0.005?"Residuo da incassare € "+eur(res):tot?"Scalo saldato":"")+'</span></div>';
  if(inc.length){ h+='<div class="scroll" style="margin-top:12px"><table><thead><tr><th>Data</th><th>Banca</th><th>Riferimento</th><th class="num">Importo €</th><th></th></tr></thead><tbody>';
    inc.forEach(function(i,idx){ var b=B.filter(function(x){ return x.id===i.banca; })[0]; h+='<tr><td>'+dIt(i.data)+'</td><td>'+esc(b?b.nome:i.banca)+'</td><td>'+esc(i.note)+'</td><td class="num">'+eur(i.importo)+'</td><td><button class="btn small" data-incdel="'+idx+'">togli</button></td></tr>'; });
    h+='</tbody><tfoot><tr><td colspan="3">Totale incassato</td><td class="num">'+eur(tot)+'</td><td></td></tr></tfoot></table></div>'; }
  return h; }

/* ---------- fornitori: estratto conto ---------- */
function vistaFornitori(){ var F=tuttiFornitori(), f=S.forn||F[0]||"", anni={}, righe=[];
  for(var k in S.spese){ var s=S.spese[k]; if(upper(s.fornitore)!==f) continue; var sc=S.scali[s.scalo]||{}; anni[anno(s.dataFattura||sc.eta)]=1; if(S.ecAnno&&anno(s.dataFattura||sc.eta)!==S.ecAnno) continue;
    if(S.fornStato==="aperte"&&statoSpesa(s)==="pagata") continue; if(S.fornStato==="pagate"&&statoSpesa(s)!=="pagata") continue; righe.push({s:s,sc:sc}); }
  righe.sort(function(a,b){ return (a.s.dataFattura||a.sc.eta||"").localeCompare(b.s.dataFattura||b.sc.eta||""); });
  var tot=0, ape=0; righe.forEach(function(r){ tot+=num(r.s.totale)||0; if(statoSpesa(r.s)!=="pagata") ape+=residuoDi(r.s); });
  var h='<div class="top"><h1>Fornitori</h1><span class="stato">estratto conto per fornitore</span></div>';
  h+='<div class="panel"><div class="panel-h"><div class="field"><select id="ecForn" aria-label="Fornitore">'+F.map(function(x){ return opt(x,etichettaForn(x),f); }).join("")+'</select></div>'+
     '<div class="field"><select id="ecStato">'+opt("aperte","da pagare",S.fornStato)+opt("pagate","pagate",S.fornStato)+opt("tutte","tutte",S.fornStato)+'</select></div>'+
     '<div class="field"><select id="ecAnno">'+opt("","tutti gli anni",S.ecAnno)+Object.keys(anni).sort().reverse().map(function(y){ return opt(y,y,S.ecAnno); }).join("")+'</select></div><div class="spacer"></div><span class="sub">'+righe.length+' fatture · totale € '+eur(tot)+(ape?' · aperte € '+eur(ape):"")+'</span></div>';
  if(!F.length) h+='<div class="panel-b sub">Nessuna fattura registrata.</div>';
  else{ h+='<div class="scroll"><table><thead><tr><th>Data fatt.</th><th>N. fattura</th><th>Prot.</th><th>Nave</th><th>Voce</th><th class="num">Totale €</th><th>Pagata</th><th></th></tr></thead><tbody>';
    righe.forEach(function(r){ var s=r.s, sc=r.sc, v=voce(s.voce); h+='<tr><td>'+dIt(s.dataFattura)+'</td><td>'+esc(s.numFattura)+'</td><td>'+(sc.id?'<button class="btn lnk" data-go="'+esc(sc.id)+'">'+esc(sc.prot||"?")+'/'+String(sc.annoProt||"").slice(2)+'</button>':'<button class="btn lnk" data-abbina="'+s.id+'">da abbinare</button>')+'</td><td>'+esc(sc.nave||"")+chipDoppia(s)+(sc.pagDir?' <span class="chip grey">PAG DIR</span>':"")+'</td><td class="sub">'+esc(nomeVoce(s))+(s.fuoriFda?' <span class="chip grey">fuori FDA</span>':'')+'</td><td class="num">'+eur(s.totale)+'</td><td>'+chipPag(s)+'</td><td>'+(statoSpesa(s)==="pagata"?'<button class="btn small" data-riapri="'+s.id+'">riapri</button>':'<button class="btn small" data-paga="'+s.id+'">segna pagata oggi</button>')+'</td></tr>'; });
    h+='</tbody><tfoot><tr><td colspan="5">Totale</td><td class="num">'+eur(tot)+'</td><td colspan="2"></td></tr></tfoot></table></div>'; }
  return h+'</div>'; }

/* ---------- riepilogo ---------- */
function riepilogo(){ var lst=listaScali(), Y=S.anno||String(new Date().getFullYear()), anni={}; lst.forEach(function(s){ anni[anno(s.eta||s.creato)]=1; }); var ann=lst.filter(function(s){ return anno(s.eta||s.creato)===Y; });
  var tp=0,tf=0,inc=0,daInc=0,prev=0; ann.forEach(function(s){ var p=totPda(s),f=totFda(s),i=incassato(s); tp+=p; tf+=f; inc+=i; if(!s.pagDir&&f>i) daInc+=f-i; if(statoScalo(s).t==="preventivo") prev++; });
  var h='<div class="top"><h1>Riepilogo</h1><div class="field"><select id="rAnno" aria-label="Anno">'+Object.keys(anni).sort().reverse().map(function(y){ return opt(y,y,Y); }).join("")+(anni[Y]?"":opt(Y,Y,Y))+'</select></div></div>';
  h+='<div class="tiles"><div class="tile"><div class="k">Scali '+Y+'</div><div class="v">'+ann.length+'</div><div class="s">'+prev+' ancora a preventivo</div></div>'+
    '<div class="tile"><div class="k">Totale PDA</div><div class="v">€ '+eur(tp)+'</div><div class="s">preventivi inviati</div></div>'+
    '<div class="tile '+(tf>tp?"warn":"")+'"><div class="k">Totale FDA</div><div class="v">€ '+eur(tf)+'</div><div class="s">'+(tf&&tp?(tf>=tp?"+":"")+eur(tf-tp)+" rispetto ai PDA":"")+'</div></div>'+
    '<div class="tile '+(daInc>0?"no":"ok")+'"><div class="k">Da incassare</div><div class="v">€ '+eur(daInc)+'</div><div class="s">incassato € '+eur(inc)+'</div></div>'+
    '<div class="tile '+(daPagare()>0?"warn":"")+'"><div class="k">Da pagare ai fornitori</div><div class="v">€ '+eur(daPagare())+'</div><div class="s">fatture aperte, tutti gli anni</div></div></div>';
  var g=gruppiDoppioni(); if(g.length){ h+='<div class="warnbox"><details'+(g.length<=3?" open":"")+'><summary>'+g.length+' possibili fatture addebitate 2 volte</summary><ul style="margin:6px 0 0">'+g.map(function(x){ return '<li>'+esc(x.m)+': '+x.lista.map(function(s){ var sc=S.scali[s.scalo]||{}; return '<button class="btn lnk" data-go="'+esc(sc.id||"")+'" data-hl="'+s.id+'">prot. '+esc(sc.prot||"?")+' '+esc(sc.nave||"")+'</button> '+esc(s.fornitore)+' € '+eur(s.totale); }).join(" · ")+'</li>'; }).join("")+'</ul></details></div>'; }
  /* scostamenti medi per voce: dove il preventivo sbaglia di più */
  var acc={}; ann.forEach(function(s){ if(!totFda(s)) return; righeConto(s,"fda").forEach(function(x){ if(x.extra) return; var a=acc[x.k]||(acc[x.k]={label:x.label,p:0,f:0,n:0}); a.p+=x.pda.val; a.f+=x.fda.val; if(x.pda.val||x.fda.val) a.n++; }); });
  var sc=Object.keys(acc).map(function(k){ return acc[k]; }).filter(function(a){ return a.n&&Math.abs(a.f-a.p)>0.5; }).sort(function(a,b){ return Math.abs(b.f-b.p)-Math.abs(a.f-a.p); }).slice(0,10);
  h+='<div class="panel"><div class="panel-h"><h2>Preventivo e consuntivo per voce</h2><span class="sub">scali '+Y+' con FDA · dove il PDA si scosta di più</span></div>';
  if(!sc.length) h+='<div class="panel-b sub">Nessuno scostamento rilevante: PDA e FDA coincidono, oppure non ci sono ancora consuntivi.</div>';
  else{ h+='<div class="scroll"><table><thead><tr><th>Voce</th><th class="num">Scali</th><th class="num">PDA €</th><th class="num">FDA €</th><th class="num">Diff. €</th><th class="num">Diff. %</th></tr></thead><tbody>';
    sc.forEach(function(a){ var d=a.f-a.p; h+='<tr><td>'+esc(a.label)+'</td><td class="num">'+a.n+'</td><td class="num">'+eur(a.p)+'</td><td class="num">'+eur(a.f)+'</td><td class="num '+(d>0?"pos":"neg")+'">'+(d>0?"+":"")+eur(d)+'</td><td class="num">'+(a.p?((d/a.p*100).toFixed(0)+"%"):"—")+'</td></tr>'; }); h+='</tbody></table></div>'; }
  h+='</div>';
  var mesi=[]; for(var i=0;i<12;i++) mesi.push({n:0,p:0,f:0}); ann.forEach(function(s){ var m=parseInt((s.eta||s.creato||"").slice(5,7),10)-1; if(m>=0){ mesi[m].n++; mesi[m].p+=totPda(s); mesi[m].f+=totFda(s); } });
  h+='<div class="panel"><div class="panel-h"><h2>Scali per mese</h2></div><div class="scroll"><table><thead><tr><th>Mese</th><th class="num">Scali</th><th class="num">PDA €</th><th class="num">FDA €</th></tr></thead><tbody>';
  mesi.forEach(function(m,i){ if(!m.n) return; h+='<tr><td>'+MESI[i]+'</td><td class="num">'+m.n+'</td><td class="num">'+eur(m.p)+'</td><td class="num">'+eur(m.f)+'</td></tr>'; }); h+='</tbody></table></div></div>';
  return h; }

/* ---------- guida ---------- */
function guida(){ return '<div class="top"><h1>Guida</h1></div><div class="panel help"><div class="panel-b">'+
 '<p><strong>Portolano</strong> unisce in un solo archivio la pratica di scalo (dati nave e viaggio, come in <em>Pratiche di Scalo</em>) e il mastrino dei conti nave (fatture fornitori, PDA/FDA, incassi, come in <em>Mastrino Approdi</em>). Ogni scalo è una scheda con sei pagine.</p>'+
 '<p><strong>Nave &amp; viaggio</strong> — anagrafica della nave (IMO, bandiera, GT/NT, LOA…) e del viaggio (ETA/ETD, ormeggio, operazione, carico, cliente). Scrivendo il nome di una nave già in archivio, GT/NT e dati si ripropongono da soli. <strong>Dati da Pratiche di Scalo</strong>: in cima alla pagina si carica il file esportato dall\'altra app (Archivio → <em>Estrai dati</em> = PORTOLANO_DATI_*.json, o Impostazioni → <em>Esporta archivio</em> = BACKUP_PRATICHE_*.json), poi <em>Scegli la pratica</em>: l\'elenco mette in cima le pratiche della stessa nave/IMO o della stessa data e con <em>Carica</em> nave, viaggio e (se vuoi) il PDA entrano nello scalo. Il file resta in memoria sul dispositivo: per gli scali successivi basta <em>Scegli la pratica</em>. <em>Importa tutte nell\'archivio</em> crea o aggiorna uno scalo per ogni pratica. In Pratiche di Scalo il pulsante <em>Per Portolano</em> (archivio, o in fondo alla pratica) salva il file di <strong>una sola nave</strong> (PORTOLANO_NAVE_*.json) con il <strong>PDA inviato</strong>: caricato nella scheda, nave, viaggio e PDA entrano nello scalo da soli, con gli stessi importi inviati al cliente. Premendo <em>+ Nuovo scalo</em> uno scalo vuoto già aperto viene riusato e gli scali lasciati vuoti si eliminano da soli.</p>'+
 '<p><strong>Intestazione</strong> — il destinatario del conto (Messrs) riga per riga, riprendibile dagli scali precedenti, e la banca da indicare sul documento. La carta intestata dell\'agenzia (ragione sociale, indirizzo, recapiti, P.IVA, logo, colore, lingua, firma) si imposta una volta in <em>Impostazioni → Intestazione</em> e vale per tutti i documenti.</p>'+
 '<p><strong>PDA preventivo</strong> — calcolato dalle tariffe per scaglioni di GT: piloti, ormeggiatori e rimorchiatori × numero di prestazioni (con trasferimento rimorchiatori a 2 mezzi), tassa d\'ancoraggio per NT, chimico, più gli importi standard delle voci d\'agenzia. Ogni voce si può forzare a mano; le voci in corsivo ottone sono automatiche. Gli scaglioni sono quelli dei fogli PILOTI, ORMEGGIATORI, TUG e TASSA ANC del file APPRODO.xlsx e si modificano in <em>Impostazioni → Tariffe</em>.</p>'+
 '<p><strong>Fatture fornitori</strong> — ogni fattura si registra sulla voce del conto (proposta automaticamente dal fornitore: PILOTI → Pilotage, SIDRA → Fresh water…). Se una fattura risulta già registrata (stesso fornitore e numero, o stessa nave/importo/data) l\'app avvisa prima di salvare e la segna con <span class="chip no">addebitata 2 volte</span> ovunque compaia. <strong>Ns fattura di commissione</strong>: nel campo <em>Documento</em> scegli «Ns fattura di commissione al fornitore» per registrare la provvigione che l\'azienda fattura a un fornitore (rimorchiatori, piloti…): non è un costo dello scalo, in Contabilità è una fattura emessa e nell\'estratto conto del fornitore va in avere, riducendo quanto gli dobbiamo; il suo incasso o la compensazione si registra come pagamento.</p>'+
 '<p><strong>Conto PDA / FDA</strong> — il consuntivo rispecchia le fatture registrate e assegnate allo scalo (tranne quelle contrassegnate <em>Non inserire nel FDA</em> nella registrazione: restano nel registro, nello scadenzario, nell\'estratto conto del fornitore e nella prima nota, ma non vengono addebitate al cliente): quelle dei fornitori voce per voce e la ns fattura Fratelli Bonanno scomposta nelle sue voci (agency fees, ISPS, bolli, dogana…), il cui numero e data compaiono anche sul documento FDA; le voci interne senza fattura (H.Master, informer, ISPS, bolli…) sono riprese dal PDA solo finché allo scalo non è assegnata una ns fattura; il <em>Confronto</em> mette a fianco preventivo e consuntivo voce per voce e in rosso i costi in più. <strong>Stampa / PDF</strong> apre il documento con carta intestata, Messrs, tabella nave, voci, totale, banca e firma: si salva in PDF dalla finestra di stampa del browser.</p>'+
 '<p><strong>Incassi</strong> — bonifici ricevuti dal cliente; lo stato dello scalo (preventivo, da incassare, parziale, saldato) si aggiorna da solo. Con <em>PAG DIR</em> il cliente paga i fornitori direttamente e lo scalo resta fuori dai residui.</p>'+
 '<p><strong>Fatture</strong> — la maschera per registrare le fatture fornitori appena arrivano, anche in blocco e senza conoscere ancora lo scalo: al passo 2 si sceglie l\'approdo (in cima all\'elenco gli scali con ETA vicina alla data fattura) e con <em>Abbina</em> la fattura entra nel conto FDA di quello scalo. Le fatture in attesa compaiono anche nella scheda di ogni scalo (<em>abbina a questo scalo</em>) e nell\'estratto conto fornitori come <em>da abbinare</em>.</p>'+
 '<p><strong>General infos e ricerca</strong> — all\'apertura la pagina <em>General infos</em> mostra navi in porto e in arrivo, fatture in scadenza, clienti in ritardo e fatture da abbinare; la casella in alto a sinistra cerca in tutto l\'archivio (navi, IMO, clienti, fornitori, numeri di fattura). Ogni fattura può avere <em>imponibile, IVA e ritenuta</em> (il totale si calcola da solo), essere una <em>nota di credito</em>, avere <em>più pagamenti</em> (acconti) e un <em>allegato</em> (link, oppure il PDF conservato in questo browser). In <em>Impostazioni → Archivio</em> si chiude il periodo contabile, si imposta il backup automatico e si consulta il registro delle modifiche.</p>'+
 '<p><strong>Prima nota cassa</strong> — in Contabilità, il registro di cassa: spese quotidiane in contanti (bolli, taxi, varchi, cancelleria…), prelievi dalla banca e versamenti in banca, entrate; saldo progressivo e saldo di cassa a oggi. Un movimento può essere legato a uno scalo e, con «addebita nel FDA», entra nel consuntivo sulla voce scelta. Vi compaiono da soli anche i pagamenti di fatture fatti in contanti e gli incassi registrati su «Cassa (contanti)».</p>'+
 '<p><strong>Contabilità</strong> — i prospetti da contabile, tutti esportabili in CSV (Excel) e stampabili: <em>Registro fatture</em> ricevute con filtri e ricerca; <em>Scadenzario fornitori</em> (sospesi passivi per fornitore, con scadenza = data fattura + 30 giorni salvo scadenza indicata, e ritardo in giorni); <em>Partite aperte clienti</em> (conti FDA non ancora incassati, per cliente, con anzianità); <em>Estratto conto cliente</em> (addebiti FDA e incassi in ordine di data con saldo progressivo); <em>Prima nota</em> (incassi e pagamenti per mese e per banca). Nelle fatture la voce del conto può essere anche scritta a mano libera (<em>Altra voce</em>): nel FDA le fatture con lo stesso nome si sommano in una riga e si confrontano con la voce aggiuntiva del PDA che ha lo stesso nome.</p>'+
 '<p><strong>Fatture elettroniche</strong> — nella pagina <em>Fatture</em> il riquadro <em>Importa fatture elettroniche (XML)</em> legge i file XML (o .p7m) ricevuti dallo SDI: fornitore, numero, data, imponibile, IVA, ritenuta, totale, scadenza e descrizione si compilano da soli, l\'app propone la voce del conto e lo scalo e segnala le fatture già registrate; il fornitore scelto per una partita IVA viene ricordato per le volte successive.</p>'+
 '<p><strong>Importazione fatture (XML, PDF, ZIP)</strong> — nella pagina <em>Fatture</em> e nella pagina <em>Fornitori</em> puoi caricare gli XML/P7M dello SDI, i PDF delle fatture (letti dal testo; le scansioni senza testo non si leggono) o un intero <em>.zip</em> con tante fatture, anche in cartelle. Fornitore, voce, numero, importi e approdo vengono proposti da soli (nave, IMO o protocollo citati nel testo, altrimenti l\'approdo vicino alla data con un PDA compatibile); la colonna <em>Controlli</em> segnala le incoerenze: fattura già registrata, fornitore nuovo o diverso da quello della pagina, nessun approdo o più approdi possibili, importo lontano dal PDA, scalo già saldato, fattura intestata a un\'altra azienda.</p><p><strong>NS FATTURA = Fratelli Bonanno</strong> — le fatture registrate con fornitore <em>NS FATTURA</em> sono le fatture emesse dall\'azienda (agency fees). Nella registrazione e nel conto PDA/FDA restano una voce distinta come sempre; in <em>Contabilità</em> invece prendono il nome dell\'azienda (Impostazioni → Contabilità) e sono trattate come fatture <em>emesse</em>: stanno nel registro <em>Fatture emesse</em> e nel <em>Registro IVA</em> tra le vendite (IVA a debito), non tra le fatture ricevute, lo scadenzario fornitori o i pagamenti; nella pagina <em>Fornitori</em> il loro estratto conto è quello delle fatture emesse (fatturato, incassato, da incassare).</p>'+
 '<p><strong>Fatture emesse</strong> — nel <em>Conto PDA / FDA</em> il FDA può ricevere un numero progressivo di fattura (<em>assegna il prossimo numero</em>, formato in Impostazioni → Contabilità) e una data: compaiono sul documento stampato e nel registro <em>Fatture emesse</em> della Contabilità, che segnala numeri mancanti o doppi e mostra incassato e residuo per ogni fattura.</p>'+
 '<p><strong>Statistiche</strong> — in Contabilità, confronto anno su anno per cliente, nave, fornitore, operazione, ormeggio o mese: scali, FDA, costi fornitori, FDA − fatture e incassi, con variazione percentuale.</p>'+
 '<p><strong>Estratti conto</strong> — la pagina <em>Fornitori</em> e, in Contabilità, <em>Estratto conto cliente</em> mostrano i movimenti in ordine di data con saldo progressivo: fatture (o conti FDA) da una parte, pagamenti (o incassi) dall\'altra, totali per mese, stato di ogni documento e riquadri con fatturato, pagato, saldo e scaduto. In alto la striscia dei fornitori/clienti con saldo aperto: un tocco e si apre il loro estratto. I pulsanti <em>Stampa / PDF</em> (su carta intestata, con l\'elenco dei documenti ancora aperti), <em>Excel</em>, <em>CSV</em> e <em>Invia</em> (e-mail pronta, testo anche negli appunti) lo rendono estraibile. <em>Elenco fatture</em> mostra la sola lista delle fatture.</p>'+
 '<p><strong>Uso rapido</strong> — nella barra laterale <em>+ Scalo</em> e <em>+ Fattura</em> aprono subito una scheda nuova. Nella maschera fatture i campi essenziali sono in cima e gli altri (IVA, ritenuta, scadenza, pagamenti, note, allegato) sotto <em>Altri dati</em>; <em>Invio</em> salva; fornitore e data dell\'ultima fattura restano proposti per la successiva. Negli <em>Scali</em> i filtri sono pulsanti (in porto, in arrivo, da incassare…) e le colonne si ordinano toccando l\'intestazione. Sul telefono le tabelle diventano schede e la barra delle sezioni resta fissa in alto.</p>'+
 '<p><strong>Fornitori</strong> — estratto conto per fornitore con fatture aperte e pagate, per anno; <strong>Riepilogo</strong> — totali dell\'anno, da incassare e da pagare, doppioni, voci dove il preventivo si scosta di più dal consuntivo, scali per mese.</p>'+
 '<p><strong>Archivio</strong> — i dati restano in questo browser e, quando l\'app è aperta da claude.ai, anche nell\'archivio condiviso con i colleghi. In <em>Impostazioni → Archivio</em> si esporta un backup completo, si reimporta, e si importano i dati esistenti dal backup di Pratiche di Scalo (file BACKUP_PRATICHE_*.json) e dal CSV esportato dal Mastrino Approdi (mastrino_approdi.csv).</p>'+
 '</div></div>'; }

/* ---------- impostazioni ---------- */
