function impostazioni(){ var tabs=[["agenzia","Intestazione"],["banche","Banche"],["tariffe","Tariffe"],["voci","Voci del conto"],["liste","Liste"],["archivio","Archivio"]], C=S.cfg;
  var h='<div class="top"><h1>Impostazioni</h1></div><div class="panel"><div class="subtabs" role="tablist">'+tabs.map(function(t){ return '<button role="tab" data-imp="'+t[0]+'" aria-selected="'+(S.imp===t[0])+'">'+t[1]+'</button>'; }).join("")+'</div><div class="panel-b">';
  if(S.imp==="agenzia"){ var a=C.ag, d=C.doc;
    h+='<h3>Carta intestata dell\'agenzia</h3><div class="grid" style="margin:8px 0 14px">'+campo("ag_nome","Ragione sociale",a.nome,"text",{cls:"w2"})+campo("ag_nomeBreve","Nome breve",a.nomeBreve)+campo("ag_sottotitolo","Sottotitolo",a.sottotitolo)+campo("ag_indirizzo","Indirizzo",a.indirizzo,"text",{cls:"w2"})+campo("ag_citta","Città (data documento)",a.citta)+
      campo("ag_tel","Telefono",a.tel)+campo("ag_fax","Fax",a.fax)+campo("ag_email","E-mail",a.email)+campo("ag_piva","P.IVA / VAT",a.piva)+campo("ag_firmatario","Firmatario",a.firmatario)+'</div>';
    h+='<h3>Impostazione dell\'intestazione sui documenti</h3><div class="grid" style="margin:8px 0 14px">'+
      '<div class="field"><label for="d_layout">Disposizione</label><select id="d_layout">'+opt("sinistra","nome a sinistra, recapiti a destra",d.layout)+opt("centro","tutto centrato",d.layout)+'</select></div>'+
      '<div class="field"><label for="d_lingua">Lingua documenti</label><select id="d_lingua">'+opt("en","inglese",d.lingua)+opt("it","italiano",d.lingua)+'</select></div>'+
      '<div class="field"><label for="d_colore">Colore</label><input id="d_colore" type="color" value="'+esc(d.colore||"#0e4e5c")+'" style="height:36px;padding:2px"></div>'+
      '<div class="field"><label for="d_logo">Logo</label><input id="d_logo" type="file" accept="image/*">'+(d.logo?'<span class="sub">logo caricato · <button class="btn lnk" id="d_logoDel">togli</button></span>':"")+'</div>'+
      campo("d_titoloPda","Titolo PDA",d.titoloPda,"text",{cls:"w2"})+campo("d_titoloFda","Titolo FDA",d.titoloFda,"text",{cls:"w2"})+campo("d_notaPda","Nota in calce al PDA",d.notaPda,"text",{cls:"w2"})+campo("d_notaFda","Nota in calce al FDA",d.notaFda,"text",{cls:"w2"})+campo("d_piede","Piè di pagina",d.piede,"text",{cls:"full",ph:"es. Cap. soc. …, REA …"})+
      '<div class="field full"><label>Elementi</label><div class="acts">'+[["mostraFax","fax"],["mostraEmail","e-mail"],["mostraPiva","P.IVA"],["mostraMessrs","riquadro Messrs"],["mostraBanca","coordinate bancarie"],["mostraFirma","firma"],["nascondiZero","nascondi voci a zero"]].map(function(x){ return '<label><input type="checkbox" id="d_'+x[0]+'" style="width:auto"'+(d[x[0]]?" checked":"")+'> '+x[1]+'</label>'; }).join("")+'</div></div></div>';
    h+='<div class="acts"><button class="btn primary" id="salvaAg">Salva</button><button class="btn" id="anteprimaAg">Anteprima carta intestata</button></div>'; }
  else if(S.imp==="banche"){ h+='<p class="sub">La banca da stampare si sceglie scalo per scalo nella pagina Intestazione; la prima è quella proposta.</p><div class="scroll"><table><thead><tr><th>Banca</th><th>IBAN</th><th>BIC</th><th></th></tr></thead><tbody>';
    C.banche.forEach(function(b,i){ h+='<tr><td><input data-bn="'+i+'" value="'+esc(b.nome)+'"></td><td><input data-bi="'+i+'" value="'+esc(b.iban)+'" class="num" style="text-align:left"></td><td><input data-bb="'+i+'" value="'+esc(b.bic)+'"></td><td><button class="btn small" data-bdel="'+i+'">togli</button></td></tr>'; });
    h+='</tbody></table></div><div class="acts" style="margin-top:10px"><button class="btn" id="bAdd">+ banca</button><button class="btn primary" id="salvaBanche">Salva</button></div>'; }
  else if(S.imp==="tariffe"){ h+='<p class="sub" style="max-width:70ch">Scaglioni di GT come nei fogli PILOTI, ORMEGGIATORI e TUG: da – a – tariffa per prestazione. Oltre l\'ultimo scaglione si aggiunge l\'"extra" per ogni blocco di GT indicato in "passo".</p>';
    [["pil","Piloti"],["orm","Ormeggiatori"],["tug","Rimorchiatori (per rimorchiatore)"]].forEach(function(t){ var T=C[t[0]]; h+='<h3 style="margin-top:14px">'+t[1]+'</h3><div class="bands" style="margin-top:6px"><span class="sub">da GT</span><span class="sub">a GT</span><span class="sub">€</span><span></span>';
      T.bands.forEach(function(b,i){ h+='<input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="0" value="'+b[0]+'"><input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="1" value="'+b[1]+'"><input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="2" value="'+b[2]+'"><button class="btn small" data-tdel="'+t[0]+':'+i+'">togli</button>'; });
      h+='</div><div class="acts" style="margin-top:6px"><button class="btn small" data-tadd="'+t[0]+'">+ scaglione</button><span class="sub">passo GT</span><input class="num" id="t_'+t[0]+'_step" value="'+T.step+'" style="width:90px"><span class="sub">extra €</span><input class="num" id="t_'+t[0]+'_extra" value="'+T.extra+'" style="width:100px"></div>'; });
    h+='<h3 style="margin-top:14px">Altre tariffe</h3><div class="grid" style="margin-top:6px">'+campo("t_transfer","Trasferimento rimorchiatori €",C.transfer,"number")+campo("t_anc_ue30","Ancoraggio UE ≤30 gg €/NT",C.anc.ue30,"number")+campo("t_anc_ex30","Ancoraggio extra UE ≤30 gg €/NT",C.anc.ex30,"number")+campo("t_anc_ue1y","Ancoraggio UE annuale €/NT",C.anc.ue1y,"number")+campo("t_anc_ex1y","Ancoraggio extra UE annuale €/NT",C.anc.ex1y,"number")+
      campo("t_chim_defum","Chimico – defumigazione €",C.chim.defum,"number")+campo("t_chim_soia","Chimico – soia €",C.chim.soia,"number")+campo("t_chim_ciabattato","Chimico – ciabattato €",C.chim.ciabattato,"number")+'</div>';
    h+='<div class="acts" style="margin-top:14px"><button class="btn primary" id="salvaTariffe">Salva tariffe</button><button class="btn" id="tariffeReset">Ripristina predefinite</button></div>';
    h+='<h3 style="margin-top:18px">Prova rapida</h3><div class="acts" style="margin-top:6px"><span class="sub">GT</span><input class="num" id="provaGt" value="7374" style="width:110px"><span id="provaOut" class="sub"></span></div>'; }
  else if(S.imp==="voci"){ h+='<p class="sub" style="max-width:70ch">Le voci del conto (PDA e FDA). "Fornitori" e "parole chiave" servono a riconoscere la voce quando si registra una fattura; "standard" è l\'importo proposto nel PDA; le voci "interne" senza fattura passano nel FDA con l\'importo del PDA; "automatico" indica la tariffa che la calcola.</p><div class="scroll"><table><thead><tr><th>Voce</th><th>Fornitori (virgola)</th><th>Parole chiave</th><th class="num">Standard €</th><th>Automatico</th><th>Interna</th><th></th></tr></thead><tbody>';
    C.voci.forEach(function(v,i){ h+='<tr><td><input data-vl="'+i+'" value="'+esc(v.label)+'"></td><td><input data-vf="'+i+'" value="'+esc(v.forn.join(", "))+'"></td><td><input data-vk="'+i+'" value="'+esc(v.kw.join(", "))+'"></td><td><input class="num" data-vs="'+i+'" value="'+(v.std!=null?v.std:"")+'" style="width:90px"></td><td><select data-va="'+i+'">'+opt("","—",v.auto||"")+opt("pil","piloti",v.auto)+opt("orm","ormeggiatori",v.auto)+opt("tug","rimorchiatori",v.auto)+opt("anc","ancoraggio",v.auto)+opt("chim","chimico",v.auto)+'</select></td><td style="text-align:center"><input type="checkbox" data-vi="'+i+'" style="width:auto"'+(v.int?" checked":"")+'></td><td><button class="btn small" data-vdel="'+i+'">togli</button></td></tr>'; });
    h+='</tbody></table></div><div class="acts" style="margin-top:10px"><button class="btn" id="vAdd">+ voce</button><button class="btn primary" id="salvaVoci">Salva voci</button><button class="btn" id="vociReset">Ripristina predefinite</button></div>'; }
  else if(S.imp==="liste"){ h+='<p class="sub">Un valore per riga.</p><div class="grid">'+[["agenti","Agenti"],["tipi","Tipi nave"],["bandiere","Bandiere"],["ormeggi","Ormeggi"],["operazioni","Operazioni"],["porti","Porti"]].map(function(l){ return '<div class="field"><label for="l_'+l[0]+'">'+l[1]+'</label><textarea id="l_'+l[0]+'" style="min-height:140px">'+esc(C.liste[l[0]].join("\n"))+'</textarea></div>'; }).join("")+'</div><div class="acts" style="margin-top:10px"><button class="btn primary" id="salvaListe">Salva liste</button></div>'; }
  else{ var ns=Object.keys(S.scali).length, nsp=Object.keys(S.spese).length;
    h+='<p>In archivio: <strong>'+ns+'</strong> scali e <strong>'+nsp+'</strong> fatture. '+(S.db?"I dati sono nell'archivio condiviso di claude.ai e in copia in questo browser.":"I dati sono salvati in questo browser: esporta un backup a fine giornata.")+'</p>';
    h+='<h3>Backup</h3><div class="acts" style="margin:6px 0 14px"><button class="btn" id="bkExport">Esporta backup completo (JSON)</button><button class="btn" id="bkCsv">Esporta scali e fatture (CSV)</button><label class="btn">Importa backup Portolano <input type="file" id="bkImport" accept=".json" hidden></label></div>';
    h+='<h3>Importa dagli altri programmi</h3><p class="sub" style="max-width:70ch">Da <strong>Pratiche di Scalo</strong>: il file PORTOLANO_DATI_*.json (Archivio → <em>Estrai dati</em>) oppure BACKUP_PRATICHE_*.json (Impostazioni → <em>Esporta archivio</em>) porta dentro navi, viaggi e PDA di ogni pratica; lo stesso file resta disponibile nella scheda di ogni scalo (Nave &amp; viaggio → <em>Scegli la pratica</em>) per compilare un singolo scalo. Dal <strong>Mastrino Approdi</strong>: il file mastrino_approdi.csv (tasto Esporta) porta approdi, fatture fornitori, intestazioni e bonifici. Gli scali già importati (stessa nave e stessa data) vengono aggiornati, non duplicati.</p>';
    h+='<div class="acts" style="margin:6px 0 14px"><label class="btn">Importa da Pratiche di Scalo <input type="file" id="impPs" accept=".json" hidden></label><label class="btn">Importa CSV del Mastrino <input type="file" id="impMa" accept=".csv,.txt" hidden></label></div>';
    if(window.PORTOLANO_SEED) h+='<h3>Archivio incorporato</h3><div class="acts" style="margin:6px 0 14px"><button class="btn" id="seedCarica">Carica gli scali incorporati nel file ('+Object.keys(window.PORTOLANO_SEED.scali||{}).length+' scali, '+Object.keys(window.PORTOLANO_SEED.spese||{}).length+' fatture)</button><span class="sub">aggiunge solo quelli che mancano</span></div>';
    h+='<h3>Contabilità</h3><div class="grid" style="margin:6px 0 8px">'+campo("c_giorni","Scadenza fatture (giorni dalla data fattura)",C.conta.giorniScadenza,"number")+campo("c_iva","IVA predefinita %",C.conta.ivaDefault,"number")+campo("c_chiuso","Periodo chiuso fino al",C.conta.chiusoFino,"date")+campo("c_backup","Backup automatico ogni (giorni, 0 = mai)",C.conta.backupAuto,"number")+campo("c_formato","Numerazione fatture FDA ({n} = progressivo, {anno}, {aa})",C.conta.formatoNum||"{n}/{anno}")+campo("c_azienda","Nome dell'azienda in Contabilità (per le voci NS FATTURA)",C.conta.nomeAzienda||"Fratelli Bonanno")+'</div><div class="acts" style="margin:0 0 14px"><button class="btn primary" id="salvaConta">Salva</button><span class="sub">Con il periodo chiuso, scali e fatture con data entro quella data non si modificano più (l\'amministratore può forzare). Il backup automatico scarica il file JSON all\'apertura dell\'app quando è passato l\'intervallo.</span></div>';
    h+='<div id="logBox"></div>';
    h+='<h3>Pulizia</h3><div class="acts" style="margin-top:6px"><button class="btn danger" id="azzeraTutto">Svuota archivio locale</button><span class="sub">cancella scali e fatture da questo browser (l\'archivio condiviso non viene toccato)</span></div>'; }
  return h+'</div></div>'; }
function leggiTariffe(){ var C=S.cfgRaw; ["pil","orm","tug"].forEach(function(t){ var rows={}; document.querySelectorAll('[data-t="'+t+'"]').forEach(function(i){ var bi=i.getAttribute("data-bi"), f=i.getAttribute("data-bf"); (rows[bi]=rows[bi]||[0,0,0])[f]=num(i.value)||0; });
    C[t]={step:num(val("t_"+t+"_step"))||S.cfg[t].step,extra:num(val("t_"+t+"_extra"))||0,bands:Object.keys(rows).sort(function(a,b){ return a-b; }).map(function(k){ return rows[k]; }).sort(function(a,b){ return a[0]-b[0]; })}; });
  C.transfer=num(val("t_transfer"))||0; C.anc={ue30:num(val("t_anc_ue30"))||0,ex30:num(val("t_anc_ex30"))||0,ue1y:num(val("t_anc_ue1y"))||0,ex1y:num(val("t_anc_ex1y"))||0}; C.chim={defum:num(val("t_chim_defum"))||0,soia:num(val("t_chim_soia"))||0,ciabattato:num(val("t_chim_ciabattato"))||0}; }
function leggiVoci(){ var out=[]; document.querySelectorAll("[data-vl]").forEach(function(i){ var idx=i.getAttribute("data-vl"), old=S.cfg.voci[idx]||{k:nuovoId("v")}, g=function(a){ var e=document.querySelector('['+a+'="'+idx+'"]'); return e?e:null; };
    var v={k:old.k,label:i.value.trim(),forn:g("data-vf").value.split(",").map(function(x){ return upper(x); }).filter(Boolean),kw:g("data-vk").value.split(",").map(function(x){ return upper(x); }).filter(Boolean)}; var s=num(g("data-vs").value); if(s!==null) v.std=s; var a=g("data-va").value; if(a) v.auto=a; if(g("data-vi").checked) v.int=true; if(old.opz) v.opz=true; if(v.label) out.push(v); }); S.cfgRaw.voci=out; }

/* ---------- documento PDA / FDA ---------- */
function testi(){ var en=S.cfg.doc.lingua!=="it"; return en?{messrs:"Messrs",ship:"Ship's name",master:"Master",flag:"Flag",type:"Type",imo:"IMO",gt:"GT / NT",eta:"ETA / ETD",berth:"Berth",op:"Operation",cargo:"Cargo",desc:"DESCRIPTION",amt:"EUR",sub:"TOTAL DISBURSEMENTS",stamp:"Stamp duty",tot:"TOTAL EUR",bank:"Bank details",agent:"Agent",vat:"VAT",prot:"Ref.",date:dEn,sign:"For "+S.cfg.ag.nomeBreve,pdaVs:"Proforma sent",inv:"Invoice no."}:
  {messrs:"Spett.le",ship:"Nave",master:"Comandante",flag:"Bandiera",type:"Tipo",imo:"IMO",gt:"GT / NT",eta:"ETA / ETD",berth:"Ormeggio",op:"Operazione",cargo:"Carico",desc:"DESCRIZIONE",amt:"EUR",sub:"TOTALE ESBORSI",stamp:"Bolli",tot:"TOTALE EUR",bank:"Coordinate bancarie",agent:"Agente",vat:"P.IVA",prot:"Prot.",date:dIt,sign:"Per "+S.cfg.ag.nomeBreve,pdaVs:"Preventivo inviato",inv:"Fattura n."}; }
function lettera(){ var a=S.cfg.ag, d=S.cfg.doc, rec=[a.indirizzo,[a.tel?"Tel. "+a.tel:"",d.mostraFax&&a.fax?"Fax "+a.fax:""].filter(Boolean).join(" · "),d.mostraEmail?a.email:"",d.mostraPiva&&a.piva?testi().vat+" "+a.piva:""].filter(Boolean);
  return '<div class="lh'+(d.layout==="centro"?" center":"")+'">'+(d.logo?'<img src="'+d.logo+'" alt="">':"")+'<div><div class="n">'+esc(a.nome)+'</div><div class="t">'+esc(a.sottotitolo)+'</div></div><div class="c">'+rec.map(esc).join("<br>")+'</div></div>'; }
function documento(sc,mode){ var T=testi(), C=S.cfg, d=C.doc, en=d.lingua!=="it", r=righeConto(sc,mode), t=totali(sc,mode), b=C.banche.filter(function(x){ return x.id===sc.banca; })[0]||C.banche[0], f=en?eurEn:eur;
  var h='<div class="doc" style="--docc:'+esc(d.colore||"#0e4e5c")+'">'+lettera();
  h+='<div style="display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;align-items:flex-start"><div>'+(d.mostraMessrs?'<div class="sub" style="font-size:11px;color:#555">'+T.messrs+'</div><div class="messrs">'+esc(sc.intestazione||sc.cliente||"")+(sc.attn?"\n"+esc(sc.attn):"")+'</div>':"")+'</div><div style="text-align:right;font-size:12px">'+esc(C.ag.citta||"")+', '+T.date(mode==="fda"&&fdaRif(sc).data?fdaRif(sc).data:oggi())+'<br>'+T.prot+' '+esc(sc.prot)+'/'+esc(sc.annoProt||anno(sc.eta))+(mode==="fda"&&fdaRif(sc).numero?'<br><b>'+T.inv+' '+esc(fdaRif(sc).numero)+'</b>':"")+(mode==="fda"&&sc.pda.inviato?'<br><span style="color:#555">'+T.pdaVs+' '+T.date(sc.pda.inviato)+'</span>':"")+'</div></div>';
  h+='<div class="titolo">'+esc(mode==="pda"?d.titoloPda:d.titoloFda)+'</div>';
  h+='<div class="kv"><div><b>'+T.ship+'</b> M/V '+esc(sc.nave)+(sc.master?' – '+T.master+' '+esc(sc.master):"")+'</div><div><b>'+T.imo+'</b> '+esc(sc.imo||"—")+(sc.callSign?' · '+esc(sc.callSign):"")+'</div><div><b>'+T.flag+'</b> '+esc(sc.flag||"—")+(sc.tipo?' · '+esc(sc.tipo):"")+'</div><div><b>'+T.gt+'</b> '+(sc.gt?Number(sc.gt).toLocaleString(en?"en-GB":"it-IT"):"—")+' / '+(sc.nt?Number(sc.nt).toLocaleString(en?"en-GB":"it-IT"):"—")+'</div><div><b>'+T.eta+'</b> '+T.date(sc.eta)+(sc.etd?' / '+T.date(sc.etd):"")+'</div><div><b>'+T.berth+'</b> '+esc(sc.ormeggio||"—")+'</div><div><b>'+T.op+'</b> '+esc(sc.operazione||"—")+'</div><div><b>'+T.cargo+'</b> '+esc([sc.carico,sc.quantita?sc.quantita+" MT":""].filter(Boolean).join(" ")||"—")+'</div></div>';
  h+='<table><thead><tr><th>'+T.desc+'</th><th class="n">'+T.amt+'</th></tr></thead><tbody>';
  r.forEach(function(x){ var v=mode==="pda"?x.pda.val:x.fda.val; if(!v&&(d.nascondiZero||x.extra)) return; h+='<tr><td>'+esc(x.label)+'</td><td class="n">'+f(v)+'</td></tr>'; });
  h+='<tr class="tot"><td>'+T.sub+'</td><td class="n">'+f(t.sub)+'</td></tr>'+(t.stamp?'<tr><td>'+T.stamp+'</td><td class="n">'+f(t.stamp)+'</td></tr>':"")+'<tr class="tot"><td>'+T.tot+'</td><td class="n">'+f(t.tot)+'</td></tr></tbody></table>';
  if(mode==="fda"&&incassato(sc)){ var res=r2(t.tot-incassato(sc)); h+='<table><tbody><tr><td>'+(en?"Received on account":"Ricevuto in acconto")+'</td><td class="n">'+f(incassato(sc))+'</td></tr><tr class="tot"><td>'+(res>=0?(en?"BALANCE DUE":"SALDO A VS DEBITO"):(en?"BALANCE IN YOUR FAVOUR":"SALDO A VS CREDITO"))+'</td><td class="n">'+f(Math.abs(res))+'</td></tr></tbody></table>'; }
  var nota=mode==="pda"?d.notaPda:d.notaFda; if(nota) h+='<div class="nota">'+esc(nota)+'</div>';
  if(d.mostraBanca&&b) h+='<div class="bank"><b>'+T.bank+'</b><br>'+esc(b.nome)+'<br>IBAN '+esc(b.iban)+(b.bic?' · BIC/SWIFT '+esc(b.bic):"")+'<br>'+(en?"Beneficiary: ":"Beneficiario: ")+esc(C.ag.nome)+'</div>';
  if(d.mostraFirma) h+='<div class="firma"><div>'+T.agent+': '+esc(sc.agente||C.ag.firmatario)+'</div><div class="l">'+esc(T.sign)+'<br><b>'+esc(C.ag.firmatario)+'</b></div></div>';
  if(d.piede) h+='<div class="piede">'+esc(d.piede)+'</div>';
  return h+'</div>'; }
function apriDoc(o){ var sc=S.scali[o.id]; var w=document.getElementById("docwrap"); if(!sc){ S.doc=null; if(w) w.remove(); return; }
  var h='<div class="docbar"><span class="sub" style="color:#fff;align-self:center;margin-right:auto">'+(o.mode==="pda"?"PDA":"FDA")+' – '+esc(sc.nave)+' · si salva in PDF dalla finestra di stampa</span><button class="btn" id="docStampa">Stampa / salva PDF</button>'+(S.downloads?'<button class="btn" id="docHtml">Scarica HTML</button>':"")+'<button class="btn" id="docChiudi">Chiudi</button></div>'+documento(sc,o.mode);
  if(!w){ w=document.createElement("div"); w.className="docwrap"; w.id="docwrap"; document.body.appendChild(w); } w.innerHTML=h;
  on("docStampa","click",function(){ window.print(); }); on("docChiudi","click",function(){ S.doc=null; w.remove(); });
  on("docHtml","click",async function(){ var css=document.querySelector("style").textContent; var html='<!doctype html><html><head><meta charset="utf-8"><title>'+esc(o.mode.toUpperCase()+" "+sc.nave)+'</title><style>'+css+' body{background:#fff} .docwrap{position:static;background:none;padding:0}</style></head><body><div class="docwrap">'+documento(sc,o.mode)+'</div></body></html>';
    try{ await S.downloads.save({filename:o.mode.toUpperCase()+"_"+(sc.nave||"nave").replace(/[^A-Za-z0-9]+/g,"_")+"_"+sc.prot+".html",data:html}); }catch(e){ avviso("Download non riuscito."); } }); }
function anteprimaAg(){ var w=document.getElementById("docwrap"); if(!w){ w=document.createElement("div"); w.className="docwrap"; w.id="docwrap"; document.body.appendChild(w); }
  w.innerHTML='<div class="docbar"><button class="btn" id="docChiudi">Chiudi</button></div><div class="doc" style="--docc:'+esc(S.cfg.doc.colore)+';min-height:300px">'+lettera()+'<div class="titolo">'+esc(S.cfg.doc.titoloPda)+'</div><p class="nota">Anteprima della carta intestata con le impostazioni salvate.</p></div>'; on("docChiudi","click",function(){ w.remove(); }); }

/* ---------- importazioni ed esportazioni ---------- */
function leggiFile(input,fn){ var f=input.files&&input.files[0]; if(!f) return; var r=new FileReader(); r.onload=function(){ fn(String(r.result),f.name); input.value=""; }; r.readAsText(f); }
function legaPS(sc){ document.querySelectorAll("[data-pscarica]").forEach(function(b){ b.addEventListener("click",async function(){ var D=psDati(); if(!D) return; var p=D.dati.pratiche[parseInt(b.getAttribute("data-pscarica"),10)]; if(!p) return;
    var o=leggiNave(sc), n=applicaPS(o,p,{pda:!S.psNoPda,soloVuoti:!!S.psVuoti}); o.pda=o.pda||sc.pda; await scriviScalo(o); S.psPick=false; render(); avviso("Caricati i dati della pratica "+p.nave+(p.eta?" del "+dIt(isoData(p.eta)):"")+(n?" ("+n+" campi)":"")+(!S.psNoPda&&p.pda?" con il PDA":"")+"."); }); }); }
function trovaScalo(nave,data){ nave=upper(nave); for(var k in S.scali){ var s=S.scali[k]; if(upper(s.nave)===nave&&(s.eta||"")===(data||"")) return s; } return null; }
function isoData(t){ t=String(t||"").trim(); if(!t) return ""; if(/^\d{4}-\d{2}-\d{2}/.test(t)) return t.slice(0,10); var m=t.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/); if(m){ var y=m[3].length===2?"20"+m[3]:m[3]; return y+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[1]).slice(-2); } var d=new Date(t); return isNaN(d)?"":d.toISOString().slice(0,10); }
/* ---------- dati da Pratiche di Scalo ----------
   Due file possibili: BACKUP_PRATICHE_*.json (Impostazioni → Esporta archivio: ogni pratica è {id,nave,eta,imo,updated,data:{…tutti i campi…}})
   e PORTOLANO_DATI_*.json (Archivio → Estrai dati: {navi:[anagrafica],scali:[viaggio],pda:[conto],tariffe,liste,agenzia}).
   normalizzaPS li porta a una lista unica di pratiche "piatte"; applicaPS copia una pratica in uno scalo. */
var LS_PS="portolano.psdati";
function normalizzaPS(j){ if(!j||typeof j!=="object") return null; var out={tipo:"",pratiche:[],cfg:null,navi:{}}, i;
  var tieni=function(v){ return v!==null&&v!==undefined&&v!==""; };
  var puliExtra=function(L){ return (L||[]).filter(function(e){ return e&&(e.desc||e.d||tieni(e.amount)||tieni(e.v)||tieni(e.val)); }).map(function(e){ return {d:e.desc||e.d||"",v:String(tieni(e.amount)?e.amount:(tieni(e.v)?e.v:(e.val||"")))}; }); };
  if(j.tipo==="pratiche-scalo-nave"||(j.pratica&&typeof j.pratica==="object"&&!Array.isArray(j.pratiche))){ out.tipo="nave"; var d1=j.pratica||{}, r1=Object.assign({},d1); r1.id=j.id||d1.id||""; r1.aggiornato=j.esportato||d1.updated||""; r1.nave=d1.nave||""; r1.imo=d1.imo||""; r1.eta=d1.eta||"";
    var q1=j.pda||{}, qi=(d1.pda&&typeof d1.pda==="object")?d1.pda:{}, pick=function(k){ return tieni(q1[k])?q1[k]:qi[k]; };
    r1.pda={nPil:pick("nPil"),nOrm:pick("nOrm"),nTug:pick("nTug"),tugs:pick("tugs"),transfer:!!(q1.transfer!==undefined?q1.transfer:qi.transfer),stamp:pick("stamp"),banca:pick("banca"),cliente:pick("cliente")||"",clienteInd:pick("clienteInd")||"",clienteAtt:pick("clienteAtt")||"",clienteEmail:pick("clienteEmail")||"",totale:q1.totale,inviato:q1.inviato||qi.inviato||"",items:{},extra:[]};
    if(Array.isArray(q1.righe)){ r1.pda.righe=true; q1.righe.forEach(function(l){ if(!l) return; if(l.k==="x"){ if(l.desc||tieni(l.amount)) r1.pda.extra.push({d:l.desc||"",v:String(l.amount==null?"":l.amount)}); } else if(l.k&&tieni(l.amount)) r1.pda.items[l.k]=String(l.amount); }); }
    else { r1.pda.items=Object.assign({},qi.items||{}); r1.pda.extra=puliExtra(qi.extra); }
    if(r1.nave&&!d1.esempio){ out.pratiche.push(r1); out.navi[String(r1.imo||"").trim()||upper(r1.nave)]=r1; }
  } else if(j.tipo==="portolano-import"||(Array.isArray(j.scali)&&Array.isArray(j.navi))){ out.tipo="dati";
    (j.navi||[]).forEach(function(n){ if(!n) return; var k=String(n.imo||"").trim()||upper(n.nave||""); if(k) out.navi[k]=n; });
    var pdaPer={}; (j.pda||[]).forEach(function(q){ if(q&&q.scaloId) pdaPer[q.scaloId]=q; });
    (j.scali||[]).forEach(function(c){ if(!c||!c.nave) return; var n=out.navi[String(c.imo||"").trim()]||out.navi[upper(c.nave)]||{}, r={id:c.id||"",aggiornato:c.aggiornato||""};
      ["nave","imo","callSign","flag","tipo","gt","nt","dwt","loa","classe","yob","portoIscr","armatore"].forEach(function(k){ r[k]=tieni(c[k])?c[k]:(tieni(n[k])?n[k]:""); });
      ["agente","master","pescaggio","eta","etaOra","etd","durata","provenienza","prossimo","ormeggio","operazione","carico","quantita","consignee","shipper","notify","bl","portoImbarco","portoSbarco"].forEach(function(k){ r[k]=tieni(c[k])?c[k]:""; });
      var q=pdaPer[c.id]; if(q){ r.pda={nPil:q.piloti,nOrm:q.ormeggiatori,nTug:q.rimorchiatoriPrest,tugs:q.rimorchiatori,transfer:!!q.transfer,stamp:q.bolli,banca:q.banca,cliente:q.cliente,clienteInd:q.clienteInd,clienteAtt:q.clienteAtt,clienteEmail:q.clienteEmail,totale:q.totale,inviato:q.inviato||"",righe:true,items:{},extra:[]};
        (q.voci||[]).forEach(function(v){ if(!v) return; if(v.codice==="x"){ if(v.descrizione||v.importo) r.pda.extra.push({d:v.descrizione||"",v:String(v.importo==null?"":v.importo)}); } else if(v.codice&&tieni(v.importo)) r.pda.items[v.codice]=String(v.importo); }); }
      out.pratiche.push(r); });
    if(j.agenzia||j.tariffe||j.liste){ var t=j.tariffe||{}; out.cfg={ag:j.agenzia,pil:t.piloti,orm:t.ormeggiatori,tug:t.rimorchiatori,transfer:t.transfer,anc:t.ancoraggio,chim:t.chimico,banche:t.banche,liste:j.liste}; }
  } else { out.tipo="backup"; var lst=Array.isArray(j.pratiche)?j.pratiche:(j.pratiche&&typeof j.pratiche==="object")?Object.keys(j.pratiche).map(function(k){ var x=j.pratiche[k]; if(x&&typeof x==="object"&&!x.id) x.id=k; return x; }):(Array.isArray(j)?j:[]);
    lst.forEach(function(a){ if(!a||typeof a!=="object") return; var d=(a.data&&typeof a.data==="object"&&(a.data.nave!==undefined||a.data.pda))?a.data:a, r=Object.assign({},d); r.id=a.id||d.id||""; r.aggiornato=a.updated||d.updated||""; r.nave=d.nave||a.nave||""; r.imo=d.imo||a.imo||""; r.eta=d.eta||a.eta||""; if(!r.nave||d.esempio) return;
      if(d.pda&&typeof d.pda==="object"){ var q=d.pda; r.pda={nPil:q.nPil,nOrm:q.nOrm,nTug:q.nTug,tugs:q.tugs,transfer:!!q.transfer,stamp:q.stamp,banca:q.banca,cliente:q.cliente,clienteInd:q.clienteInd,clienteAtt:q.clienteAtt,clienteEmail:q.clienteEmail,items:Object.assign({},q.items||{}),extra:(q.extra||[]).filter(function(e){ return e&&(e.desc||e.d||tieni(e.amount)||tieni(e.v)||tieni(e.val)); }).map(function(e){ return {d:e.desc||e.d||"",v:String(tieni(e.amount)?e.amount:(tieni(e.v)?e.v:(e.val||"")))}; })}; } else delete r.pda;
      var k=String(r.imo||"").trim()||upper(r.nave); if(k&&!out.navi[k]) out.navi[k]=r;
      out.pratiche.push(r); });
    if(j.cfg) out.cfg=j.cfg; }
  out.pratiche.sort(function(a,b){ return (isoData(b.eta)||"").localeCompare(isoData(a.eta)||"")||(a.nave||"").localeCompare(b.nave||""); });
  for(i=0;i<out.pratiche.length;i++) out.pratiche[i].idx=i; return out; }
function psDati(){ if(S.psDati===undefined){ S.psDati=null; try{ var j=JSON.parse(localStorage.getItem(LS_PS)||"null"); if(j&&j.dati&&j.dati.pratiche) S.psDati=j; }catch(e){} } return S.psDati; }
function ricordaPS(nome,dati){ S.psDati={file:nome||"",quando:new Date().toISOString(),dati:dati}; try{ localStorage.setItem(LS_PS,JSON.stringify(S.psDati)); }catch(e){} }
function naveDaPS(nome){ var d=psDati(); if(!d||!nome) return null; var N=d.dati.navi||{}, k=upper(nome); if(N[k]) return N[k]; for(var x in N){ if(upper(N[x].nave||"")===k) return N[x]; } return null; }
function naviPS(){ var d=psDati(), out=[]; if(!d) return out; var seen={}; d.dati.pratiche.forEach(function(p){ var n=upper(p.nave||""); if(n&&!seen[n]){ seen[n]=1; out.push(n); } }); return out; }
/* copia una pratica nello scalo: opz.soloVuoti = non toccare i campi già compilati; opz.pda=false = solo nave e viaggio */
function applicaPS(sc,p,opz){ opz=opz||{}; var n0=function(v){ var n=num(v); return n===null?null:n; }, tieni=function(v){ return v!==null&&v!==undefined&&v!==""; };
  var map={nave:upper(p.nave||""),imo:p.imo,callSign:p.callSign,flag:upper(p.flag||""),tipo:upper(p.tipo||""),gt:n0(p.gt),nt:n0(p.nt),dwt:n0(p.dwt),loa:n0(p.loa),pescaggio:n0(p.pescaggio),yob:p.yob,master:p.master,eta:isoData(p.eta),etaOra:p.etaOra,etd:isoData(p.etd),provenienza:p.provenienza,prossimo:p.prossimo,ormeggio:p.ormeggio,operazione:p.operazione,carico:p.carico,quantita:p.quantita,ricevitore:p.consignee,agente:p.agente};
  var n=0; for(var k in map){ var v=map[k]; if(!tieni(v)) continue; if(opz.soloVuoti&&tieni(sc[k])) continue; if(typeof v==="string") v=v.trim(); if(sc[k]!==v){ sc[k]=v; n++; } }
  if(sc.eta) sc.annoProt=parseInt(anno(sc.eta),10)||sc.annoProt;
  if(p.pda&&opz.pda!==false){ var q=p.pda; sc.pda=sc.pda||nuovoScalo().pda; ["nPil","nOrm","nTug","tugs"].forEach(function(k){ if(tieni(q[k])) sc.pda[k]=String(q[k]); }); sc.pda.transfer=!!q.transfer; if(tieni(q.stamp)) sc.pda.stamp=String(q.stamp);
    if(q.banca&&S.cfg.banche.some(function(b){ return b.id===q.banca; })) sc.banca=q.banca;
    var it=q.items||{}; if(q.righe){ sc.pda.items={}; S.cfg.voci.forEach(function(dv){ var c=dv.k, v=num(it[c]); if(v===null) v=0; var base=dv.auto?r2(calcAuto(dv.auto,sc)):(dv.std!=null?r2(dv.std):0); if(Math.abs(v-base)>0.005) sc.pda.items[c]=String(r2(v)); }); }
    else for(var c in it){ var dv=voce(c); if(!dv||!tieni(it[c])) continue; if(dv.std!=null&&num(it[c])===dv.std&&!(sc.pda.items&&tieni(sc.pda.items[c]))) continue; sc.pda.items[c]=String(it[c]); }
    if(tieni(q.inviato)){ sc.pda.inviato=isoData(q.inviato)||sc.pda.inviato; sc.pda.fontePS=isoData(q.inviato)||oggi(); } else if(q.righe) sc.pda.fontePS=oggi();
    if(q.righe||(q.extra&&q.extra.length&&!(opz.soloVuoti&&sc.pda.extra&&sc.pda.extra.length))) sc.pda.extra=(q.extra||[]).map(function(e){ return {d:e.d||"",v:String(e.v||"")}; });
    if(q.cliente&&(!opz.soloVuoti||!sc.cliente)) sc.cliente=q.cliente; var righe=[q.cliente,q.clienteInd].filter(Boolean).join("\n"); if(righe&&!sc.intestazione) sc.intestazione=righe; if(q.clienteAtt&&!sc.attn) sc.attn=q.clienteAtt; }
  return n; }
function descrPS(p){ var q=p.pda||{}; return [p.eta?dIt(isoData(p.eta))+(p.etd?" → "+dIt(isoData(p.etd)):""):"", p.agente, [p.ormeggio,p.operazione].filter(Boolean).join(" · "), q.cliente?"PDA "+q.cliente+(q.totale?" € "+eur(q.totale):""):(q.items&&Object.keys(q.items).length?"PDA":""), p.provenienza?"da "+p.provenienza:""].filter(Boolean).join(" · "); }
async function importaPS(txt,nomeFile){ var j; try{ j=JSON.parse(txt); }catch(e){ avviso("File non valido."); return; } var D=normalizzaPS(j); if(!D||!D.pratiche.length){ avviso("Nel file non ci sono pratiche (serve PORTOLANO_NAVE_*.json, PORTOLANO_DATI_*.json o BACKUP_PRATICHE_*.json di Pratiche di Scalo)."); return; } ricordaPS(nomeFile,D);
  var c=D.cfg; if(c&&c.ag){ var agN={}, agS={nome:c.ag.nome,nomeBreve:c.ag.nomeBreve,indirizzo:c.ag.indirizzo,tel:c.ag.tel,fax:c.ag.fax,email:c.ag.email,piva:c.ag.piva,firmatario:c.ag.firmatarioNome||c.ag.firmatario}; for(var ak in agS) if(agS[ak]!==undefined&&agS[ak]!==null&&agS[ak]!=="") agN[ak]=agS[ak]; S.cfgRaw.ag=merge(S.cfg.ag,agN); ["pil","orm","tug","transfer","anc","chim"].forEach(function(k){ if(c[k]) S.cfgRaw[k]=clone(c[k]); }); if(c.banche) S.cfgRaw.banche=clone(c.banche); await scriviCfg(); }
  var n=0,agg=0; for(var i=0;i<D.pratiche.length;i++){ var p=D.pratiche[i], eta=isoData(p.eta), sc=trovaScalo(p.nave,eta); if(sc) agg++; else{ sc=nuovoScalo(); if(p.prot||p.n) sc.prot=String(p.prot||p.n); n++; }
    applicaPS(sc,p,{pda:true}); await scriviScalo(sc); }
  avviso("Pratiche di Scalo ("+(D.tipo==="dati"?"Estrai dati":"backup")+"): "+n+" scali nuovi, "+agg+" aggiornati su "+D.pratiche.length+" pratiche."); render(); }
