function impostazioni(){ var tabs=[["agenzia","Intestazione"],["banche","Banche"],["tariffe","Tariffe"],["voci","Voci del conto"],["liste","Liste"],["archivio","Archivio"]], C=S.cfg;
  var h='<div class="top"><h1>Impostazioni</h1></div><div class="panel"><div class="subtabs" role="tablist">'+tabs.map(function(t){ return '<button role="tab" data-imp="'+t[0]+'" aria-selected="'+(S.imp===t[0])+'">'+t[1]+'</button>'; }).join("")+'</div><div class="panel-b">';
  if(S.imp==="agenzia"){ var a=C.ag, d=C.doc;
    h+='<h3>Carta intestata dell\'agenzia</h3><div class="grid" style="margin:8px 0 14px">'+campo("ag_nome","Ragione sociale",a.nome,"text",{cls:"w2"})+campo("ag_nomeBreve","Nome breve",a.nomeBreve)+campo("ag_sottotitolo","Sottotitolo",a.sottotitolo)+campo("ag_indirizzo","Indirizzo",a.indirizzo,"text",{cls:"w2"})+campo("ag_citta","Città (data documento)",a.citta)+
      campo("ag_tel","Telefono",a.tel)+campo("ag_fax","Fax",a.fax)+campo("ag_email","E-mail",a.email)+campo("ag_piva","P.IVA / VAT",a.piva)+campo("ag_firmatario","Firmatario",a.firmatario)+'</div>';
    h+='<h3>Impostazione dell\'intestazione sui documenti</h3><div class="grid" style="margin:8px 0 14px">'+
      '<div class="field"><label for="d_layout">Disposizione</label><select id="d_layout">'+opt("sinistra","nome a sinistra, recapiti a destra",d.layout)+opt("centro","tutto centrato",d.layout)+'</select></div>'+
      '<div class="field"><label for="d_lingua">Lingua documenti</label><select id="d_lingua">'+opt("en","inglese",d.lingua)+opt("it","italiano",d.lingua)+'</select></div>'+
      '<div class="field"><label for="d_colore">Colore</label><input id="d_colore" type="color" value="'+esc(d.colore||"#0e4e5c")+'" style="height:36px;padding:2px"></div>'+
      '<div class="field"><label for="d_logo">Logo</label><input id="d_logo" type="file" accept="image/*">'+(d.logo?'<span class="sub">logo caricato · <button class="btn lnk" id="d_logoDel">togli</button></span>':"")+'</div>'+
      campo("d_titoloPda","Titolo PDA",d.titoloPda,"text",{cls:"w2"})+campo("d_titoloFda","Titolo FDA",d.titoloFda,"text",{cls:"w2"})+campo("d_notaPda","Nota in calce al PDA",d.notaPda,"text",{cls:"w2"})+campo("d_notaFda","Nota in calce al FDA",d.notaFda,"text",{cls:"w2"})+campo("d_piede","Piè di pagina",d.piede,"text",{cls:"full",ph:"es. Cap. soc. …, REA …"})+
      '<div class="field full"><label>Elementi</label><div class="acts">'+[["mostraFax","fax"],["mostraEmail","e-mail"],["mostraPiva","P.IVA"],["mostraMessrs","riquadro Messrs"],["mostraBanca","coordinate bancarie"],["mostraFirma","firma"],["nascondiZero","nascondi voci a zero"]].map(function(x){ return '<label><input type="checkbox" id="d_'+x[0]+'" style="width:auto"'+(d[x[0]]?" checked":"")+'> '+x[1]+'</label>'; }).join("")+'</div></div></div>';
    h+='<div class="acts"><button class="btn primary" id="salvaAg">Salva</button><button class="btn" id="anteprimaAg">Anteprima carta intestata</button></div>'; }
  else if(S.imp==="banche"){ h+='<p class="sub">La banca da stampare si sceglie scalo per scalo nella pagina Intestazione; la prima è quella proposta.</p><div class="scroll"><table><thead><tr><th>Banca</th><th>IBAN</th><th>BIC</th><th></th></tr></thead><tbody>';
    C.banche.forEach(function(b,i){ h+='<tr><td><input data-bn="'+i+'" value="'+esc(b.nome)+'"></td><td><input data-bi="'+i+'" value="'+esc(b.iban)+'" class="num" style="text-align:left"></td><td><input data-bb="'+i+'" value="'+esc(b.bic)+'"></td><td><button class="btn small" data-bdel="'+i+'">togli</button></td></tr>'; });
    h+='</tbody></table></div><div class="acts" style="margin-top:10px"><button class="btn" id="bAdd">+ banca</button><button class="btn primary" id="salvaBanche">Salva</button></div>'; }
  else if(S.imp==="tariffe"){ h+='<p class="sub" style="max-width:70ch">Scaglioni di GT come nei fogli PILOTI, ORMEGGIATORI e TUG: da – a – tariffa per prestazione. Oltre l\'ultimo scaglione si aggiunge l\'"extra" per ogni blocco di GT indicato in "passo".</p>';
    [["pil","Piloti"],["orm","Ormeggiatori"],["tug","Rimorchiatori (per rimorchiatore)"]].forEach(function(t){ var T=C[t[0]]; h+='<h3 style="margin-top:14px">'+t[1]+'</h3><div class="bands" style="margin-top:6px"><span class="sub">da GT</span><span class="sub">a GT</span><span class="sub">€</span><span></span>';
      T.bands.forEach(function(b,i){ h+='<input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="0" value="'+b[0]+'"><input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="1" value="'+b[1]+'"><input class="num" data-t="'+t[0]+'" data-bi="'+i+'" data-bf="2" value="'+b[2]+'"><button class="btn small" data-tdel="'+t[0]+':'+i+'">togli</button>'; });
      h+='</div><div class="acts" style="margin-top:6px"><button class="btn small" data-tadd="'+t[0]+'">+ scaglione</button><span class="sub">passo GT</span><input class="num" id="t_'+t[0]+'_step" value="'+T.step+'" style="width:90px"><span class="sub">extra €</span><input class="num" id="t_'+t[0]+'_extra" value="'+T.extra+'" style="width:100px"></div>'; });
    h+='<h3 style="margin-top:14px">Altre tariffe</h3><div class="grid" style="margin-top:6px">'+campo("t_transfer","Trasferimento rimorchiatori €",C.transfer,"number")+campo("t_anc_ue30","Ancoraggio UE ≤30 gg €/NT",C.anc.ue30,"number")+campo("t_anc_ex30","Ancoraggio extra UE ≤30 gg €/NT",C.anc.ex30,"number")+campo("t_anc_ue1y","Ancoraggio UE annuale €/NT",C.anc.ue1y,"number")+campo("t_anc_ex1y","Ancoraggio extra UE annuale €/NT",C.anc.ex1y,"number")+
      campo("t_chim_defum","Chimico – defumigazione €",C.chim.defum,"number")+campo("t_chim_soia","Chimico – soia €",C.chim.soia,"number")+campo("t_chim_ciabattato","Chimico – ciabattato €",C.chim.ciabattato,"number")+'</div>';
    h+='<div class="acts" style="margin-top:14px"><button class="btn primary" id="salvaTariffe">Salva tariffe</button><button class="btn" id="tariffeReset">Ripristina predefinite</button></div>';
    h+='<h3 style="margin-top:18px">Prova rapida</h3><div class="acts" style="margin-top:6px"><span class="sub">GT</span><input class="num" id="provaGt" value="7374" style="width:110px"><span id="provaOut" class="sub"></span></div>'; }
  else if(S.imp==="voci"){ h+='<p class="sub" style="max-width:70ch">Le voci del conto (PDA e FDA). "Fornitori" e "parole chiave" servono a riconoscere la voce quando si registra una fattura; "standard" è l\'importo proposto nel PDA; le voci "interne" senza fattura passano nel FDA con l\'importo del PDA; "automatico" indica la tariffa che la calcola.</p><div class="scroll"><table><thead><tr><th>Voce</th><th>Fornitori (virgola)</th><th>Parole chiave</th><th class="num">Standard €</th><th>Automatico</th><th>Interna</th><th></th></tr></thead><tbody>';
    C.voci.forEach(function(v,i){ h+='<tr><td><input data-vl="'+i+'" value="'+esc(v.label)+'"></td><td><input data-vf="'+i+'" value="'+esc(v.forn.join(", "))+'"></td><td><input data-vk="'+i+'" value="'+esc(v.kw.join(", "))+'"></td><td><input class="num" data-vs="'+i+'" value="'+(v.std!=null?v.std:"")+'" style="width:90px"></td><td><select data-va="'+i+'">'+opt("","—",v.auto||"")+opt("pil","piloti",v.auto)+opt("orm","ormeggiatori",v.auto)+opt("tug","rimorchiatori",v.auto)+opt("anc","ancoraggio",v.auto)+opt("chim","chimico",v.auto)+'</select></td><td style="text-align:center"><input type="checkbox" data-vi="'+i+'" style="width:auto"'+(v.int?" checked":"")+'></td><td><button class="btn small" data-vdel="'+i+'">togli</button></td></tr>'; });
    h+='</tbody></table></div><div class="acts" style="margin-top:10px"><button class="btn" id="vAdd">+ voce</button><button class="btn primary" id="salvaVoci">Salva voci</button><button class="btn" id="vociReset">Ripristina predefinite</button></div>'; }
  else if(S.imp==="liste"){ h+='<p class="sub">Un valore per riga.</p><div class="grid">'+[["agenti","Agenti"],["tipi","Tipi nave"],["bandiere","Bandiere"],["ormeggi","Ormeggi"],["operazioni","Operazioni"],["porti","Porti"]].map(function(l){ return '<div class="field"><label for="l_'+l[0]+'">'+l[1]+'</label><textarea id="l_'+l[0]+'" style="min-height:140px">'+esc(C.liste[l[0]].join("\n"))+'</textarea></div>'; }).join("")+'</div><div class="acts" style="margin-top:10px"><button class="btn primary" id="salvaListe">Salva liste</button></div>'; }
  else{ var ns=Object.keys(S.scali).length, nsp=Object.keys(S.spese).length;
    h+='<p>In archivio: <strong>'+ns+'</strong> scali e <strong>'+nsp+'</strong> fatture. '+(S.db?"I dati sono nell'archivio condiviso di claude.ai e in copia in questo browser.":"I dati sono salvati in questo browser: esporta un backup a fine giornata.")+'</p>';
    h+='<h3>Backup</h3><div class="acts" style="margin:6px 0 14px"><button class="btn" id="bkExport">Esporta backup completo (JSON)</button><button class="btn" id="bkCsv">Esporta scali e fatture (CSV)</button><label class="btn">Importa backup Portolano <input type="file" id="bkImport" accept=".json" hidden></label></div>';
    h+='<h3>Importa dagli altri programmi</h3><p class="sub" style="max-width:70ch">Da <strong>Pratiche di Scalo</strong>: il file BACKUP_PRATICHE_*.json (Impostazioni → Esporta archivio) porta dentro navi, viaggi e parametri PDA di ogni pratica. Dal <strong>Mastrino Approdi</strong>: il file mastrino_approdi.csv (tasto Esporta) porta approdi, fatture fornitori, intestazioni e bonifici. Gli scali già importati (stessa nave e stessa data) vengono aggiornati, non duplicati.</p>';
    h+='<div class="acts" style="margin:6px 0 14px"><label class="btn">Importa da Pratiche di Scalo <input type="file" id="impPs" accept=".json" hidden></label><label class="btn">Importa CSV del Mastrino <input type="file" id="impMa" accept=".csv,.txt" hidden></label></div>';
    if(window.PORTOLANO_SEED) h+='<h3>Archivio incorporato</h3><div class="acts" style="margin:6px 0 14px"><button class="btn" id="seedCarica">Carica gli scali incorporati nel file ('+Object.keys(window.PORTOLANO_SEED.scali||{}).length+' scali, '+Object.keys(window.PORTOLANO_SEED.spese||{}).length+' fatture)</button><span class="sub">aggiunge solo quelli che mancano</span></div>';
    h+='<h3>Contabilità</h3><div class="grid" style="margin:6px 0 8px">'+campo("c_giorni","Scadenza fatture (giorni dalla data fattura)",C.conta.giorniScadenza,"number")+campo("c_iva","IVA predefinita %",C.conta.ivaDefault,"number")+campo("c_chiuso","Periodo chiuso fino al",C.conta.chiusoFino,"date")+campo("c_backup","Backup automatico ogni (giorni, 0 = mai)",C.conta.backupAuto,"number")+campo("c_formato","Numerazione fatture FDA ({n} = progressivo, {anno}, {aa})",C.conta.formatoNum||"{n}/{anno}")+campo("c_azienda","Nome dell'azienda in Contabilità (per le voci NS FATTURA)",C.conta.nomeAzienda||"Fratelli Bonanno")+'</div><div class="acts" style="margin:0 0 14px"><button class="btn primary" id="salvaConta">Salva</button><span class="sub">Con il periodo chiuso, scali e fatture con data entro quella data non si modificano più (l\'amministratore può forzare). Il backup automatico scarica il file JSON all\'apertura dell\'app quando è passato l\'intervallo.</span></div>';
    h+='<div id="logBox"></div>';
    h+='<h3>Pulizia</h3><div class="acts" style="margin-top:6px"><button class="btn danger" id="azzeraTutto">Svuota archivio locale</button><span class="sub">cancella scali e fatture da questo browser (l\'archivio condiviso non viene toccato)</span></div>'; }
  return h+'</div></div>'; }
function leggiTariffe(){ var C=S.cfgRaw; ["pil","orm","tug"].forEach(function(t){ var rows={}; document.querySelectorAll('[data-t="'+t+'"]').forEach(function(i){ var bi=i.getAttribute("data-bi"), f=i.getAttribute("data-bf"); (rows[bi]=rows[bi]||[0,0,0])[f]=num(i.value)||0; });
    C[t]={step:num(val("t_"+t+"_step"))||S.cfg[t].step,extra:num(val("t_"+t+"_extra"))||0,bands:Object.keys(rows).sort(function(a,b){ return a-b; }).map(function(k){ return rows[k]; }).sort(function(a,b){ return a[0]-b[0]; })}; });
  C.transfer=num(val("t_transfer"))||0; C.anc={ue30:num(val("t_anc_ue30"))||0,ex30:num(val("t_anc_ex30"))||0,ue1y:num(val("t_anc_ue1y"))||0,ex1y:num(val("t_anc_ex1y"))||0}; C.chim={defum:num(val("t_chim_defum"))||0,soia:num(val("t_chim_soia"))||0,ciabattato:num(val("t_chim_ciabattato"))||0}; }
function leggiVoci(){ var out=[]; document.querySelectorAll("[data-vl]").forEach(function(i){ var idx=i.getAttribute("data-vl"), old=S.cfg.voci[idx]||{k:nuovoId("v")}, g=function(a){ var e=document.querySelector('['+a+'="'+idx+'"]'); return e?e:null; };
    var v={k:old.k,label:i.value.trim(),forn:g("data-vf").value.split(",").map(function(x){ return upper(x); }).filter(Boolean),kw:g("data-vk").value.split(",").map(function(x){ return upper(x); }).filter(Boolean)}; var s=num(g("data-vs").value); if(s!==null) v.std=s; var a=g("data-va").value; if(a) v.auto=a; if(g("data-vi").checked) v.int=true; if(old.opz) v.opz=true; if(v.label) out.push(v); }); S.cfgRaw.voci=out; }

/* ---------- documento PDA / FDA ---------- */
function testi(){ var en=S.cfg.doc.lingua!=="it"; return en?{messrs:"Messrs",ship:"Ship's name",master:"Master",flag:"Flag",type:"Type",imo:"IMO",gt:"GT / NT",eta:"ETA / ETD",berth:"Berth",op:"Operation",cargo:"Cargo",desc:"DESCRIPTION",amt:"EUR",sub:"TOTAL DISBURSEMENTS",stamp:"Stamp duty",tot:"TOTAL EUR",bank:"Bank details",agent:"Agent",vat:"VAT",prot:"Ref.",date:dEn,sign:"For "+S.cfg.ag.nomeBreve,pdaVs:"Proforma sent",inv:"Invoice no."}:
  {messrs:"Spett.le",ship:"Nave",master:"Comandante",flag:"Bandiera",type:"Tipo",imo:"IMO",gt:"GT / NT",eta:"ETA / ETD",berth:"Ormeggio",op:"Operazione",cargo:"Carico",desc:"DESCRIZIONE",amt:"EUR",sub:"TOTALE ESBORSI",stamp:"Bolli",tot:"TOTALE EUR",bank:"Coordinate bancarie",agent:"Agente",vat:"P.IVA",prot:"Prot.",date:dIt,sign:"Per "+S.cfg.ag.nomeBreve,pdaVs:"Preventivo inviato",inv:"Fattura n."}; }
function lettera(){ var a=S.cfg.ag, d=S.cfg.doc, rec=[a.indirizzo,[a.tel?"Tel. "+a.tel:"",d.mostraFax&&a.fax?"Fax "+a.fax:""].filter(Boolean).join(" · "),d.mostraEmail?a.email:"",d.mostraPiva&&a.piva?testi().vat+" "+a.piva:""].filter(Boolean);
  return '<div class="lh'+(d.layout==="centro"?" center":"")+'">'+(d.logo?'<img src="'+d.logo+'" alt="">':"")+'<div><div class="n">'+esc(a.nome)+'</div><div class="t">'+esc(a.sottotitolo)+'</div></div><div class="c">'+rec.map(esc).join("<br>")+'</div></div>'; }
function documento(sc,mode){ var T=testi(), C=S.cfg, d=C.doc, en=d.lingua!=="it", r=righeConto(sc,mode), t=totali(sc,mode), b=C.banche.filter(function(x){ return x.id===sc.banca; })[0]||C.banche[0], f=en?eurEn:eur;
  var h='<div class="doc" style="--docc:'+esc(d.colore||"#0e4e5c")+'">'+lettera();
  h+='<div style="display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;align-items:flex-start"><div>'+(d.mostraMessrs?'<div class="sub" style="font-size:11px;color:#555">'+T.messrs+'</div><div class="messrs">'+esc(sc.intestazione||sc.cliente||"")+(sc.attn?"\n"+esc(sc.attn):"")+'</div>':"")+'</div><div style="text-align:right;font-size:12px">'+esc(C.ag.citta||"")+', '+T.date(mode==="fda"&&fdaRif(sc).data?fdaRif(sc).data:oggi())+'<br>'+T.prot+' '+esc(sc.prot)+'/'+esc(sc.annoProt||anno(sc.eta))+(mode==="fda"&&fdaRif(sc).numero?'<br><b>'+T.inv+' '+esc(fdaRif(sc).numero)+'</b>':"")+(mode==="fda"&&sc.pda.inviato?'<br><span style="color:#555">'+T.pdaVs+' '+T.date(sc.pda.inviato)+'</span>':"")+'</div></div>';
  h+='<div class="titolo">'+esc(mode==="pda"?d.titoloPda:d.titoloFda)+'</div>';
  h+='<div class="kv"><div><b>'+T.ship+'</b> M/V '+esc(sc.nave)+(sc.master?' – '+T.master+' '+esc(sc.master):"")+'</div><div><b>'+T.imo+'</b> '+esc(sc.imo||"—")+(sc.callSign?' · '+esc(sc.callSign):"")+'</div><div><b>'+T.flag+'</b> '+esc(sc.flag||"—")+(sc.tipo?' · '+esc(sc.tipo):"")+'</div><div><b>'+T.gt+'</b> '+(sc.gt?Number(sc.gt).toLocaleString(en?"en-GB":"it-IT"):"—")+' / '+(sc.nt?Number(sc.nt).toLocaleString(en?"en-GB":"it-IT"):"—")+'</div><div><b>'+T.eta+'</b> '+T.date(sc.eta)+(sc.etd?' / '+T.date(sc.etd):"")+'</div><div><b>'+T.berth+'</b> '+esc(sc.ormeggio||"—")+'</div><div><b>'+T.op+'</b> '+esc(sc.operazione||"—")+'</div><div><b>'+T.cargo+'</b> '+esc([sc.carico,sc.quantita?sc.quantita+" MT":""].filter(Boolean).join(" ")||"—")+'</div></div>';
  h+='<table><thead><tr><th>'+T.desc+'</th><th class="n">'+T.amt+'</th></tr></thead><tbody>';
  r.forEach(function(x){ var v=mode==="pda"?x.pda.val:x.fda.val; if(!v&&(d.nascondiZero||x.extra)) return; h+='<tr><td>'+esc(x.label)+'</td><td class="n">'+f(v)+'</td></tr>'; });
  h+='<tr class="tot"><td>'+T.sub+'</td><td class="n">'+f(t.sub)+'</td></tr>'+(t.stamp?'<tr><td>'+T.stamp+'</td><td class="n">'+f(t.stamp)+'</td></tr>':"")+'<tr class="tot"><td>'+T.tot+'</td><td class="n">'+f(t.tot)+'</td></tr></tbody></table>';
  if(mode==="fda"&&incassato(sc)){ var res=r2(t.tot-incassato(sc)); h+='<table><tbody><tr><td>'+(en?"Received on account":"Ricevuto in acconto")+'</td><td class="n">'+f(incassato(sc))+'</td></tr><tr class="tot"><td>'+(res>=0?(en?"BALANCE DUE":"SALDO A VS DEBITO"):(en?"BALANCE IN YOUR FAVOUR":"SALDO A VS CREDITO"))+'</td><td class="n">'+f(Math.abs(res))+'</td></tr></tbody></table>'; }
  var nota=mode==="pda"?d.notaPda:d.notaFda; if(nota) h+='<div class="nota">'+esc(nota)+'</div>';
  if(d.mostraBanca&&b) h+='<div class="bank"><b>'+T.bank+'</b><br>'+esc(b.nome)+'<br>IBAN '+esc(b.iban)+(b.bic?' · BIC/SWIFT '+esc(b.bic):"")+'<br>'+(en?"Beneficiary: ":"Beneficiario: ")+esc(C.ag.nome)+'</div>';
  if(d.mostraFirma) h+='<div class="firma"><div>'+T.agent+': '+esc(sc.agente||C.ag.firmatario)+'</div><div class="l">'+esc(T.sign)+'<br><b>'+esc(C.ag.firmatario)+'</b></div></div>';
  if(d.piede) h+='<div class="piede">'+esc(d.piede)+'</div>';
  return h+'</div>'; }
function apriDoc(o){ var sc=S.scali[o.id]; var w=document.getElementById("docwrap"); if(!sc){ S.doc=null; if(w) w.remove(); return; }
  var h='<div class="docbar"><span class="sub" style="color:#fff;align-self:center;margin-right:auto">'+(o.mode==="pda"?"PDA":"FDA")+' – '+esc(sc.nave)+' · si salva in PDF dalla finestra di stampa</span><button class="btn" id="docStampa">Stampa / salva PDF</button>'+(S.downloads?'<button class="btn" id="docHtml">Scarica HTML</button>':"")+'<button class="btn" id="docChiudi">Chiudi</button></div>'+documento(sc,o.mode);
  if(!w){ w=document.createElement("div"); w.className="docwrap"; w.id="docwrap"; document.body.appendChild(w); } w.innerHTML=h;
  on("docStampa","click",function(){ window.print(); }); on("docChiudi","click",function(){ S.doc=null; w.remove(); });
  on("docHtml","click",async function(){ var css=document.querySelector("style").textContent; var html='<!doctype html><html><head><meta charset="utf-8"><title>'+esc(o.mode.toUpperCase()+" "+sc.nave)+'</title><style>'+css+' body{background:#fff} .docwrap{position:static;background:none;padding:0}</style></head><body><div class="docwrap">'+documento(sc,o.mode)+'</div></body></html>';
    try{ await S.downloads.save({filename:o.mode.toUpperCase()+"_"+(sc.nave||"nave").replace(/[^A-Za-z0-9]+/g,"_")+"_"+sc.prot+".html",data:html}); }catch(e){ avviso("Download non riuscito."); } }); }
function anteprimaAg(){ var w=document.getElementById("docwrap"); if(!w){ w=document.createElement("div"); w.className="docwrap"; w.id="docwrap"; document.body.appendChild(w); }
  w.innerHTML='<div class="docbar"><button class="btn" id="docChiudi">Chiudi</button></div><div class="doc" style="--docc:'+esc(S.cfg.doc.colore)+';min-height:300px">'+lettera()+'<div class="titolo">'+esc(S.cfg.doc.titoloPda)+'</div><p class="nota">Anteprima della carta intestata con le impostazioni salvate.</p></div>'; on("docChiudi","click",function(){ w.remove(); }); }

/* ---------- importazioni ed esportazioni ---------- */
function leggiFile(input,fn){ var f=input.files&&input.files[0]; if(!f) return; var r=new FileReader(); r.onload=function(){ fn(String(r.result)); }; r.readAsText(f); }
function trovaScalo(nave,data){ nave=upper(nave); for(var k in S.scali){ var s=S.scali[k]; if(upper(s.nave)===nave&&(s.eta||"")===(data||"")) return s; } return null; }
function isoData(t){ t=String(t||"").trim(); if(!t) return ""; if(/^\d{4}-\d{2}-\d{2}/.test(t)) return t.slice(0,10); var m=t.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/); if(m){ var y=m[3].length===2?"20"+m[3]:m[3]; return y+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[1]).slice(-2); } var d=new Date(t); return isNaN(d)?"":d.toISOString().slice(0,10); }
async function importaPS(txt){ var j; try{ j=JSON.parse(txt); }catch(e){ avviso("File non valido."); return; } var lst=Array.isArray(j.pratiche)?j.pratiche:Object.keys(j.pratiche||{}).map(function(k){ return j.pratiche[k]; }); if(!lst.length&&Array.isArray(j)) lst=j;
  if(j.cfg&&j.cfg.ag){ S.cfgRaw.ag=merge(S.cfg.ag,{nome:j.cfg.ag.nome,nomeBreve:j.cfg.ag.nomeBreve,indirizzo:j.cfg.ag.indirizzo,tel:j.cfg.ag.tel,fax:j.cfg.ag.fax,email:j.cfg.ag.email,piva:j.cfg.ag.piva,firmatario:j.cfg.ag.firmatarioNome||j.cfg.ag.firmatario}); ["pil","orm","tug","transfer","anc","chim"].forEach(function(k){ if(j.cfg[k]) S.cfgRaw[k]=clone(j.cfg[k]); }); if(j.cfg.banche) S.cfgRaw.banche=clone(j.cfg.banche); await scriviCfg(); }
  var n=0,agg=0; for(var i=0;i<lst.length;i++){ var p=lst[i]; if(!p||!p.nave||p.esempio) continue; var eta=isoData(p.eta), sc=trovaScalo(p.nave,eta); if(sc) agg++; else{ sc=nuovoScalo(); sc.prot=String(p.prot||p.n||sc.prot); n++; }
    Object.assign(sc,{nave:upper(p.nave),imo:p.imo||sc.imo,callSign:p.callSign||sc.callSign,flag:upper(p.flag||sc.flag),tipo:upper(p.tipo||sc.tipo),gt:num(p.gt)||sc.gt,nt:num(p.nt)||sc.nt,dwt:num(p.dwt)||sc.dwt,loa:num(p.loa)||sc.loa,pescaggio:num(p.pescaggio)||sc.pescaggio,yob:p.yob||sc.yob,master:p.master||sc.master,eta:eta||sc.eta,etaOra:p.etaOra||sc.etaOra,etd:isoData(p.etd)||sc.etd,provenienza:p.provenienza||sc.provenienza,prossimo:p.prossimo||sc.prossimo,ormeggio:p.ormeggio||sc.ormeggio,operazione:p.operazione||sc.operazione,carico:p.carico||sc.carico,quantita:p.quantita||sc.quantita,ricevitore:p.consignee||sc.ricevitore,agente:p.agente||sc.agente});
    sc.annoProt=parseInt(anno(sc.eta),10)||sc.annoProt; if(p.pda){ var q=p.pda; sc.pda=Object.assign(sc.pda,{nPil:q.nPil||sc.pda.nPil,nOrm:q.nOrm||sc.pda.nOrm,nTug:q.nTug||sc.pda.nTug,tugs:q.tugs||sc.pda.tugs,transfer:!!q.transfer,stamp:q.stamp||"",banca:q.banca}); if(q.banca) sc.banca=q.banca;
      var it=q.items||{}, mapK={hm:"hm",customs:"customs",sanit:"sanit",disch:"disch",security:"security",informer:"informer",chemist:"chemist",phone:"phone",shore:"shore",transfer:"transfer",isps:"isps",garbage:"garbage",stamps:"stamps",sludge:"sludge",anchor:"anchor",agency:"agency",pil:"pil",orm:"orm",tug:"tug"};
      for(var k in it){ if(it[k]!==""&&it[k]!=null&&mapK[k]){ var dflt=voce(mapK[k]); if(!(dflt&&dflt.std!=null&&num(it[k])===dflt.std)) sc.pda.items[mapK[k]]=String(it[k]); } } (q.extra||[]).forEach(function(e){ if(e&&(e.d||e.v)) sc.pda.extra.push({d:e.d||e.desc||"",v:String(e.v||e.val||"")}); }); }
    await scriviScalo(sc); }
  avviso("Pratiche di Scalo: "+n+" scali nuovi, "+agg+" aggiornati."); render(); }
