function csvParse(t){ var rows=[],row=[],cell="",q=false; t=t.replace(/^\uFEFF/,""); for(var i=0;i<t.length;i++){ var c=t[i]; if(q){ if(c==='"'){ if(t[i+1]==='"'){ cell+='"'; i++; } else q=false; } else cell+=c; } else if(c==='"') q=true; else if(c===";"||c===","){ row.push(cell); cell=""; } else if(c==="\n"||c==="\r"){ if(c==="\r"&&t[i+1]==="\n") i++; row.push(cell); rows.push(row); row=[]; cell=""; } else cell+=c; } if(cell||row.length){ row.push(cell); rows.push(row); } return rows; }
async function importaMastrino(txt){ var rows=csvParse(txt); if(!rows.length){ avviso("CSV vuoto."); return; } var H=rows[0].map(upper), ix=function(n){ return H.indexOf(n); };
  var iP=ix("PROT"),iDA=ix("DATA APPRODO"),iDP=ix("DATA PARTENZA"),iN=ix("NAVE"),iT=ix("TIPO"),iG=ix("GT"),iNT=ix("NT"),iC=ix("CLIENTE"),iCa=ix("CARICO"),iR=ix("RICEVITORE"),iPda=ix("PDA APPRODO"),iB=ix("BONIFICO"),iDB=ix("DATA BONIFICO"),iBa=ix("BANCA"),iNo=ix("NOTE APPRODO"),iI=ix("INTESTAZIONE FATTURA"),
    iF=ix("FORNITORE"),iDe=ix("DESCRIZIONE"),iIP=ix("IMPORTO PDA"),iTo=ix("TOTALE"),iDF=ix("DATA FATTURA"),iNF=ix("N. FATTURA"),iDPa=ix("DATA PAGAMENTO"),iMo=ix("MODO PAG."),iNS=ix("NOTE SPESA");
  if(iP<0||iN<0){ avviso("Non sembra il CSV del Mastrino Approdi."); return; }
  var g=function(r,i){ return i>=0&&r[i]!=null?String(r[i]).trim():""; }, n=0,agg=0,ns=0, perProt={};
  for(var i=1;i<rows.length;i++){ var r=rows[i]; if(!g(r,iP)||!g(r,iN)) continue; var prot=g(r,iP), eta=isoData(g(r,iDA)), key=prot+"|"+anno(eta), sc=perProt[key];
    if(!sc){ sc=trovaScalo(g(r,iN),eta); if(sc) agg++; else{ sc=nuovoScalo(); n++; } sc.prot=prot; sc.annoProt=parseInt(anno(eta),10)||sc.annoProt; Object.assign(sc,{nave:upper(g(r,iN)),eta:eta||sc.eta,etd:isoData(g(r,iDP))||sc.etd,tipo:upper(g(r,iT))||sc.tipo,gt:num(g(r,iG))||sc.gt,nt:num(g(r,iNT))||sc.nt,cliente:g(r,iC)||sc.cliente,carico:g(r,iCa)||sc.carico,ricevitore:g(r,iR)||sc.ricevitore,note:g(r,iNo)||sc.note,intestazione:g(r,iI).replace(/\s*\/\s*/g,"\n")||sc.intestazione});
      sc.pagDir=/PAG\s*DIR/i.test(g(r,iNo)); var bon=num(g(r,iB)); if(bon&&!(sc.incassi||[]).length){ var bk=S.cfg.banche.filter(function(b){ return upper(b.nome).indexOf(upper(g(r,iBa)).split(" ")[0])===0; })[0]; sc.incassi=[{importo:bon,data:isoData(g(r,iDB)),banca:bk?bk.id:sc.banca,note:"bonifico (Mastrino)"}]; if(bk) sc.banca=bk.id; }
      var pdaTot=num(g(r,iPda)); if(pdaTot) sc.pdaMastrino=pdaTot; perProt[key]=sc; }
    var forn=upper(g(r,iF)); if(forn){ var tot=num(g(r,iTo)), ip=num(g(r,iIP)), descr=g(r,iDe), vk=vocePerFornitore(forn,descr);
      if(ip!==null&&vk!=="other"&&(!sc.pda.items[vk]||sc.pda.items[vk]==="")){ var ex=num(sc.pda.items[vk])||0; sc.pda.items[vk]=String(r2(ex+ip)); } else if(ip!==null&&vk==="other") sc.pda.extra.push({d:forn+(descr?" – "+descr:""),v:String(ip)});
      if(tot!==null||g(r,iNF)){ var dup=false; for(var k in S.spese){ var s=S.spese[k]; if(s.scalo===sc.id&&upper(s.fornitore)===forn&&(s.numFattura||"")===g(r,iNF)&&num(s.totale)===tot){ dup=true; break; } }
        if(!dup){ await scriviSpesa({id:nuovoId("sp"),scalo:sc.id,fornitore:forn,voce:vk,numFattura:g(r,iNF),dataFattura:isoData(g(r,iDF)),totale:tot,descrizione:descr,dataPagamento:isoData(g(r,iDPa)),modo:g(r,iMo),note:g(r,iNS)}); ns++; } } } }
  for(var kk in perProt){ var s2=perProt[kk]; if(s2.pdaMastrino&&Math.abs(totPda(s2)-s2.pdaMastrino)>0.5){ var diff=r2(s2.pdaMastrino-totali(s2,"pda").sub-(num(s2.pda.stamp)||0)); if(Math.abs(diff)>0.5) s2.pda.extra.push({d:"Altre voci PDA (Mastrino)",v:String(diff)}); } delete s2.pdaMastrino; await scriviScalo(s2); }
  avviso("Mastrino: "+n+" scali nuovi, "+agg+" aggiornati, "+ns+" fatture."); render(); }
function backupJson(){ return JSON.stringify({tipo:"portolano",versione:1,esportato:new Date().toISOString(),cfg:S.cfgRaw,scali:S.scali,spese:S.spese},null,1); }
async function importaBackup(txt){ var j; try{ j=JSON.parse(txt); }catch(e){ avviso("File non valido."); return; } if(j.tipo!=="portolano"){ avviso("Non è un backup di Portolano."); return; }
  if(j.cfg){ S.cfgRaw=j.cfg; await scriviCfg(); } var n=0; for(var k in j.scali||{}){ await scriviScalo(j.scali[k]); n++; } for(var q in j.spese||{}){ await scriviSpesa(j.spese[q]); } avviso("Backup importato: "+n+" scali."); render(); }
function csvOut(rows){ return rows.map(function(r){ return r.map(function(c){ c=c==null?"":String(c); return /[";\n]/.test(c)?'"'+c.replace(/"/g,'""')+'"':c; }).join(";"); }).join("\r\n"); }
function esportaCsv(){ var rows=[["PROT","ANNO","ETA","ETD","NAVE","IMO","BANDIERA","TIPO","GT","NT","CLIENTE","OPERAZIONE","CARICO","PDA","FDA","INCASSATO","STATO","FORNITORE","VOCE","N. FATTURA","DATA FATTURA","TOTALE","PAGATA IL","NOTE"]], n=function(x){ return x==null?"":String(x).replace(".",","); };
  listaScali().forEach(function(s){ var base=[s.prot,s.annoProt,dIt(s.eta),dIt(s.etd),s.nave,s.imo,s.flag,s.tipo,n(s.gt),n(s.nt),s.cliente,s.operazione,s.carico,n(totPda(s)),n(totFda(s)),n(incassato(s)),statoScalo(s).t]; var sp=speseDi(s.id); if(!sp.length) rows.push(base.concat(["","","","","","",""])); sp.forEach(function(x){ var v=voce(x.voce); rows.push(base.concat([x.fornitore,v?v.label:x.voce,x.numFattura,dIt(x.dataFattura),n(x.totale),dIt(x.dataPagamento),x.note])); }); });
  return "\uFEFF"+csvOut(rows); }
async function scarica(nome,data){ if(S.downloads){ try{ await S.downloads.save({filename:nome,data:data}); return; }catch(e){} } try{ var a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([data],{type:"text/plain"})); a.download=nome; document.body.appendChild(a); a.click(); a.remove(); }catch(e){ avviso("Download non disponibile qui."); } }

/* ---------- eventi ---------- */
function sel(){ return S.scali[S.sel]; }
function eventi(){ var sc=sel();
  on("nuovoScalo","click",async function(){ var n=nuovoScalo(); await scriviScalo(n); S.sel=n.id; S.tab="nave"; render(); var e=document.getElementById("n_nave"); if(e) e.focus(); });
  on("q","input",function(){ S.q=this.value; var p=this.selectionStart; render(); var e=document.getElementById("q"); if(e){ e.focus(); e.setSelectionRange(p,p); } });
  on("fAnno","change",function(){ S.anno=this.value; render(); }); on("fStato","change",function(){ S.filtro=this.value; render(); });
  document.querySelectorAll("[data-filtro]").forEach(function(b){ b.addEventListener("click",function(){ S.filtro=b.getAttribute("data-filtro"); render(); }); });
  document.querySelectorAll("th[data-sort]").forEach(function(t){ t.addEventListener("click",function(){ var k=t.getAttribute("data-sort"), O=S.ordScali||{k:"",d:-1}; S.ordScali=(O.k===k)?{k:k,d:-O.d}:{k:k,d:(k==="nave"||k==="cliente"||k==="operazione"||k==="stato")?1:-1}; render(); }); });
  document.querySelectorAll("[data-quick]").forEach(function(b){ b.addEventListener("click",async function(){ var q=b.getAttribute("data-quick"); S.qg=""; var g=document.getElementById("qg"); if(g) g.value="";
    if(q==="scalo"){ var n=nuovoScalo(); await scriviScalo(n); S.view="scali"; S.sel=n.id; S.tab="nave"; render(); var e=document.getElementById("n_nave"); if(e) e.focus(); }
    else { S.view="fatture"; S.sel=null; S.editSpesa=null; S.bozza=null; S.dupWarn=null; S.pagTmp=null; render(); var f=document.getElementById("f_forn"); if(f){ f.focus(); f.select(); } } window.scrollTo(0,0); }); });
  document.querySelectorAll("tr.row[data-sc]").forEach(function(tr){ tr.addEventListener("click",function(){ S.sel=tr.getAttribute("data-sc"); S.tab="nave"; S.hl=null; render(); window.scrollTo(0,0); }); });
  document.querySelectorAll("[data-go]").forEach(function(b){ b.addEventListener("click",function(){ var id=b.getAttribute("data-go"); if(!S.scali[id]) return; S.view="scali"; S.sel=id; S.hl=b.getAttribute("data-hl"); S.tab=S.hl?"spese":"nave"; render(); window.scrollTo(0,0); }); });
  on("indietro","click",function(){ S.sel=null; S.editSpesa=null; S.dupWarn=null; S.bozza=null; S.pagTmp=null; render(); });
  document.querySelectorAll("[data-tab]").forEach(function(b){ b.addEventListener("click",function(){ S.tab=b.getAttribute("data-tab"); S.editSpesa=null; S.dupWarn=null; S.bozza=null; S.pagTmp=null; render(); }); });
  document.querySelectorAll("[data-doc]").forEach(function(b){ b.addEventListener("click",function(){ if(!sc) return; S.doc={id:sc.id,mode:b.getAttribute("data-doc")}; apriDoc(S.doc); }); });
  if(sc){
    on("elimina","click",async function(){ if(!confirm("Eliminare lo scalo "+sc.nave+" e le sue fatture?")) return; await cancellaScalo(sc.id); S.sel=null; render(); avviso("Scalo eliminato."); });
    on("duplica","click",async function(){ var n=nuovoScalo(); ["nave","imo","callSign","flag","tipo","gt","nt","dwt","loa","pescaggio","yob","cliente","intestazione","attn","banca","agente","ormeggio","operazione","carico","ricevitore"].forEach(function(k){ n[k]=sc[k]; }); n.pda=clone(sc.pda); n.pda.inviato=""; await scriviScalo(n); S.sel=n.id; S.tab="nave"; render(); avviso("Nuovo scalo creato dalla stessa nave."); });
    on("n_nave","change",function(){ var nome=upper(this.value), prev=listaScali().filter(function(s){ return s.id!==sc.id&&upper(s.nave)===nome; })[0], ps=naveDaPS(nome); if(!prev&&!ps) return; var fonti=[], usati={}; if(prev) fonti.push({k:"scalo",d:prev}); if(ps) fonti.push({k:"ps",d:ps});
      ["imo","callSign","flag","tipo","gt","nt","dwt","loa","yob","cliente"].forEach(function(k){ var e=document.getElementById("n_"+k); if(!e||e.value) return; for(var i=0;i<fonti.length;i++){ var v=fonti[i].d[k]; if(v!=null&&v!==""){ e.value=typeof v==="string"?upper(v):v; usati[fonti[i].k]=1; break; } } });
      var m=[]; if(usati.scalo) m.push("dallo scalo del "+dIt(prev.eta)); if(usati.ps) m.push("dal file di Pratiche di Scalo"); if(m.length) avviso("Dati nave ripresi "+m.join(" e ")+"."); });
    on("psFile","change",function(){ var inp=this; leggiFile(inp,function(txt,nome){ var j; try{ j=JSON.parse(txt); }catch(e){ avviso("File non valido."); return; } var D=normalizzaPS(j); if(!D||!D.pratiche.length){ avviso("Nel file non ci sono pratiche: serve PORTOLANO_DATI_*.json (Estrai dati) o BACKUP_PRATICHE_*.json di Pratiche di Scalo."); return; } ricordaPS(nome,D); S.psPick=true; S.psQ=""; render(); avviso(D.pratiche.length+" pratiche lette da "+nome+"."); }); });
    on("psApri","click",function(){ S.psPick=!S.psPick; render(); });
    on("psQ","input",function(){ S.psQ=this.value; var pn=document.querySelector(".pspanel"); if(!pn) return; var tmp=document.createElement("div"); tmp.innerHTML=pannelloPS(sc); var nuovo=tmp.firstChild; var tb=nuovo.querySelector("tbody"), cur=pn.querySelector("tbody"), msg=nuovo.querySelector(".panel-b > p.sub"); if(tb&&cur) cur.innerHTML=tb.innerHTML; else if(!tb&&cur){ cur.innerHTML=""; } legaPS(sc); });
    on("psPda","change",function(){ S.psNoPda=!this.checked; }); on("psVuoti","change",function(){ S.psVuoti=this.checked; });
    on("psTutte","click",async function(){ var D=psDati(); if(!D) return; if(!confirm("Creare o aggiornare nell'archivio uno scalo per ognuna delle "+D.dati.pratiche.length+" pratiche del file?")) return; var n=0,agg=0; for(var i=0;i<D.dati.pratiche.length;i++){ var p=D.dati.pratiche[i], sx=trovaScalo(p.nave,isoData(p.eta)); if(sx) agg++; else{ sx=nuovoScalo(); n++; } applicaPS(sx,p,{pda:true}); await scriviScalo(sx); } S.psPick=false; render(); avviso("Pratiche di Scalo: "+n+" scali nuovi, "+agg+" aggiornati."); });
    legaPS(sc);
    on("salvaNave","click",async function(){ var o=leggiNave(sc); if(!o.nave){ avviso("Scrivi il nome della nave."); return; } var prev=listaScali().filter(function(s){ return s.id!==sc.id&&upper(s.nave)===o.nave&&!s.intestazione===false; })[0]; if(prev&&!o.intestazione&&prev.intestazione) o.intestazione=prev.intestazione; await scriviScalo(o); avviso("Scalo salvato."); render(); });
    on("salvaIntest","click",async function(){ sc.intestazione=val("i_intest"); sc.banca=val("i_banca"); sc.attn=val("i_attn"); await scriviScalo(sc); avviso("Intestazione salvata."); render(); });
    on("i_riusa","change",function(){ if(this.value){ document.getElementById("i_intest").value=this.value; } });
    on("salvaPda","click",async function(){ sc.pda=leggiPda(sc); await scriviScalo(sc); avviso("PDA salvato: € "+eur(totPda(sc))); render(); });
    on("pdaAzzera","click",async function(){ sc.pda.items={}; await scriviScalo(sc); render(); });
    on("pdaExtra","click",function(){ sc.pda=leggiPda(sc); sc.pda.extra.push({d:"",v:""}); render(); });
    document.querySelectorAll("[data-pxdel]").forEach(function(b){ b.addEventListener("click",function(){ sc.pda=leggiPda(sc); sc.pda.extra.splice(parseInt(b.getAttribute("data-pxdel"),10),1); render(); }); });
    ["p_nPil","p_nOrm","p_nTug","p_tugs","p_transfer","p_anc","p_chim","p_stamp"].forEach(function(id){ on(id,"input",function(){ aggiornaPda(sc); }); on(id,"change",function(){ aggiornaPda(sc); }); });
    document.querySelectorAll("[data-pv]").forEach(function(i){ i.addEventListener("focus",function(){ if(i.classList.contains("auto")){ i.value=""; i.classList.remove("auto"); } }); i.addEventListener("change",function(){ aggiornaPda(sc); }); });
    on("nuovaSpesa","click",function(){ S.editSpesa="nuova"; S.dupWarn=null; S.dupOk=null; S.bozza=null; S.pagTmp=null; render(); var e=document.getElementById("s_forn"); if(e) e.focus(); });
    document.querySelectorAll("tr.row[data-sp]").forEach(function(tr){ tr.addEventListener("click",function(){ S.editSpesa=tr.getAttribute("data-sp"); S.dupWarn=null; S.bozza=null; S.pagTmp=null; render(); }); });
    on("s_forn","change",function(){ var v=document.getElementById("s_voce"); if(v&&!v.value){ var k=vocePerFornitore(this.value,val("s_descr")); if(k!=="other") v.value=k; } });
    on("s_voce","change",function(){ var b=document.getElementById("s_voceBox"); if(b){ b.hidden=this.value!=="libera"; if(!b.hidden) document.getElementById("s_voceTesto").focus(); } });
    ["s_imp","s_ivap","s_iva","s_rit"].forEach(function(id){ on(id,"change",function(){ calcIva("s_"); }); });
    on("s_pgAdd","click",function(){ if(!aggPagamento("s_")) return; var e=leggiSpesa(sc); S.bozza=Object.assign({},e,{id:S.editSpesa==="nuova"?"":e.id}); S.dupWarn=null; render(); });
    document.querySelectorAll("[data-pgdel]").forEach(function(b){ b.addEventListener("click",function(){ if(S.view!=="scali") return; S.pagTmp.splice(parseInt(b.getAttribute("data-pgdel"),10),1); var e=leggiSpesa(sc); S.bozza=Object.assign({},e,{id:S.editSpesa==="nuova"?"":e.id}); render(); }); });
    on("annullaSpesa","click",function(){ S.editSpesa=null; S.dupWarn=null; S.bozza=null; S.pagTmp=null; render(); }); on("dupAnnulla","click",function(){ S.dupWarn=null; render(); });
    on("salvaSpesa","click",async function(){ var e=leggiSpesa(sc); if(!e.fornitore){ avviso("Indica il fornitore."); return; } if(e.voce==="libera"&&!e.voceLibera){ avviso("Scrivi il nome della voce."); return; } var dup=doppioniDi(e), firma=JSON.stringify([e.fornitore,normFatt(e.numFattura),e.totale,e.dataFattura,e.scalo]);
      if(dup.length&&S.dupOk!==firma){ S.dupWarn={firma:firma,lista:dup}; S.bozza=Object.assign({},e,{id:S.editSpesa==="nuova"?"":e.id}); render(); return; } await scriviSpesa(e); S.editSpesa=null; S.dupWarn=null; S.dupOk=null; S.bozza=null; S.pagTmp=null; avviso("Fattura registrata."); render(); });
    on("dupComunque","click",function(){ S.dupOk=S.dupWarn.firma; S.dupWarn=null; document.getElementById("salvaSpesa").click(); });
    on("eliminaSpesa","click",async function(){ if(!confirm("Eliminare la fattura?")) return; await cancellaSpesa(S.editSpesa); S.editSpesa=null; S.pagTmp=null; S.bozza=null; S.pagTmp=null; render(); });
    document.querySelectorAll("[data-abbq]").forEach(function(b){ b.addEventListener("click",async function(){ var s=S.spese[b.getAttribute("data-abbq")]; if(!s) return; await abbina(s.id,sc.id); S.hl=s.id; render(); avviso("Fattura "+s.fornitore+" abbinata a "+sc.nave+"."); }); });
    document.querySelectorAll(".modes [data-mode]").forEach(function(b){ b.addEventListener("click",function(){ S.contoMode=b.getAttribute("data-mode"); render(); }); });
    on("salvaFda","click",async function(){ sc.fda=leggiFda(sc); await scriviScalo(sc); avviso("FDA salvato: € "+eur(totFda(sc))); render(); });
    on("fdaNum","click",function(){ var d=document.getElementById("f_dataFatt"), e=document.getElementById("f_numero"); if(d&&!d.value) d.value=val("f_inviato")||oggi(); if(e){ e.value=prossimoNumeroFda(anno(d?d.value:oggi())); e.focus(); } });
    on("fdaExtra","click",function(){ sc.fda=leggiFda(sc); sc.fda.extra.push({d:"",v:""}); render(); });
    document.querySelectorAll("[data-fxdel]").forEach(function(b){ b.addEventListener("click",function(){ sc.fda=leggiFda(sc); sc.fda.extra.splice(parseInt(b.getAttribute("data-fxdel"),10),1); render(); }); });
    document.querySelectorAll("[data-fv]").forEach(function(i){ i.addEventListener("focus",function(){ if(i.classList.contains("auto")){ i.value=""; i.classList.remove("auto"); } }); });
    on("addIncasso","click",async function(){ var imp=num(val("c_importo")); if(!imp){ avviso("Indica l'importo."); return; } sc.incassi=sc.incassi||[]; sc.incassi.push({importo:imp,data:val("c_data"),banca:val("c_banca"),note:val("c_note")}); await scriviScalo(sc); avviso("Incasso registrato."); render(); });
    document.querySelectorAll("[data-incdel]").forEach(function(b){ b.addEventListener("click",async function(){ sc.incassi.splice(parseInt(b.getAttribute("data-incdel"),10),1); await scriviScalo(sc); render(); }); });
  }
  document.querySelectorAll("[data-abbina]").forEach(function(b){ b.addEventListener("click",function(){ S.view="fatture"; S.sel=null; S.editSpesa=null; S.bozza=null; S.dupWarn=null; S.hl=b.getAttribute("data-abbina"); render(); window.scrollTo(0,0); }); });
  if(S.view==="fatture"){
    on("f_more","toggle",function(){ S.fMore=this.open; }); on("f_forn","focus",function(){ this.select(); });
    document.querySelectorAll('#main input[id^="f_"]').forEach(function(i){ i.addEventListener("keydown",function(ev){ if(ev.key!=="Enter") return; ev.preventDefault(); var b=document.getElementById(i.id.indexOf("f_pg_")===0?"f_pgAdd":"f_salva"); if(b) b.click(); }); });
    on("f_forn","change",function(){ var v=document.getElementById("f_voce"); if(v&&v.value!=="libera"){ var k=vocePerFornitore(this.value,val("f_descr")); if(k!=="other"||!v.value) v.value=k==="other"?"":k; } });
    on("f_voce","change",function(){ var b=document.getElementById("f_voceBox"); if(b){ b.hidden=this.value!=="libera"; if(!b.hidden) document.getElementById("f_voceTesto").focus(); } });
    ["f_imp","f_ivap","f_iva","f_rit"].forEach(function(id){ on(id,"change",function(){ calcIva("f_"); }); });
    on("f_pgAdd","click",function(){ if(!aggPagamento("f_")) return; var e=leggiFattura(), mod=!!(S.editSpesa&&S.editSpesa!=="nuova"&&S.spese[S.editSpesa]); S.bozza=Object.assign({},e,{id:mod?e.id:""}); S.dupWarn=null; render(); });
    document.querySelectorAll("[data-pgdel]").forEach(function(b){ b.addEventListener("click",function(){ S.pagTmp.splice(parseInt(b.getAttribute("data-pgdel"),10),1); var e=leggiFattura(), mod=!!(S.editSpesa&&S.editSpesa!=="nuova"&&S.spese[S.editSpesa]); S.bozza=Object.assign({},e,{id:mod?e.id:""}); render(); }); });
    on("f_salva","click",async function(){ var e=leggiFattura(); if(!e.fornitore){ avviso("Indica il fornitore."); return; } if(e.totale===null){ avviso("Indica il totale della fattura."); return; } if(e.voce==="libera"&&!e.voceLibera){ avviso("Scrivi il nome della voce."); return; }
      var mod=!!(S.editSpesa&&S.editSpesa!=="nuova"&&S.spese[S.editSpesa]), dup=doppioniDi(e), firma=JSON.stringify([e.fornitore,normFatt(e.numFattura),e.totale,e.dataFattura]);
      if(dup.length&&S.dupOk!==firma){ S.dupWarn={firma:firma,lista:dup}; S.bozza=Object.assign({},e,{id:mod?e.id:""}); render(); return; }
      await scriviSpesa(e); if(!mod) S.ultimaFatt={fornitore:e.fornitore,dataFattura:e.dataFattura}; S.editSpesa=null; S.dupWarn=null; S.dupOk=null; S.bozza=null; S.pagTmp=null; S.fMore=null; S.hl=e.id; render(); avviso(mod?"Fattura aggiornata.":"Fattura aggiunta: ora scegli l'approdo al passo 2."); var f=document.getElementById("f_forn"); if(f&&!mod){ f.focus(); f.select(); } });
    on("f_annulla","click",function(){ S.editSpesa=null; S.dupWarn=null; S.bozza=null; S.pagTmp=null; render(); }); on("dupAnnulla","click",function(){ S.dupWarn=null; render(); });
    on("dupComunque","click",function(){ S.dupOk=S.dupWarn.firma; S.dupWarn=null; document.getElementById("f_salva").click(); });
    on("f_elimina","click",async function(){ if(!confirm("Eliminare la fattura?")) return; await cancellaSpesa(S.editSpesa); S.editSpesa=null; S.bozza=null; S.dupWarn=null; render(); avviso("Fattura eliminata."); });
    document.querySelectorAll("[data-fmod]").forEach(function(b){ b.addEventListener("click",function(){ S.editSpesa=b.getAttribute("data-fmod"); S.bozza=null; S.dupWarn=null; S.hl=S.editSpesa; render(); window.scrollTo(0,0); }); });
    document.querySelectorAll("[data-fabb]").forEach(function(b){ b.addEventListener("click",async function(){ var id=b.getAttribute("data-fabb"), sel=document.querySelector('[data-fsc="'+id+'"]'); if(!sel||!sel.value){ avviso("Scegli prima l'approdo."); if(sel) sel.focus(); return; }
      var sc=S.scali[sel.value]; if(!(await abbina(id,sel.value))) return; S.hl=null; render(); avviso("Fattura "+(S.spese[id]||{}).fornitore+" abbinata a "+sc.nave+" (prot. "+sc.prot+")."); }); });
    on("f_abbinaTutte","click",async function(){ var n=0, sels=document.querySelectorAll("[data-fsc]"); for(var i=0;i<sels.length;i++){ if(sels[i].value&&await abbina(sels[i].getAttribute("data-fsc"),sels[i].value)) n++; } if(!n){ avviso("Scegli l'approdo di almeno una fattura."); return; } S.hl=null; render(); avviso(n+" fatture abbinate."); });
  }
  on("ecForn","change",function(){ S.forn=this.value; render(); }); on("ecStato","change",function(){ S.fornStato=this.value; render(); }); on("ecAnno","change",function(){ S.ecAnno=this.value; render(); });
  document.querySelectorAll("[data-paga]").forEach(function(b){ b.addEventListener("click",async function(){ var s=S.spese[b.getAttribute("data-paga")]; var res=residuoDi(s); s.pagamenti=pagamentiDi(s).map(function(p){ return {data:p.data,importo:p.importo,modo:p.modo||"",note:p.note||""}; }).concat(res>0.005?[{data:oggi(),importo:res,modo:s.modo||"bonifico",note:""}]:[]); normalizzaPagamenti(s); if(!s.dataPagamento) s.dataPagamento=oggi(); await scriviSpesa(s); render(); }); });
  document.querySelectorAll("[data-riapri]").forEach(function(b){ b.addEventListener("click",async function(){ var s=S.spese[b.getAttribute("data-riapri")]; s.dataPagamento=""; s.pagamenti=[]; await scriviSpesa(s); render(); }); });
  on("rAnno","change",function(){ S.anno=this.value; render(); });
  document.querySelectorAll("[data-imp]").forEach(function(b){ b.addEventListener("click",function(){ S.imp=b.getAttribute("data-imp"); render(); }); });
  on("salvaAg","click",async function(){ var a={}; ["nome","nomeBreve","sottotitolo","indirizzo","citta","tel","fax","email","piva","firmatario"].forEach(function(k){ a[k]=val("ag_"+k); }); S.cfgRaw.ag=a;
    var d=Object.assign({},S.cfg.doc); ["layout","lingua","colore","titoloPda","titoloFda","notaPda","notaFda","piede"].forEach(function(k){ d[k]=val("d_"+k); }); ["mostraFax","mostraEmail","mostraPiva","mostraMessrs","mostraBanca","mostraFirma","nascondiZero"].forEach(function(k){ d[k]=val("d_"+k); });
    var f=document.getElementById("d_logo"); if(f&&f.files&&f.files[0]){ d.logo=await new Promise(function(res){ var r=new FileReader(); r.onload=function(){ res(String(r.result)); }; r.readAsDataURL(f.files[0]); }); if(d.logo.length>300000){ avviso("Logo troppo grande (max ~200 KB)."); d.logo=S.cfg.doc.logo; } }
    S.cfgRaw.doc=d; await scriviCfg(); avviso("Intestazione salvata."); render(); });
  on("d_logoDel","click",async function(){ S.cfgRaw.doc=Object.assign({},S.cfg.doc,{logo:""}); await scriviCfg(); render(); });
  on("anteprimaAg","click",anteprimaAg);
  on("salvaBanche","click",async function(){ var out=[]; document.querySelectorAll("[data-bn]").forEach(function(i){ var idx=i.getAttribute("data-bn"), n=i.value.trim(); if(!n) return; out.push({id:(S.cfg.banche[idx]||{}).id||nuovoId("b"),nome:n,iban:document.querySelector('[data-bi="'+idx+'"]').value.replace(/\s/g,"").toUpperCase(),bic:document.querySelector('[data-bb="'+idx+'"]').value.trim().toUpperCase()}); }); S.cfgRaw.banche=out; await scriviCfg(); avviso("Banche salvate."); render(); });
  on("bAdd","click",function(){ S.cfgRaw.banche=clone(S.cfg.banche); S.cfgRaw.banche.push({id:nuovoId("b"),nome:"",iban:"",bic:""}); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); render(); });
  document.querySelectorAll("[data-bdel]").forEach(function(b){ b.addEventListener("click",async function(){ S.cfgRaw.banche=clone(S.cfg.banche); S.cfgRaw.banche.splice(parseInt(b.getAttribute("data-bdel"),10),1); await scriviCfg(); render(); }); });
  on("salvaTariffe","click",async function(){ leggiTariffe(); await scriviCfg(); avviso("Tariffe salvate."); render(); });
  on("tariffeReset","click",async function(){ ["pil","orm","tug","transfer","anc","chim"].forEach(function(k){ delete S.cfgRaw[k]; }); await scriviCfg(); render(); });
  document.querySelectorAll("[data-tadd]").forEach(function(b){ b.addEventListener("click",function(){ leggiTariffe(); var t=b.getAttribute("data-tadd"), bd=S.cfgRaw[t].bands, last=bd[bd.length-1]||[0,0,0]; bd.push([last[1]+1,last[1]+1000,last[2]]); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); render(); }); });
  document.querySelectorAll("[data-tdel]").forEach(function(b){ b.addEventListener("click",function(){ leggiTariffe(); var p=b.getAttribute("data-tdel").split(":"); S.cfgRaw[p[0]].bands.splice(parseInt(p[1],10),1); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); render(); }); });
  var pg=document.getElementById("provaGt"); if(pg){ var prova=function(){ var gt=num(pg.value)||0, C=S.cfg; document.getElementById("provaOut").textContent="piloti € "+eur(rate(C.pil,gt))+" · ormeggiatori € "+eur(rate(C.orm,gt))+" · rimorchiatore € "+eur(rate(C.tug,gt))+" per prestazione"; }; pg.addEventListener("input",prova); prova(); }
  on("salvaVoci","click",async function(){ leggiVoci(); await scriviCfg(); avviso("Voci salvate."); render(); });
  on("vociReset","click",async function(){ delete S.cfgRaw.voci; await scriviCfg(); render(); });
  on("vAdd","click",function(){ leggiVoci(); S.cfgRaw.voci.push({k:nuovoId("v"),label:"Nuova voce",forn:[],kw:[]}); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); render(); });
  document.querySelectorAll("[data-vdel]").forEach(function(b){ b.addEventListener("click",function(){ leggiVoci(); S.cfgRaw.voci.splice(parseInt(b.getAttribute("data-vdel"),10),1); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); render(); }); });
  on("salvaListe","click",async function(){ var L={}; ["agenti","tipi","bandiere","ormeggi","operazioni","porti"].forEach(function(k){ L[k]=val("l_"+k).split("\n").map(function(x){ return x.trim(); }).filter(Boolean); }); S.cfgRaw.liste=L; await scriviCfg(); avviso("Liste salvate."); render(); });
  on("bkExport","click",function(){ scarica("PORTOLANO_BACKUP_"+oggi()+".json",backupJson()); try{ localStorage.setItem("portolano.lastBackup",oggi()); }catch(e){} });
  on("salvaConta","click",async function(){ S.cfgRaw.conta=Object.assign({},S.cfgRaw.conta||{},{giorniScadenza:num(val("c_giorni"))||30,ivaDefault:num(val("c_iva"))||22,chiusoFino:val("c_chiuso"),backupAuto:num(val("c_backup"))||0,formatoNum:val("c_formato")||"{n}/{anno}",nomeAzienda:val("c_azienda")||"Fratelli Bonanno"}); await scriviCfg(); avviso("Impostazioni contabili salvate."); render(); });
  on("bkCsv","click",function(){ scarica("portolano_"+oggi()+".csv",esportaCsv()); });
  on("bkImport","change",function(){ leggiFile(this,importaBackup); }); on("impPs","change",function(){ leggiFile(this,importaPS); }); on("impMa","change",function(){ leggiFile(this,importaMastrino); });
  on("seedCarica","click",async function(){ var n=caricaSeed(); if(S.db){ for(var k in S.scali) await S.db.doc("scali/"+k).set(S.scali[k]).catch(function(){}); for(var j in S.spese) await S.db.doc("spese/"+j).set(S.spese[j]).catch(function(){}); } avviso("Archivio caricato: "+n+" scali aggiunti."); render(); });
  on("azzeraTutto","click",function(){ if(!confirm("Svuotare scali e fatture da questo browser?")) return; S.scali={}; S.spese={}; salvaLocale(); render(); });
}

/* ---------- archivio incorporato nel file ---------- */
function caricaSeed(){ var d=window.PORTOLANO_SEED; if(!d) return 0; var n=0; for(var k in d.scali||{}){ if(!S.scali[k]){ S.scali[k]=d.scali[k]; n++; } } for(var j in d.spese||{}){ if(!S.spese[j]) S.spese[j]=d.spese[j]; } if(d.cfg&&!Object.keys(S.cfgRaw).length){ S.cfgRaw=d.cfg; S.cfg=merge(CFG_DEFAULT,S.cfgRaw); } salvaLocale(); return n; }
/* ---------- avvio ---------- */
document.getElementById("nav").addEventListener("click",function(e){ var nv=document.getElementById("nav"), m=e.target.closest(".navmore"), c=e.target.closest(".navcerca"); if(c){ nv.classList.remove("more"); var q=document.getElementById("qg"); if(q){ window.scrollTo(0,0); q.focus(); q.select(); } return; } if(m){ nv.classList.toggle("more"); m.setAttribute("aria-expanded",String(nv.classList.contains("more"))); return; } var b=e.target.closest("[data-view]"); if(!b) return; nv.classList.remove("more"); S.view=b.getAttribute("data-view"); S.sel=null; S.editSpesa=null; S.dupWarn=null; S.bozza=null; S.pagTmp=null; S.hl=null; S.qg=""; var q=document.getElementById("qg"); if(q) q.value=""; render(); });
document.addEventListener("keydown",function(e){ var q=document.getElementById("qg"); if(!q) return; var ae=document.activeElement, scrive=ae&&/^(INPUT|TEXTAREA|SELECT)$/.test(ae.tagName)&&ae!==q; if((e.key==="k"||e.key==="K")&&(e.ctrlKey||e.metaKey)){ e.preventDefault(); q.focus(); q.select(); } else if(e.key==="/"&&!scrive&&ae!==q){ e.preventDefault(); q.focus(); q.select(); } else if(e.key==="Escape"&&ae===q&&q.value){ q.value=""; S.qg=""; if(S.view==="cerca") S.view="cruscotto"; render(); } });
document.getElementById("qg").addEventListener("input",function(){ S.qg=this.value; S.sel=null; S.editSpesa=null; S.bozza=null; S.pagTmp=null; if(S.qg.trim()){ S.view="cerca"; } else if(S.view==="cerca") S.view="cruscotto"; render(); });
document.addEventListener("keydown",function(e){ if(e.key==="Escape"&&S.doc){ S.doc=null; var w=document.getElementById("docwrap"); if(w) w.remove(); } });
leggiLocale(); if(window.PORTOLANO_SEED&&!Object.keys(S.scali).length){ caricaSeed(); } render();
(async function(){ if(!(window.claude&&window.claude.use)) return;
  try{ var u=await Promise.all([claude.use("db").catch(function(){ return null; }),claude.use("user").catch(function(){ return null; }),claude.use("downloads").catch(function(){ return null; })]); S.db=u[0]; S.downloads=u[2];
    if(u[1]){ try{ var me=await u[1].me(); S.user={id:me&&me.id,nome:(me&&me.name)||""}; }catch(e){} }
    if(!S.db){ render(); return; }
    S.db.collection("scali").onSnapshot(function(sn){ var m={}; sn.docs.forEach(function(d){ var v=clone(d.data()||{}); v.id=v.id||d.id; m[v.id]=v; }); if(sn.docs.length||Object.keys(S.scali).length===0) S.scali=m; salvaLocale(); render(); },function(){});
    S.db.collection("spese").onSnapshot(function(sn){ var m={}; sn.docs.forEach(function(d){ var v=clone(d.data()||{}); v.id=v.id||d.id; m[v.id]=v; }); if(sn.docs.length||Object.keys(S.spese).length===0) S.spese=m; salvaLocale(); render(); },function(){});
    S.db.doc("config/main").onSnapshot(function(sn){ if(sn&&sn.exists&&sn.data()){ S.cfgRaw=clone(sn.data()); S.cfg=merge(CFG_DEFAULT,S.cfgRaw); salvaLocale(); render(); } },function(){});
    /* prima apertura con archivio condiviso vuoto ma dati locali: li carica */
    setTimeout(async function(){ try{ var q=await S.db.collection("scali").limit(1).get(); if(!q.docs.length&&Object.keys(S.scali).length){ for(var k in S.scali) await S.db.doc("scali/"+k).set(S.scali[k]); for(var j in S.spese) await S.db.doc("spese/"+j).set(S.spese[j]); if(Object.keys(S.cfgRaw).length) await S.db.doc("config/main").set(S.cfgRaw); avviso("Archivio locale caricato in quello condiviso."); } }catch(e){} },1500);
  }catch(e){ render(); } })();
