/* ---------- Portolano: Contabilità — registro fatture, registro IVA, fatture emesse, scadenzario fornitori, partite aperte clienti, estratto conto cliente, prima nota, banca, statistiche (tutto esportabile) ---------- */
(function(){
  "use strict";
  var TABS=[["registro","Registro fatture"],["iva","Registro IVA"],["emesse","Fatture emesse"],["scadenzario","Scadenzario fornitori"],["clienti","Partite aperte clienti"],["eccliente","Estratto conto cliente"],["primanota","Prima nota"],["cassa","Prima nota cassa"],["banca","Banca"],["stat","Statistiche"]];
  S.contaTab=S.contaTab||"registro"; S.ct=S.ct||{anno:"",mese:"",forn:"",stato:"tutte",q:"",cliente:"",solo:"",banca:"",bancaImp:"",statPer:"cliente",statAnno:""}; S.bk=S.bk||{righe:[],testo:""};
  var MESI_IT=["gennaio","febbraio","marzo","aprile","maggio","giugno","luglio","agosto","settembre","ottobre","novembre","dicembre"];
  function ym(d){ d=String(d||""); return /^\d{4}-\d{2}/.test(d)?d.slice(0,7):""; }
  function nomeMese(m){ if(!m) return "senza data"; var p=m.split("-"); return (MESI_IT[parseInt(p[1],10)-1]||p[1])+" "+p[0]; }
  function clienteDi(sc){ return (sc.cliente||(sc.intestazione||"").split("\n")[0]||"—").trim(); }
  function giorniDa(d){ if(!d) return null; var g=Math.floor((new Date(oggi()+"T00:00:00")-new Date(d+"T00:00:00"))/86400000); return isNaN(g)?null:g; }
  function n2(x){ return (Math.round((Number(x)||0)*100)/100).toFixed(2).replace(".",","); }
  function csvCell(v){ if(typeof v==="number") return n2(v); v=v===null||v===undefined?"":String(v); return /[;"\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v; }
  var ULTIMO=null, ESPORTA_SILENZIOSO=false;
  function esporta(nome,testata,righe){ ULTIMO={nome:nome,testata:testata,righe:righe}; if(ESPORTA_SILENZIOSO) return; var t="\uFEFF"+testata.map(csvCell).join(";")+"\r\n"+righe.map(function(r){ return r.map(csvCell).join(";"); }).join("\r\n")+"\r\n"; scarica(nome+"_"+oggi()+".csv",t); avviso("File CSV pronto: si apre con Excel."); }
  function protDi(sc){ return sc&&sc.id?(sc.prot||"?")+"/"+String(sc.annoProt||anno(sc.eta)||"").slice(2):""; }
  function lnkScalo(sc){ return sc&&sc.id?'<button class="btn lnk" data-go="'+esc(sc.id)+'">'+esc(protDi(sc))+'</button>':'<span class="chip warn">da abbinare</span>'; }
  function selAnni(id,anni,v){ return '<div class="field"><select id="'+id+'" aria-label="Anno">'+opt("","tutti gli anni",v)+Object.keys(anni).sort().reverse().map(function(y){ return opt(y,y,v); }).join("")+'</select></div>'; }
  function selMesi(id,mesi,v){ var l=Object.keys(mesi).sort().reverse().filter(function(m){ return !S.ct.anno||m.slice(0,4)===S.ct.anno; }); return '<div class="field"><select id="'+id+'" aria-label="Mese">'+opt("","tutti i mesi",v)+l.map(function(m){ return opt(m,nomeMese(m),v); }).join("")+'</select></div>'; }
  function testa(tit,sotto,extra){ return '<div class="top"><h1>Contabilità</h1><span class="stato">'+esc(tit)+(sotto?" · "+esc(sotto):"")+'</span><div class="spacer"></div><div class="acts">'+(extra||"")+'<button class="btn" id="ctCsv">Esporta CSV (Excel)</button><button class="btn" id="ctXlsx" title="Un file Excel con tutti i prospetti, con i filtri attuali">Esporta tutto (XLSX)</button></div></div>'+
    '<div class="panel" style="margin-bottom:12px"><div class="subtabs" role="tablist">'+TABS.map(function(t){ return '<button role="tab" data-ctab="'+t[0]+'" aria-selected="'+(S.contaTab===t[0])+'">'+t[1]+'</button>'; }).join("")+'</div></div>'; }
  var CSV=null, SOLL=null;

  /* ---- 1. registro fatture ricevute ---- */
  function registro(){ var anni={},mesi={},forn={},righe=[],q=upper(S.ct.q), nNs=0;
    for(var k in S.spese){ var s=S.spese[k], sc=S.scali[s.scalo]||{}, d=s.dataFattura||sc.eta||""; if(isNs(s)||isComm(s)){ nNs++; continue; } anni[anno(d)]=1; forn[upper(s.fornitore||"")]=1;
      if(S.ct.anno&&anno(d)!==S.ct.anno) continue; var m=ym(d); if(m) mesi[m]=1; if(S.ct.mese&&m!==S.ct.mese) continue;
      if(S.ct.forn&&upper(s.fornitore)!==S.ct.forn) continue; if(S.ct.stato==="aperte"&&statoSpesa(s)==="pagata") continue; if(S.ct.stato==="pagate"&&statoSpesa(s)!=="pagata") continue;
      if(q&&!cercaOk(q,campiSpesa(s,sc))) continue;
      righe.push({s:s,sc:sc,d:d}); }
    righe.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||String(a.s.fornitore).localeCompare(String(b.s.fornitore)); });
    var tot=0,ape=0; righe.forEach(function(r){ tot+=num(r.s.totale)||0; if(statoSpesa(r.s)!=="pagata") ape+=residuoDi(r.s); });
    var h=testa("Registro fatture ricevute",righe.length+" fatture · € "+eur(tot)+(ape?" · aperte € "+eur(ape):""));
    if(nNs) h+='<div class="sub" style="margin:-8px 0 10px">Le '+nNs+' fatture registrate come NS FATTURA sono fatture emesse da '+esc(nomeAzienda())+': le trovi in <button class="btn lnk" data-ctab="emesse">Fatture emesse</button> e nel Registro IVA vendite.</div>';
    h+='<div class="panel"><div class="panel-h"><div class="field" style="flex:1;min-width:160px"><input id="ctQ" placeholder="Cerca fornitore, n. fattura, nave, cliente, voce…" value="'+esc(S.ct.q)+'" aria-label="Cerca"></div>'+selAnni("ctAnno",anni,S.ct.anno)+selMesi("ctMese",mesi,S.ct.mese)+
      '<div class="field"><select id="ctForn" aria-label="Fornitore">'+opt("","tutti i fornitori",S.ct.forn)+tuttiFornitori().filter(function(f){ return !isNsNome(f); }).map(function(f){ return opt(f,etichettaForn(f),S.ct.forn); }).join("")+'</select></div>'+
      '<div class="field"><select id="ctStato">'+opt("tutte","tutte",S.ct.stato)+opt("aperte","da pagare",S.ct.stato)+opt("pagate","pagate",S.ct.stato)+'</select></div></div>';
    if(!righe.length) h+='<div class="panel-b sub">Nessuna fattura con questi filtri.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Data fatt.</th><th>N.</th><th>Fornitore</th><th>Voce</th><th>Prot.</th><th>Nave</th><th>Cliente</th><th class="num">Totale €</th><th>Scadenza</th><th>Pagata</th><th>Note</th></tr></thead><tbody>';
      righe.forEach(function(r){ var s=r.s, sc=r.sc, sca=scadenzaDi(s), rit=(statoSpesa(s)!=="pagata"&&sca)?giorniDa(sca):null;
        h+='<tr><td>'+dIt(s.dataFattura)+'</td><td>'+esc(s.numFattura)+(s.tipo==="nc"?' <span class="chip grey">NC</span>':'')+'</td><td><strong>'+esc(s.fornitore)+'</strong>'+chipDoppia(s)+(window.PortolanoAllegati&&PortolanoAllegati.esiste(s.id)?' <button class="btn lnk" data-allegato="'+s.id+'" title="apri il file allegato">&#128206;</button>':(s.allegato&&/^https?:/.test(s.allegato)?' <a href="'+esc(s.allegato)+'" target="_blank" rel="noopener" title="allegato">&#128206;</a>':''))+'</td><td class="sub">'+esc(nomeVoce(s))+'</td><td>'+lnkScalo(sc)+'</td><td>'+esc(sc.nave||"")+'</td><td class="sub">'+esc(sc.id?clienteDi(sc):"")+'</td><td class="num">'+eur(s.totale)+'</td><td>'+dIt(sca)+(rit>0?' <span class="chip no">+'+rit+' gg</span>':"")+'</td><td>'+chipPag(s)+'</td><td class="sub">'+esc([s.descrizione,s.note].filter(Boolean).join(" · "))+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="7">Totale'+(ape?' <span class="sub">(di cui aperte € '+eur(ape)+')</span>':'')+'</td><td class="num">'+eur(tot)+'</td><td colspan="3"></td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("registro_fatture",["Data fattura","N. fattura","Tipo","Fornitore","Voce","Prot.","Nave","Cliente","Imponibile","IVA","Ritenuta","Totale","Pagato","Residuo","Scadenza","Stato","Pagata il","Modo","Descrizione","Note","Allegato"],righe.map(function(r){ var s=r.s,sc=r.sc; return [dIt(s.dataFattura),s.numFattura,s.tipo==="nc"?"Nota di credito":"Fattura",s.fornitore,nomeVoce(s),protDi(sc),sc.nave||"",sc.id?clienteDi(sc):"",num(s.imponibile)!==null?num(s.imponibile):"",num(s.iva)!==null?num(s.iva):"",num(s.ritenuta)!==null?num(s.ritenuta):"",num(s.totale)||0,pagatoDi(s),residuoDi(s),dIt(scadenzaDi(s)),statoSpesa(s),dIt(s.dataPagamento),s.modo||"",s.descrizione||"",s.note||"",s.allegato||""]; })); };
    return h+'</div>'; }

  /* ---- 2. scadenzario fornitori (sospesi passivi) ---- */
  function scadenzario(){ var righe=[], per={}, tot=0, scad=0, sett=0, forn={};
    for(var k in S.spese){ var s=S.spese[k]; if(statoSpesa(s)==="pagata"||num(s.totale)===null||isNs(s)||isComm(s)) continue; var sc=S.scali[s.scalo]||{}; if(sc.pagDir) continue; forn[upper(s.fornitore)]=1;
      if(S.ct.forn&&upper(s.fornitore)!==S.ct.forn) continue; if(S.ct.q&&!cercaOk(S.ct.q,campiSpesa(s,sc))) continue; var sca=scadenzaDi(s), rit=giorniDa(sca); if(S.ct.solo==="scadute"&&!(rit>0)) continue; if(S.ct.solo==="settimana"&&!(rit!==null&&rit<=0&&rit>=-7)) continue;
      var t=residuoDi(s); tot+=t; if(rit>0) scad+=t; else if(rit!==null&&rit>=-7) sett+=t; righe.push({s:s,sc:sc,sca:sca,rit:rit}); var p=per[upper(s.fornitore)]||(per[upper(s.fornitore)]={n:0,t:0,scad:0}); p.n++; p.t+=t; if(rit>0) p.scad+=t; }
    righe.sort(function(a,b){ return String(a.s.fornitore).localeCompare(String(b.s.fornitore))||(a.sca||"").localeCompare(b.sca||""); });
    var h=testa("Scadenzario fornitori",righe.length+" fatture aperte");
    h+='<div class="tiles"><div class="tile warn"><div class="k">Da pagare</div><div class="v">€ '+eur(tot)+'</div><div class="s">'+righe.length+' fatture aperte</div></div><div class="tile '+(scad?"no":"ok")+'"><div class="k">Scadute</div><div class="v">€ '+eur(scad)+'</div><div class="s">oltre la scadenza</div></div><div class="tile"><div class="k">In scadenza (7 gg)</div><div class="v">€ '+eur(sett)+'</div><div class="s">da pagare questa settimana</div></div><div class="tile"><div class="k">Fornitori</div><div class="v">'+Object.keys(per).length+'</div><div class="s">con partite aperte</div></div></div>';
    h+='<div class="panel"><div class="panel-h">'+'<div class="field" style="flex:1;min-width:160px"><input id="ctQ" type="search" placeholder="Cerca fattura: n., fornitore, nave, cliente, importo…" value="'+esc(S.ct.q||"")+'" aria-label="Cerca"></div>'+'<div class="field"><select id="ctForn" aria-label="Fornitore">'+opt("","tutti i fornitori",S.ct.forn)+Object.keys(forn).sort().map(function(f){ return opt(f,etichettaForn(f),S.ct.forn); }).join("")+'</select></div><div class="field"><select id="ctSolo">'+opt("","tutte le aperte",S.ct.solo)+opt("scadute","solo scadute",S.ct.solo)+opt("settimana","in scadenza entro 7 gg",S.ct.solo)+'</select></div><span class="sub">Scadenza = data indicata sulla fattura, altrimenti data fattura (o partenza della nave, se la data manca) + '+(num(S.cfg.giorniScadenza)||30)+' giorni. Escluse le fatture degli scali a pagamento diretto.</span></div>';
    if(!righe.length) h+='<div class="panel-b sub">Nessuna fattura aperta.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Fornitore</th><th>N.</th><th>Data fatt.</th><th>Scadenza</th><th>Ritardo</th><th>Prot.</th><th>Nave</th><th class="num">Residuo €</th><th></th></tr></thead><tbody>'; var cur=null;
      function chiudi(){ if(cur===null) return; var p=per[cur]; h+='<tr class="tot" style="background:var(--paper2)"><td colspan="7"><b>Totale '+esc(cur)+'</b> <span class="sub">'+p.n+' fatture'+(p.scad?' · scadute € '+eur(p.scad):'')+'</span></td><td class="num"><b>'+eur(p.t)+'</b></td><td></td></tr>'; }
      righe.forEach(function(r){ var f=upper(r.s.fornitore); if(f!==cur){ chiudi(); cur=f; }
        h+='<tr><td>'+esc(r.s.fornitore)+chipDoppia(r.s)+'</td><td>'+esc(r.s.numFattura)+'</td><td>'+dIt(r.s.dataFattura)+'</td><td>'+dIt(r.sca)+'</td><td>'+(r.rit>0?'<span class="chip no">scaduta da '+r.rit+' gg</span>':r.rit===null?'':r.rit>=-7?'<span class="chip warn">tra '+(-r.rit)+' gg</span>':'<span class="chip grey">tra '+(-r.rit)+' gg</span>')+'</td><td>'+lnkScalo(r.sc)+'</td><td>'+esc(r.sc.nave||"")+'</td><td class="num">'+eur(residuoDi(r.s))+(pagatoDi(r.s)?'<div class="sub">di € '+eur(r.s.totale)+'</div>':'')+'</td><td><button class="btn small" data-paga="'+r.s.id+'">segna pagata oggi</button></td></tr>'; });
      chiudi(); h+='</tbody><tfoot><tr><td colspan="7">Totale da pagare</td><td class="num">'+eur(tot)+'</td><td></td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("scadenzario_fornitori",["Fornitore","N. fattura","Data fattura","Scadenza","Giorni di ritardo","Prot.","Nave","Cliente","Totale fattura","Pagato","Residuo","Voce","Descrizione"],righe.map(function(r){ return [r.s.fornitore,r.s.numFattura,dIt(r.s.dataFattura),dIt(r.sca),r.rit>0?r.rit:"",protDi(r.sc),r.sc.nave||"",r.sc.id?clienteDi(r.sc):"",num(r.s.totale)||0,pagatoDi(r.s),residuoDi(r.s),nomeVoce(r.s),r.s.descrizione||""]; })); };
    return h+'</div>'; }

  /* ---- 3. partite aperte clienti (sospesi attivi) ---- */
  function clienti(){ var righe=[], per={}, tot=0, cl={};
    listaScali().forEach(function(sc){ if(sc.pagDir) return; var f=totFda(sc); if(!f) return; var i=incassato(sc), res=r2(f-i); if(res<=0.005) return; var c=clienteDi(sc); cl[c]=1; if(S.ct.cliente&&c!==S.ct.cliente) return;
      var rif=sc.fda&&sc.fda.inviato||sc.etd||sc.eta||"", eta=giorniDa(rif); tot+=res; righe.push({sc:sc,c:c,f:f,i:i,res:res,rif:rif,eta:eta}); var p=per[c]||(per[c]={n:0,t:0}); p.n++; p.t+=res; });
    righe.sort(function(a,b){ return a.c.localeCompare(b.c)||(a.rif||"").localeCompare(b.rif||""); });
    var old=righe.filter(function(r){ return r.eta>60; }).reduce(function(a,r){ return a+r.res; },0);
    var h=testa("Partite aperte clienti",righe.length+" conti da incassare");
    h+='<div class="tiles"><div class="tile no"><div class="k">Da incassare</div><div class="v">€ '+eur(tot)+'</div><div class="s">'+righe.length+' scali</div></div><div class="tile '+(old?"warn":"")+'"><div class="k">Oltre 60 giorni</div><div class="v">€ '+eur(old)+'</div><div class="s">dall\'invio del FDA (o dalla partenza)</div></div><div class="tile"><div class="k">Clienti</div><div class="v">'+Object.keys(per).length+'</div><div class="s">con partite aperte</div></div></div>';
    h+='<div class="panel"><div class="panel-h"><div class="field"><select id="ctCliente" aria-label="Cliente">'+opt("","tutti i clienti",S.ct.cliente)+Object.keys(cl).sort().map(function(c){ return opt(c,c,S.ct.cliente); }).join("")+'</select></div><span class="sub">Residuo = conto FDA − incassi registrati. Gli scali a pagamento diretto (PAG DIR) sono esclusi.</span></div>';
    if(!righe.length) h+='<div class="panel-b sub">Nessuna partita aperta: tutti i conti sono incassati.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Cliente</th><th>Prot.</th><th>Nave</th><th>ETA</th><th>FDA inviato</th><th>Anzianità</th><th class="num">FDA €</th><th class="num">Incassato €</th><th class="num">Residuo €</th></tr></thead><tbody>'; var cur=null;
      function chiudi(){ if(cur===null) return; var p=per[cur]; h+='<tr class="tot" style="background:var(--paper2)"><td colspan="8"><b>Totale '+esc(cur)+'</b> <span class="sub">'+p.n+' scali</span> <button class="btn small" data-soll="'+esc(cur)+'">Sollecito</button></td><td class="num"><b>'+eur(p.t)+'</b></td></tr>'; }
      righe.forEach(function(r){ if(r.c!==cur){ chiudi(); cur=r.c; } var sc=r.sc;
        h+='<tr><td>'+esc(r.c)+'</td><td>'+lnkScalo(sc)+'</td><td><strong>'+esc(sc.nave||"")+'</strong></td><td>'+dIt(sc.eta)+'</td><td>'+(sc.fda&&sc.fda.inviato?dIt(sc.fda.inviato):'<span class="chip grey">non inviato</span>')+'</td><td>'+(r.eta===null?"":r.eta>60?'<span class="chip no">'+r.eta+' gg</span>':r.eta>30?'<span class="chip warn">'+r.eta+' gg</span>':'<span class="chip grey">'+r.eta+' gg</span>')+'</td><td class="num">'+eur(r.f)+'</td><td class="num">'+(r.i?eur(r.i):"—")+'</td><td class="num"><b>'+eur(r.res)+'</b></td></tr>'; });
      chiudi(); h+='</tbody><tfoot><tr><td colspan="8">Totale da incassare</td><td class="num">'+eur(tot)+'</td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("partite_aperte_clienti",["Cliente","Prot.","Nave","ETA","ETD","FDA inviato il","Giorni","FDA","Incassato","Residuo"],righe.map(function(r){ var sc=r.sc; return [r.c,protDi(sc),sc.nave||"",dIt(sc.eta),dIt(sc.etd),dIt(sc.fda&&sc.fda.inviato),r.eta===null?"":r.eta,r.f,r.i,r.res]; })); };
    SOLL=function(c){ var en=(S.cfg.doc.lingua||"en")==="en", L=righe.filter(function(r){ return r.c===c; }), t=0; L.forEach(function(r){ t+=r.res; }); var A=S.cfg.ag;
      var righeT=L.map(function(r){ var sc=r.sc; return (en?"- M/V ":"- M/N ")+(sc.nave||"")+" - "+(en?"call ":"scalo ")+protDi(sc)+" - ETA "+dIt(sc.eta)+(sc.fda&&sc.fda.inviato?(en?" - FDA sent on ":" - FDA inviato il ")+dIt(sc.fda.inviato):"")+" - "+(en?"balance due EUR ":"saldo dovuto EUR ")+eur(r.res); });
      var b=(S.cfg.banche||[]).filter(function(x){ return x.id===(L[0]&&L[0].sc.banca); })[0]||S.cfg.banche[0]||{};
      var testo=en?("Dear Sirs,\n\nwith reference to the port calls handled by our agency at "+(A.citta||"Catania")+", we kindly remind you that the following disbursement accounts are still outstanding:\n\n"+righeT.join("\n")+"\n\nTotal balance due: EUR "+eur(t)+"\n\nWe would appreciate your remittance at your earliest convenience to:\n"+(b.nome||"")+" - IBAN "+(b.iban||"")+(b.bic?" - BIC/SWIFT "+b.bic:"")+"\nBeneficiary: "+A.nome+"\n\nShould the payment have already been made, please disregard this reminder and send us the remittance details.\n\nBest regards,\n"+(A.firmatario||"")+"\n"+A.nome+" - "+(A.sottotitolo||"")+"\n"+(A.tel?"Tel. "+A.tel+" - ":"")+(A.email||""))
        :("Spett.le "+c+",\n\ncon riferimento agli scali seguiti dalla nostra agenzia a "+(A.citta||"Catania")+", ricordiamo che risultano ancora da saldare i seguenti conti:\n\n"+righeT.join("\n")+"\n\nTotale da saldare: EUR "+eur(t)+"\n\nVi preghiamo di provvedere al pagamento a:\n"+(b.nome||"")+" - IBAN "+(b.iban||"")+(b.bic?" - BIC/SWIFT "+b.bic:"")+"\nBeneficiario: "+A.nome+"\n\nSe il pagamento fosse gia' stato disposto, vi preghiamo di inviarci gli estremi del bonifico.\n\nCordiali saluti,\n"+(A.firmatario||"")+"\n"+A.nome+"\n"+(A.tel?"Tel. "+A.tel+" - ":"")+(A.email||""));
      var ogg=(en?"Payment reminder - outstanding disbursement accounts - ":"Sollecito pagamento - conti scalo in sospeso - ")+A.nomeBreve;
      try{ if(navigator.clipboard) navigator.clipboard.writeText(testo); }catch(e){}
      window.location.href="mailto:?subject="+encodeURIComponent(ogg)+"&body="+encodeURIComponent(testo);
      avviso("Sollecito pronto: si apre nel programma di posta (il testo e' anche copiato negli appunti)."); };
    return h+'</div>'; }

  /* ---- 4. estratto conto cliente: addebiti (FDA) e incassi in ordine di data, saldo progressivo ---- */
  function ecCliente(){ if(window.PortolanoEC&&PortolanoEC.vistaCliente) return PortolanoEC.vistaCliente(testa,function(f){ CSV=f; },esporta);
    var cl={}, anni={}; listaScali().forEach(function(sc){ cl[clienteDi(sc)]=1; anni[anno(sc.eta||sc.creato)]=1; });
    var nomi=Object.keys(cl).sort(), c=S.ct.cliente&&cl[S.ct.cliente]?S.ct.cliente:(nomi[0]||""), mov=[];
    listaScali().forEach(function(sc){ if(clienteDi(sc)!==c) return; if(S.ct.anno&&anno(sc.eta||sc.creato)!==S.ct.anno) return; var f=totFda(sc), usaPda=!f&&totPda(sc)&&!sc.pagDir;
      if(f||usaPda) mov.push({d:(sc.fda&&sc.fda.inviato)||sc.etd||sc.eta||"",sc:sc,tipo:usaPda?"PDA (preventivo)":"FDA"+(sc.pagDir?" (pag. diretto)":""),dare:sc.pagDir?0:(f||totPda(sc)),avere:0,note:usaPda?"conto non ancora consuntivato":""});
      (sc.incassi||[]).forEach(function(i){ var b=(S.cfg.banche||[]).filter(function(x){ return x.id===i.banca; })[0]; mov.push({d:i.data||"",sc:sc,tipo:"Incasso",dare:0,avere:num(i.importo)||0,note:[(b?b.nome:i.banca),i.note].filter(Boolean).join(" · ")}); }); });
    mov.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||(a.tipo==="Incasso"?1:0)-(b.tipo==="Incasso"?1:0); });
    var td=0,ta=0,saldo=0; mov.forEach(function(m){ td+=m.dare; ta+=m.avere; m.saldo=r2(td-ta); }); saldo=r2(td-ta);
    var h=testa("Estratto conto cliente",c?c+" · saldo € "+eur(saldo):"nessun cliente");
    h+='<div class="panel"><div class="panel-h"><div class="field" style="min-width:220px"><select id="ctCliente" aria-label="Cliente">'+nomi.map(function(x){ return opt(x,x,c); }).join("")+'</select></div>'+selAnni("ctAnno",anni,S.ct.anno)+'<div class="spacer"></div><span class="sub">'+mov.length+' movimenti · addebiti € '+eur(td)+' · incassi € '+eur(ta)+'</span></div>';
    if(!mov.length) h+='<div class="panel-b sub">Nessun movimento per questo cliente nel periodo.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Data</th><th>Prot.</th><th>Nave</th><th>Movimento</th><th>Riferimento</th><th class="num">Dare €</th><th class="num">Avere €</th><th class="num">Saldo €</th></tr></thead><tbody>';
      mov.forEach(function(m){ h+='<tr><td>'+dIt(m.d)+'</td><td>'+lnkScalo(m.sc)+'</td><td>'+esc(m.sc.nave||"")+'</td><td>'+esc(m.tipo)+'</td><td class="sub">'+esc(m.note||"")+'</td><td class="num">'+(m.dare?eur(m.dare):"")+'</td><td class="num">'+(m.avere?eur(m.avere):"")+'</td><td class="num '+(m.saldo>0.005?"pos":"")+'">'+eur(m.saldo)+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="5">Totali · saldo a '+dIt(oggi())+'</td><td class="num">'+eur(td)+'</td><td class="num">'+eur(ta)+'</td><td class="num">'+eur(saldo)+'</td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("estratto_conto_"+(c||"cliente").replace(/[^A-Za-z0-9]+/g,"_"),["Cliente","Data","Prot.","Nave","Movimento","Riferimento","Dare","Avere","Saldo"],mov.map(function(m){ return [c,dIt(m.d),protDi(m.sc),m.sc.nave||"",m.tipo,m.note||"",m.dare?m.dare:"",m.avere?m.avere:"",m.saldo]; })); };
    return h+'</div>'; }

  /* ---- 5. prima nota: incassi e pagamenti per mese (e per banca) ---- */
  function primaNota(){ var mov=[], anni={};
    for(var k in S.scali){ var sc=S.scali[k]; (sc.incassi||[]).forEach(function(i){ var b=(S.cfg.banche||[]).filter(function(x){ return x.id===i.banca; })[0]; mov.push({d:i.data||"",tipo:"Incasso",chi:clienteDi(sc),sc:sc,banca:b?b.nome:(i.banca||""),entrata:num(i.importo)||0,uscita:0,note:i.note||""}); }); }
    for(var j in S.spese){ var s=S.spese[j]; if(num(s.totale)===null||isNs(s)) continue; var sc2=S.scali[s.scalo]||{}; pagamentiDi(s).forEach(function(p){ if(!num(p.importo)) return; mov.push({d:p.data||s.dataPagamento||"",tipo:isComm(s)?"Incasso ns commissione":"Pagamento",chi:s.fornitore,sc:sc2,banca:p.modo||s.modo||"",entrata:isComm(s)?num(p.importo):0,uscita:isComm(s)?0:num(p.importo),note:(s.numFattura?"fatt. "+s.numFattura+" ":"")+(p.note||s.descrizione||"")}); }); }
    for(var c in S.cassa||{}){ var cm=S.cassa[c], ci=num(cm.importo)||0; if(!ci||(cm.tipo!=="prelievo"&&cm.tipo!=="versamento")) continue; mov.push({d:cm.data||"",tipo:cm.tipo==="prelievo"?"Prelievo per cassa":"Versamento da cassa",chi:"Cassa",sc:{},banca:nomeBanca(cm.banca),entrata:cm.tipo==="versamento"?ci:0,uscita:cm.tipo==="prelievo"?ci:0,note:cm.note||cm.descr||""}); }
    mov.forEach(function(m){ anni[anno(m.d)]=1; }); mov=mov.filter(function(m){ return (!S.ct.anno||anno(m.d)===S.ct.anno)&&(!S.ct.mese||ym(m.d)===S.ct.mese)&&(!S.ct.banca||m.banca===S.ct.banca); });
    mov.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||a.tipo.localeCompare(b.tipo); });
    var te=0,tu=0,perMese={},banche={}; mov.forEach(function(m){ te+=m.entrata; tu+=m.uscita; var a=perMese[ym(m.d)||"—"]||(perMese[ym(m.d)||"—"]={e:0,u:0}); a.e+=m.entrata; a.u+=m.uscita; if(m.banca) banche[m.banca]=1; });
    var mesi={}; mov.forEach(function(m){ var y=ym(m.d); if(y) mesi[y]=1; });
    var h=testa("Prima nota",mov.length+" movimenti · entrate € "+eur(te)+" · uscite € "+eur(tu));
    h+='<div class="tiles"><div class="tile ok"><div class="k">Incassi</div><div class="v">€ '+eur(te)+'</div><div class="s">bonifici dai clienti</div></div><div class="tile warn"><div class="k">Pagamenti</div><div class="v">€ '+eur(tu)+'</div><div class="s">fatture fornitori pagate</div></div><div class="tile '+(te-tu>=0?"ok":"no")+'"><div class="k">Saldo del periodo</div><div class="v">'+(te-tu<0?"−":"")+'€ '+eur(Math.abs(te-tu))+'</div><div class="s">incassi − pagamenti</div></div></div>';
    h+='<div class="panel"><div class="panel-h">'+selAnni("ctAnno",anni,S.ct.anno)+selMesi("ctMese",mesi,S.ct.mese)+'<div class="field"><select id="ctBanca" aria-label="Banca / modo">'+opt("","tutte le banche / modi",S.ct.banca)+Object.keys(banche).sort().map(function(b){ return opt(b,b,S.ct.banca); }).join("")+'</select></div><span class="sub">Entrate = incassi registrati sugli scali; uscite = fatture fornitori con data di pagamento.</span></div>';
    if(!mov.length) h+='<div class="panel-b sub">Nessun movimento nel periodo.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Data</th><th>Movimento</th><th>Cliente / fornitore</th><th>Prot.</th><th>Nave</th><th>Banca / modo</th><th>Riferimento</th><th class="num">Entrate €</th><th class="num">Uscite €</th></tr></thead><tbody>'; var cur=null;
      function chiudi(){ if(cur===null||S.ct.mese) return; var a=perMese[cur]; h+='<tr class="tot" style="background:var(--paper2)"><td colspan="7"><b>Totale '+esc(nomeMese(cur==="—"?"":cur))+'</b></td><td class="num"><b>'+eur(a.e)+'</b></td><td class="num"><b>'+eur(a.u)+'</b></td></tr>'; }
      mov.forEach(function(m){ var y=ym(m.d)||"—"; if(y!==cur){ chiudi(); cur=y; }
        h+='<tr><td>'+dIt(m.d)+'</td><td>'+(m.tipo==="Incasso"?'<span class="chip ok">incasso</span>':m.tipo==="Incasso ns commissione"?'<span class="chip ok">incasso ns commissione</span>':m.tipo==="Versamento da cassa"?'<span class="chip ok">versamento da cassa</span>':m.tipo==="Prelievo per cassa"?'<span class="chip warn">prelievo per cassa</span>':'<span class="chip warn">pagamento</span>')+'</td><td>'+esc(m.chi)+'</td><td>'+lnkScalo(m.sc)+'</td><td>'+esc(m.sc.nave||"")+'</td><td class="sub">'+esc(m.banca)+'</td><td class="sub">'+esc(m.note)+'</td><td class="num">'+(m.entrata?eur(m.entrata):"")+'</td><td class="num">'+(m.uscita?eur(m.uscita):"")+'</td></tr>'; });
      chiudi(); h+='</tbody><tfoot><tr><td colspan="7">Totale</td><td class="num">'+eur(te)+'</td><td class="num">'+eur(tu)+'</td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("prima_nota",["Data","Movimento","Cliente / fornitore","Prot.","Nave","Banca / modo","Riferimento","Entrate","Uscite"],mov.map(function(m){ return [dIt(m.d),m.tipo,m.chi,protDi(m.sc),m.sc.nave||"",m.banca,m.note,m.entrata?m.entrata:"",m.uscita?m.uscita:""]; })); };
    return h+'</div>'; }

  /* ---- prima nota cassa: registro di cassa con spese quotidiane in contanti, prelievi/versamenti, saldo progressivo ---- */
  var CAT_CASSA=["Bolli e valori","Cancelleria","Carburante","Taxi e parcheggi","Varchi e porto","Pasti e rappresentanza","Spedizioni e corrieri","Mance e piccole spese","Varie"];
  var TIPI_CASSA=[["uscita","Uscita di cassa (spesa)"],["entrata","Entrata in cassa"],["prelievo","Prelievo dalla banca → cassa"],["versamento","Versamento cassa → banca"]];
  function cassaCont(x){ return /contant|cassa/i.test(String(x||"")); }
  function nomeBanca(id){ var b=(S.cfg.banche||[]).filter(function(x){ return x.id===id; })[0]; return b?b.nome:(id||""); }
  /* tutti i movimenti di cassa: manuali (S.cassa) + automatici (pagamenti di fatture in contanti, incassi su «Cassa (contanti)») */
  function movimentiCassa(){ var mov=[];
    for(var k in S.cassa){ var m=S.cassa[k], imp=num(m.importo)||0, sc=S.scali[m.scalo]||{}; if(!imp) continue; var e=m.tipo==="entrata"||m.tipo==="prelievo";
      mov.push({id:m.id,d:m.data||"",tipo:m.tipo||"uscita",chi:m.fornitore||"",descr:m.descr||(m.tipo==="prelievo"?"Prelievo dalla banca"+(m.banca?" "+nomeBanca(m.banca):""):m.tipo==="versamento"?"Versamento in banca"+(m.banca?" "+nomeBanca(m.banca):""):""),cat:m.categoria||"",sc:sc,entrata:e?imp:0,uscita:e?0:imp,fda:!!(m.fda&&m.tipo==="uscita"),note:m.note||"",auto:false,ord:m.updatedAt||""}); }
    for(var j in S.spese){ var s=S.spese[j]; if(num(s.totale)===null||isNs(s)) continue; var sc2=S.scali[s.scalo]||{}; pagamentiDi(s).forEach(function(p){ var pi=num(p.importo); if(!pi||!cassaCont(p.modo||s.modo)) return;
      mov.push({id:"",d:p.data||s.dataPagamento||"",tipo:isComm(s)?"entrata":"uscita",chi:s.fornitore,descr:(isComm(s)?"Incasso in contanti ns fattura ":"Pagamento in contanti fattura ")+(s.numFattura||"")+(s.descrizione?" – "+s.descrizione:""),cat:"Fatture",sc:sc2,entrata:isComm(s)?pi:0,uscita:isComm(s)?0:pi,fda:false,note:p.note||"",auto:true,spesa:s.id,ord:""}); }); }
    for(var q in S.scali){ var sc3=S.scali[q]; (sc3.incassi||[]).forEach(function(i){ var ii=num(i.importo); if(!ii||i.banca!=="cassa") return; mov.push({id:"",d:i.data||"",tipo:"entrata",chi:clienteDi(sc3),descr:"Incasso in contanti "+(sc3.nave||""),cat:"Incassi",sc:sc3,entrata:ii,uscita:0,fda:false,note:i.note||"",auto:true,ord:""}); }); }
    mov.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||(a.ord||"").localeCompare(b.ord||""); }); return mov; }
  function cassa(){ S.cs=S.cs||{}; var cs=S.cs, tutti=movimentiCassa(), mesi={}, anni={}; tutti.forEach(function(m){ var y=ym(m.d); if(y){ mesi[y]=1; anni[y.slice(0,4)]=1; } });
    if(cs.mese===undefined) cs.mese=ym(oggi()); if(cs.mese&&!mesi[cs.mese]&&cs.mese!==ym(oggi())) cs.mese="";
    var saldoOggi=0; tutti.forEach(function(m){ if(m.d<=oggi()) saldoOggi+=m.entrata-m.uscita; });
    var apertura=0, mov=[]; tutti.forEach(function(m){ var y=ym(m.d); if(!cs.mese||y===cs.mese){ if(!cs.q||cercaOk(cs.q,[m.descr,m.chi,m.cat,m.note,m.sc.nave,m.sc.prot,String(m.entrata||m.uscita)])) mov.push(m); } else if(cs.mese&&y<cs.mese) apertura+=m.entrata-m.uscita; });
    var te=0,tu=0,nf=0; mov.forEach(function(m){ te+=m.entrata; tu+=m.uscita; if(m.fda) nf++; });
    var e=null; if(cs.edit==="nuova") e={id:"",data:oggi(),tipo:"uscita",importo:"",descr:"",categoria:"",scalo:cs.scaloPre||"",fornitore:"",fda:false,voce:"other",note:"",banca:""}; else if(cs.edit&&S.cassa[cs.edit]) e=S.cassa[cs.edit];
    var h=testa("Prima nota cassa",(cs.mese?nomeMese(cs.mese):"tutti i mesi")+" · "+mov.length+" movimenti",'<button class="btn primary" id="csNuovo">+ Movimento di cassa</button>');
    h+='<div class="tiles"><div class="tile '+(saldoOggi<-0.005?"no":"ok")+'"><div class="k">Saldo cassa a oggi</div><div class="v">'+(saldoOggi<-0.005?"− €":"€")+' '+eur(Math.abs(saldoOggi))+'</div><div class="s">contanti in cassa, tutti i movimenti fino a oggi</div></div>'+
      '<div class="tile"><div class="k">Entrate '+(cs.mese?"del mese":"")+'</div><div class="v">€ '+eur(te)+'</div><div class="s">prelievi dalla banca, incassi e altre entrate</div></div>'+
      '<div class="tile warn"><div class="k">Uscite '+(cs.mese?"del mese":"")+'</div><div class="v">€ '+eur(tu)+'</div><div class="s">spese in contanti e versamenti in banca'+(nf?' · '+nf+' addebitate nei FDA':'')+'</div></div>'+
      (cs.mese?'<div class="tile"><div class="k">Saldo a fine '+esc(nomeMese(cs.mese))+'</div><div class="v">'+(apertura+te-tu<-0.005?"− €":"€")+' '+eur(Math.abs(apertura+te-tu))+'</div><div class="s">apertura € '+eur(apertura)+' + entrate − uscite</div></div>':'')+'</div>';
    if(e){ var L=listaScali(), F=tuttiFornitori(), cats={}; CAT_CASSA.forEach(function(c){ cats[c]=1; }); for(var k2 in S.cassa) if(S.cassa[k2].categoria) cats[S.cassa[k2].categoria]=1;
      h+='<div class="panel" style="background:var(--paper2)"><div class="panel-b"><div class="grid">'+
        '<div class="field"><label for="cs_tipo">Movimento</label><select id="cs_tipo">'+TIPI_CASSA.map(function(t){ return opt(t[0],t[1],e.tipo); }).join("")+'</select></div>'+campo("cs_data","Data",e.data,"date")+campo("cs_importo","Importo €",e.importo,"number")+
        '<div class="field w2"><label for="cs_descr">Descrizione</label><input id="cs_descr" value="'+esc(e.descr||"")+'" placeholder="es. marca da bollo, taxi per il porto, varco…"></div>'+
        '<div class="field"><label for="cs_cat">Categoria</label><input id="cs_cat" list="dl_cat" value="'+esc(e.categoria||"")+'" placeholder="Varie"></div>'+datalist("dl_cat",Object.keys(cats))+
        '<div class="field"><label for="cs_forn">Fornitore / beneficiario</label><input id="cs_forn" list="dl_forn" value="'+esc(e.fornitore||"")+'"></div>'+datalist("dl_forn",F)+
        '<div class="field w2"><label for="cs_scalo">Scalo (nave)</label><select id="cs_scalo">'+opt("","(nessuno: spesa generale dell\'agenzia)",e.scalo||"")+L.map(function(sc){ return opt(sc.id,etichettaScalo(sc),e.scalo||""); }).join("")+'</select></div>'+
        '<div class="field" id="cs_fdaBox"'+(e.scalo?"":" hidden")+'><label for="cs_fda">Addebito al cliente</label><select id="cs_fda">'+opt("no","Non addebitare (spesa nostra)",e.fda?"si":"no")+opt("si","Addebita nel FDA",e.fda?"si":"no")+'</select></div>'+
        '<div class="field" id="cs_voceBox"'+(e.scalo&&e.fda?"":" hidden")+'><label for="cs_voce">Voce del FDA</label><select id="cs_voce">'+S.cfg.voci.map(function(v){ return opt(v.k,v.label,e.voce||"other"); }).join("")+opt("libera","Voce a sé (con la descrizione)",e.voce||"other")+'</select></div>'+
        '<div class="field" id="cs_bancaBox"'+(e.tipo==="prelievo"||e.tipo==="versamento"?"":" hidden")+'><label for="cs_banca">Banca</label><select id="cs_banca">'+opt("","—",e.banca||"")+(S.cfg.banche||[]).map(function(b){ return opt(b.id,b.nome,e.banca||""); }).join("")+'</select></div>'+
        campo("cs_note","Note",e.note||"","text",{cls:"w2"})+'</div>'+
        '<div class="acts" style="margin-top:12px"><button class="btn primary" id="csSalva">Salva movimento</button><button class="btn" id="csChiudi">Chiudi</button>'+(e.id?'<button class="btn danger small" id="csElimina">Elimina</button>':"")+'</div></div></div>'; }
    h+='<div class="panel"><div class="panel-h"><div class="field"><select id="csMese" aria-label="Mese">'+opt("","tutti i mesi",cs.mese)+(mesi[ym(oggi())]?"":opt(ym(oggi()),nomeMese(ym(oggi())),cs.mese))+Object.keys(mesi).sort().reverse().map(function(m){ return opt(m,nomeMese(m),cs.mese); }).join("")+'</select></div><div class="field" style="flex:1;min-width:160px"><input id="csQ" type="search" placeholder="Cerca: descrizione, categoria, nave, importo…" value="'+esc(cs.q||"")+'" aria-label="Cerca"></div><span class="sub">Compaiono da soli i pagamenti di fatture fatti in contanti e gli incassi su «Cassa (contanti)»: si modificano dalla fattura o dallo scalo.</span></div>';
    if(!mov.length) h+='<div class="panel-b sub">Nessun movimento di cassa'+(cs.mese?" in "+esc(nomeMese(cs.mese)):"")+'. Premi <strong>+ Movimento di cassa</strong> per registrare una spesa, un prelievo o un versamento.</div>';
    else{ var saldo=apertura; h+='<div class="scroll"><table><thead><tr><th>Data</th><th>Movimento</th><th>Descrizione</th><th>Categoria</th><th>Beneficiario</th><th>Prot.</th><th>Nave</th><th class="num">Entrate €</th><th class="num">Uscite €</th><th class="num">Saldo €</th></tr></thead><tbody>';
      if(cs.mese) h+='<tr style="background:var(--paper2)"><td colspan="9"><b>Saldo di apertura '+esc(nomeMese(cs.mese))+'</b></td><td class="num"><b>'+eur(apertura)+'</b></td></tr>';
      mov.forEach(function(m){ saldo+=m.entrata-m.uscita; var chip=m.tipo==="prelievo"?'<span class="chip ok">prelievo</span>':m.tipo==="versamento"?'<span class="chip warn">versamento</span>':m.entrata?'<span class="chip ok">entrata</span>':'<span class="chip warn">uscita</span>';
        h+='<tr class="row'+(m.auto?"":" cs-riga")+'"'+(m.auto?(m.spesa?' data-sp-go="'+esc(m.spesa)+'"':''):' data-csid="'+esc(m.id)+'"')+'><td>'+dIt(m.d)+'</td><td>'+chip+(m.auto?' <span class="chip grey" title="registrato sulla fattura o sullo scalo">automatico</span>':'')+(m.fda?' <span class="chip ok" title="addebitata al cliente nel FDA">FDA</span>':'')+'</td><td>'+esc(m.descr)+(m.note?' <span class="sub">'+esc(m.note)+'</span>':'')+'</td><td class="sub">'+esc(m.cat)+'</td><td>'+esc(m.chi)+'</td><td>'+(m.sc.id?lnkScalo(m.sc):"")+'</td><td>'+esc(m.sc.nave||"")+'</td><td class="num">'+(m.entrata?eur(m.entrata):"")+'</td><td class="num">'+(m.uscita?eur(m.uscita):"")+'</td><td class="num'+(saldo<-0.005?" neg":"")+'">'+eur(saldo)+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="7">Totale'+(cs.mese?" "+esc(nomeMese(cs.mese)):"")+'</td><td class="num">'+eur(te)+'</td><td class="num">'+eur(tu)+'</td><td class="num">'+eur(saldo)+'</td></tr></tfoot></table></div>'; }
    CSV=function(){ var sl=apertura; esporta("prima_nota_cassa"+(cs.mese?"_"+cs.mese:""),["Data","Movimento","Descrizione","Categoria","Beneficiario","Prot.","Nave","Nel FDA","Entrate","Uscite","Saldo","Note"],mov.map(function(m){ sl+=m.entrata-m.uscita; return [dIt(m.d),m.tipo,m.descr,m.cat,m.chi,m.sc.id?protDi(m.sc):"",m.sc.nave||"",m.fda?"sì":"",m.entrata?m.entrata:"",m.uscita?m.uscita:"",r2(sl),m.note]; })); };
    return h+'</div>'; }
  function leggiCassa(){ var cs=S.cs, e=cs.edit==="nuova"?{id:nuovoId("cs")}:Object.assign({},S.cassa[cs.edit]); e.tipo=val("cs_tipo")||"uscita"; e.data=val("cs_data")||oggi(); e.importo=Math.abs(num(val("cs_importo"))||0); e.descr=val("cs_descr"); e.categoria=val("cs_cat"); e.fornitore=upper(val("cs_forn")); e.scalo=val("cs_scalo"); e.fda=!!(e.scalo&&e.tipo==="uscita"&&val("cs_fda")==="si"); e.voce=e.fda?(val("cs_voce")||"other"):""; e.banca=(e.tipo==="prelievo"||e.tipo==="versamento")?val("cs_banca"):""; e.note=val("cs_note"); return e; }
  function eventiCassa(){ if(S.contaTab!=="cassa") return;
    on("csNuovo","click",function(){ S.cs.edit="nuova"; S.cs.scaloPre=""; render(); var x=document.getElementById("cs_importo"); if(x) x.focus(); });
    on("csChiudi","click",function(){ S.cs.edit=null; S.cs.scaloPre=""; render(); });
    on("csSalva","click",async function(){ var e=leggiCassa(); if(!e.importo){ avviso("Indica l'importo."); return; } if(!e.descr&&e.tipo==="uscita"&&!e.categoria){ avviso("Scrivi una descrizione o una categoria."); return; } await scriviCassa(e); S.cs.edit=null; S.cs.scaloPre=""; if(S.cs.mese&&ym(e.data)!==S.cs.mese) S.cs.mese=ym(e.data); render(); avviso("Movimento di cassa registrato."); });
    on("csElimina","click",async function(){ if(!confirm("Eliminare questo movimento di cassa?")) return; await cancellaCassa(S.cs.edit); S.cs.edit=null; render(); });
    on("csMese","change",function(){ S.cs.mese=this.value; render(); });
    on("csQ","input",function(){ S.cs.q=this.value; var p=this.selectionStart; render(); var x=document.getElementById("csQ"); if(x){ x.focus(); x.setSelectionRange(p,p); } });
    on("cs_tipo","change",function(){ var t=this.value, b=document.getElementById("cs_bancaBox"); if(b) b.hidden=!(t==="prelievo"||t==="versamento"); var f=document.getElementById("cs_fdaBox"); if(f) f.hidden=t!=="uscita"||!val("cs_scalo"); var v=document.getElementById("cs_voceBox"); if(v) v.hidden=f.hidden||val("cs_fda")!=="si"; });
    on("cs_scalo","change",function(){ var f=document.getElementById("cs_fdaBox"); if(f) f.hidden=!this.value||val("cs_tipo")!=="uscita"; var v=document.getElementById("cs_voceBox"); if(v) v.hidden=f.hidden||val("cs_fda")!=="si"; });
    on("cs_fda","change",function(){ var v=document.getElementById("cs_voceBox"); if(v) v.hidden=this.value!=="si"; });
    document.querySelectorAll("[data-csid]").forEach(function(r){ r.addEventListener("click",function(ev){ if(ev.target.closest("button")) return; S.cs.edit=r.getAttribute("data-csid"); render(); }); });
    document.querySelectorAll("[data-sp-go]").forEach(function(r){ r.addEventListener("click",function(ev){ if(ev.target.closest("button")) return; var s=S.spese[r.getAttribute("data-sp-go")]; if(!s||!S.scali[s.scalo]) return; S.view="scali"; S.sel=s.scalo; S.tab="spese"; S.editSpesa=s.id; S.hl=s.id; render(); }); }); }

  /* ---- registro IVA acquisti (imponibile, IVA, ritenuta per mese e fornitore) ---- */
  function registroIva(){ var anni={},mesi={},righe=[],vend=[];
    for(var k in S.spese){ var s=S.spese[k]; var d=s.dataFattura||""; anni[anno(d)]=1;
      if(isNs(s)||isComm(s)){ if(S.ct.anno&&anno(d)!==S.ct.anno) continue; var mv=ym(d); if(mv) mesi[mv]=1; if(S.ct.mese&&mv!==S.ct.mese) continue; if(S.ct.forn) continue; if(S.ct.q&&!cercaOk(S.ct.q,campiSpesa(s))) continue; var iv=num(s.imponibile), vv=num(s.iva), tv0=num(s.totale); if(iv===null&&vv===null&&tv0===null) continue; vend.push({s:s,sc:S.scali[s.scalo]||{},d:d,imp:iv,iva:vv,rit:num(s.ritenuta),tot:tv0,senza:iv===null&&vv===null}); continue; } if(S.ct.anno&&anno(d)!==S.ct.anno) continue; var m=ym(d); if(m) mesi[m]=1; if(S.ct.mese&&m!==S.ct.mese) continue; if(S.ct.forn&&upper(s.fornitore)!==S.ct.forn) continue; if(S.ct.q&&!cercaOk(S.ct.q,campiSpesa(s))) continue;
      var imp=num(s.imponibile), iva=num(s.iva), rit=num(s.ritenuta), tot=num(s.totale); if(imp===null&&iva===null&&tot===null) continue; righe.push({s:s,sc:S.scali[s.scalo]||{},d:d,imp:imp,iva:iva,rit:rit,tot:tot,senza:imp===null&&iva===null}); }
    righe.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||String(a.s.fornitore).localeCompare(String(b.s.fornitore)); });
    var ti=0,tv=0,tr=0,tt=0,ns=0; righe.forEach(function(r){ ti+=r.imp||0; tv+=r.iva||0; tr+=r.rit||0; tt+=r.tot||0; if(r.senza) ns++; });
    vend.sort(function(a,b){ return (a.d||"").localeCompare(b.d||""); }); var vi=0,vvv=0,vt=0; vend.forEach(function(r){ vi+=r.imp||0; vvv+=r.iva||0; vt+=r.tot||0; });
    var h=testa("Registro IVA",righe.length+" acquisti · IVA € "+eur(tv)+" · "+vend.length+" vendite "+nomeAzienda()+" · IVA € "+eur(vvv));
    h+='<div class="tiles"><div class="tile"><div class="k">Imponibile</div><div class="v">€ '+eur(ti)+'</div></div><div class="tile"><div class="k">IVA</div><div class="v">€ '+eur(tv)+'</div></div><div class="tile"><div class="k">Ritenute</div><div class="v">€ '+eur(tr)+'</div></div><div class="tile '+(ns?"warn":"")+'"><div class="k">Totale documenti</div><div class="v">€ '+eur(tt)+'</div><div class="s">'+(ns?ns+' senza imponibile/IVA indicati':'tutti con imponibile e IVA')+'</div></div></div>';
    h+='<div class="panel"><div class="panel-h">'+'<div class="field" style="flex:1;min-width:160px"><input id="ctQ" type="search" placeholder="Cerca fattura: n., fornitore, nave, cliente, importo…" value="'+esc(S.ct.q||"")+'" aria-label="Cerca"></div>'+selAnni("ctAnno",anni,S.ct.anno)+selMesi("ctMese",mesi,S.ct.mese)+'<div class="field"><select id="ctForn" aria-label="Fornitore">'+opt("","tutti i fornitori",S.ct.forn)+tuttiFornitori().filter(function(f){ return !isNsNome(f); }).map(function(f){ return opt(f,etichettaForn(f),S.ct.forn); }).join("")+'</select></div><span class="sub">Le fatture senza imponibile/IVA compaiono con il solo totale: compila i campi dalla fattura per averle nel registro.</span></div>';
    if(!righe.length) h+='<div class="panel-b sub">Nessun documento nel periodo.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Data</th><th>N.</th><th>Tipo</th><th>Fornitore</th><th>Prot.</th><th>Nave</th><th class="num">Imponibile €</th><th class="num">IVA %</th><th class="num">IVA €</th><th class="num">Ritenuta €</th><th class="num">Totale €</th></tr></thead><tbody>'; var cur=null,si=0,sv=0,st=0;
      function chiudi(){ if(cur===null||S.ct.mese) return; h+='<tr class="tot" style="background:var(--paper2)"><td colspan="6"><b>Totale '+esc(nomeMese(cur==="—"?"":cur))+'</b></td><td class="num"><b>'+eur(si)+'</b></td><td></td><td class="num"><b>'+eur(sv)+'</b></td><td></td><td class="num"><b>'+eur(st)+'</b></td></tr>'; si=sv=st=0; }
      righe.forEach(function(r){ var y=ym(r.d)||"—"; if(y!==cur){ chiudi(); cur=y; } si+=r.imp||0; sv+=r.iva||0; st+=r.tot||0; var s=r.s;
        h+='<tr><td>'+dIt(s.dataFattura)+'</td><td>'+esc(s.numFattura)+'</td><td>'+(s.tipo==="nc"?'<span class="chip grey">NC</span>':s.tipo==="comm"?'<span class="chip grey">commissione</span>':'fattura')+'</td><td><strong>'+esc(s.fornitore)+'</strong></td><td>'+lnkScalo(r.sc)+'</td><td>'+esc(r.sc.nave||"")+'</td><td class="num">'+(r.imp!==null?eur(r.imp):'<span class="chip warn">—</span>')+'</td><td class="num">'+(num(s.ivaPerc)!==null?num(s.ivaPerc)+"%":"")+'</td><td class="num">'+(r.iva!==null?eur(r.iva):"")+'</td><td class="num">'+(r.rit!==null?eur(r.rit):"")+'</td><td class="num">'+eur(r.tot)+'</td></tr>'; });
      chiudi(); h+='</tbody><tfoot><tr><td colspan="6">Totale '+esc(S.ct.mese?nomeMese(S.ct.mese):S.ct.anno?"anno "+S.ct.anno:"tutti gli anni")+'</td><td class="num">'+eur(ti)+'</td><td></td><td class="num">'+eur(tv)+'</td><td class="num">'+eur(tr)+'</td><td class="num">'+eur(tt)+'</td></tr></tfoot></table></div>'; }
    h+='<div class="panel-h" style="border-top:1px solid var(--line)"><h2>IVA vendite · fatture emesse da '+esc(nomeAzienda())+'</h2><span class="sub">le fatture registrate come NS FATTURA</span><div class="spacer"></div><span class="sub">imponibile € '+eur(vi)+' · IVA a debito € '+eur(vvv)+' · totale € '+eur(vt)+'</span></div>';
    if(!vend.length) h+='<div class="panel-b sub">Nessuna fattura emessa nel periodo'+(S.ct.forn?' (togli il filtro fornitore)':'')+'.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>Data</th><th>N.</th><th>Tipo</th><th>Cliente</th><th>Prot.</th><th>Nave</th><th class="num">Imponibile €</th><th class="num">IVA %</th><th class="num">IVA €</th><th class="num">Totale €</th><th>Stato</th><th>Voci della fattura</th></tr></thead><tbody>';
      vend.forEach(function(r){ var s=r.s; h+='<tr><td>'+dIt(s.dataFattura)+'</td><td>'+esc(s.numFattura)+'</td><td>'+(s.tipo==="nc"?'<span class="chip grey">NC</span>':s.tipo==="comm"?'<span class="chip grey">commissione</span>':'fattura')+'</td><td><strong>'+esc(isComm(s)?s.fornitore:r.sc.id?clienteDi(r.sc):"—")+'</strong></td><td>'+lnkScalo(r.sc)+'</td><td>'+esc(r.sc.nave||"")+'</td><td class="num">'+(r.imp!==null?eur(r.imp):'<span class="chip warn">—</span>')+'</td><td class="num">'+(num(s.ivaPerc)!==null?num(s.ivaPerc)+"%":"")+'</td><td class="num">'+(r.iva!==null?eur(r.iva):"")+'</td><td class="num"><strong>'+eur(r.tot)+'</strong></td><td>'+(statoSpesa(s)==="pagata"?'<span class="chip ok">incassata</span>':'<span class="chip warn">da incassare</span>')+'</td><td class="voci-td" data-l="Voci">'+vociNsHtml(s)+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="6">Totale vendite</td><td class="num">'+eur(vi)+'</td><td></td><td class="num">'+eur(vvv)+'</td><td class="num">'+eur(vt)+'</td><td></td><td></td></tr></tfoot></table></div>'; }
    var righeIva=righe.slice(), vendIva=vend.slice();
    CSV=function(){ esporta("registro_iva",["Registro","Data","N.","Tipo","Fornitore / cliente","Prot.","Nave","Imponibile","IVA %","IVA","Ritenuta","Totale","Stato","Voci / descrizione","Note"],
      righeIva.map(function(r){ var s=r.s; return ["Acquisti",dIt(s.dataFattura),s.numFattura||"",s.tipo==="nc"?"NC":"fattura",s.fornitore,protDi(r.sc),r.sc.nave||"",r.imp!==null?r.imp:"",num(s.ivaPerc)!==null?num(s.ivaPerc):"",r.iva!==null?r.iva:"",r.rit!==null?r.rit:"",r.tot!==null?r.tot:"",statoSpesa(s),s.descrizione||"",s.note||""]; })
      .concat(vendIva.map(function(r){ var s=r.s; return ["Vendite "+nomeAzienda(),dIt(s.dataFattura),s.numFattura||"",s.tipo==="nc"?"NC":"fattura",r.sc.id?clienteDi(r.sc):"",protDi(r.sc),r.sc.nave||"",r.imp!==null?r.imp:"",num(s.ivaPerc)!==null?num(s.ivaPerc):"",r.iva!==null?r.iva:"",r.rit!==null?r.rit:"",r.tot!==null?r.tot:"",statoSpesa(s)==="pagata"?"incassata":"da incassare",vociNsTesto(s)||s.descrizione||"",s.note||""]; }))); };
    return h+'</div>'; }

  /* ---- banca: riconciliazione dell'estratto conto (CSV) con fatture e incassi ---- */
  function leggiEstratto(txt){ var rows=[]; String(txt||"").replace(/^\uFEFF/,"").split(/\r?\n/).forEach(function(l){ if(!l.trim()) return; var r=l.indexOf(";")>=0?l.split(";"):l.indexOf("\t")>=0?l.split("\t"):(csvParse(l)[0]||[l]); r=r.map(function(c){ return String(c).trim().replace(/^"|"$/g,""); }); if(r.some(function(c){ return c; })) rows.push(r); }); if(!rows.length) return [];
    var head=rows[0].map(function(c){ return upper(c); }), iD=-1,iI=-1,iDare=-1,iAvere=-1,iT=-1;
    head.forEach(function(c,i){ if(iD<0&&/DATA|DATE/.test(c)&&!/VALUTA/.test(c)) iD=i; if(iI<0&&/IMPORTO|AMOUNT/.test(c)) iI=i; if(iDare<0&&/DARE|USCIT|DEBIT|ADDEBIT/.test(c)) iDare=i; if(iAvere<0&&/AVERE|ENTRAT|CREDIT|ACCREDIT/.test(c)) iAvere=i; if(iT<0&&/DESCR|CAUSAL|DETTAGL|NARRAT|OPERAZ/.test(c)) iT=i; });
    var body=rows.slice(1); if(iD<0||(iI<0&&iDare<0&&iAvere<0)){ /* senza intestazione: prova a indovinare */ body=rows; iD=-1; rows[0].forEach(function(c,i){ if(iD<0&&/^\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4}$/.test(String(c).trim())) iD=i; }); iI=-1; rows[0].forEach(function(c,i){ if(i!==iD&&iI<0&&num(c)!==null&&/[,.]\d{2}$/.test(String(c).trim())) iI=i; }); if(iI<0) rows[0].forEach(function(c,i){ if(i!==iD&&iI<0&&num(c)!==null&&/^-?[\d.,]+$/.test(String(c).trim())) iI=i; }); iT=-1; rows[0].forEach(function(c,i){ if(i!==iD&&i!==iI&&iT<0&&String(c).trim().length>6&&num(c)===null) iT=i; }); if(iD<0||iI<0) return []; }
    function iso(d){ d=String(d||"").trim(); var m=d.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/); if(m){ var y=m[3].length===2?"20"+m[3]:m[3]; return y+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[1]).slice(-2); } var n=d.match(/^(\d{4})-(\d{2})-(\d{2})/); return n?n[0]:""; }
    var out=[]; body.forEach(function(r){ var imp=null; if(iI>=0) imp=num(r[iI]); else { var da=num(r[iDare]), av=num(r[iAvere]); imp=(av||0)-(da||0); if(da===null&&av===null) imp=null; } var d=iso(r[iD]); if(imp===null||!d) return; out.push({d:d,imp:r2(imp),txt:iT>=0?String(r[iT]||"").trim():r.filter(function(c,i){ return i!==iD&&i!==iI; }).join(" ").trim(),fatto:false}); });
    return out; }
  function candidati(m){ var out=[], t=upper(m.txt), a=Math.abs(m.imp);
    if(m.imp<0){ for(var k in S.spese){ var s=S.spese[k]; if(statoSpesa(s)==="pagata"||num(s.totale)===null||isNs(s)||isComm(s)) continue; var res=residuoDi(s), p=0; if(Math.abs(res-a)<0.01) p+=4; else if(Math.abs(num(s.totale)-a)<0.01) p+=3; var w=upper(s.fornitore).split(/\W+/).filter(function(x){ return x.length>=4; }); if(w.some(function(x){ return t.indexOf(x)>=0; })) p+=2; if(s.numFattura&&t.indexOf(upper(s.numFattura))>=0&&String(s.numFattura).length>=3) p+=2; var g=Math.abs(giorniDa(s.dataFattura)-giorniDa(m.d)); if(!isNaN(g)&&g<=45) p+=1; if(p>=2) out.push({p:p,tipo:"spesa",id:s.id,label:s.fornitore+(s.numFattura?" n. "+s.numFattura:"")+" del "+dIt(s.dataFattura)+" · residuo € "+eur(res)+(S.scali[s.scalo]?" · "+S.scali[s.scalo].nave:"")}); } }
    else{ listaScali().forEach(function(sc){ if(sc.pagDir) return; var f=totFda(sc)||totPda(sc); if(!f) return; var res=r2((totFda(sc)||totPda(sc))-incassato(sc)); if(res<=0.005) return; var p=0; if(Math.abs(res-a)<0.01) p+=4; else if(Math.abs(f-a)<0.01) p+=3; var n=upper(sc.nave||""); if(n.length>=4&&t.indexOf(n)>=0) p+=3; var c=upper(clienteDi(sc)).split(/\W+/).filter(function(x){ return x.length>=4; }); if(c.some(function(x){ return t.indexOf(x)>=0; })) p+=2; var g=Math.abs(giorniDa(sc.etd||sc.eta)-giorniDa(m.d)); if(!isNaN(g)&&g<=60) p+=1; if(p>=2) out.push({p:p,tipo:"scalo",id:sc.id,label:protDi(sc)+" "+sc.nave+" · "+clienteDi(sc)+" · residuo € "+eur(res)}); }); }
    out.sort(function(x,y){ return y.p-x.p; }); return out.slice(0,6); }
  function banca(){ var R=S.bk.righe, B=S.cfg.banche||[];
    var h=testa("Banca · riconciliazione estratto conto",R.length?R.length+" movimenti caricati":"nessun estratto caricato");
    h+='<div class="panel"><div class="panel-h"><label class="btn">Carica estratto conto (CSV) <input type="file" id="bkFile" accept=".csv,.txt" hidden></label><div class="field"><select id="ctBancaImp" aria-label="Banca degli incassi">'+B.map(function(b){ return opt(b.id,"incassi su "+b.nome,S.ct.bancaImp||(B[0]||{}).id); }).join("")+'</select></div><div class="spacer"></div><span class="sub">Colonne riconosciute: data, importo (o dare/avere), descrizione. Per ogni riga l\'app propone la fattura da pagare o lo scalo da incassare; con <em>Registra</em> il movimento viene scritto nell\'archivio.</span></div>';
    h+='<div class="panel-b"><textarea id="bkTesto" placeholder="…oppure incolla qui le righe copiate dall\'home banking (data; descrizione; importo)" style="min-height:70px">'+esc(S.bk.testo||"")+'</textarea><div class="acts" style="margin-top:8px"><button class="btn" id="bkLeggi">Leggi le righe incollate</button>'+(R.length?'<button class="btn" id="bkSvuota">Svuota elenco</button>':'')+'</div></div>';
    if(R.length){ var fatti=R.filter(function(m){ return m.fatto; }).length; h+='<div class="scroll"><table><thead><tr><th>Data</th><th>Descrizione</th><th class="num">Importo €</th><th style="min-width:280px">Abbinamento proposto</th><th></th></tr></thead><tbody>';
      R.forEach(function(m,i){ var c=m.fatto?[]:candidati(m); h+='<tr'+(m.fatto?' style="opacity:.55"':'')+'><td>'+dIt(m.d)+'</td><td class="sub">'+esc(m.txt)+'</td><td class="num '+(m.imp<0?"neg":"pos")+'">'+eur(m.imp)+'</td><td>'+(m.fatto?'<span class="chip ok">registrato</span> <span class="sub">'+esc(m.esito||"")+'</span>':c.length?'<select data-bk="'+i+'">'+c.map(function(x,j){ return opt(x.tipo+":"+x.id,(j===0?"★ ":"")+x.label,j===0?x.tipo+":"+x.id:""); }).join("")+opt("x","— nessuno —","-")+'</select>':'<span class="sub">nessuna corrispondenza: '+(m.imp<0?"nessuna fattura aperta con questo importo o fornitore":"nessun conto aperto con questo importo o nave")+'</span>')+'</td><td>'+(m.fatto||!c.length?'':'<button class="btn primary small" data-bkreg="'+i+'">Registra</button>')+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="5">'+fatti+' su '+R.length+' movimenti registrati</td></tr></tfoot></table></div>'; }
    CSV=function(){ esporta("estratto_conto_banca",["Data","Descrizione","Importo","Stato","Esito"],R.map(function(m){ return [dIt(m.d),m.txt,m.imp,m.fatto?"registrato":"da abbinare",m.esito||""]; })); };
    return h+'</div>'; }
  async function registraMov(i){ var m=S.bk.righe[i], sel=document.querySelector('[data-bk="'+i+'"]'); if(!m||!sel||!sel.value||sel.value==="x"){ avviso("Scegli l'abbinamento."); return; } var t=sel.value.split(":"), id=t.slice(1).join(":");
    if(t[0]==="spesa"){ var s=S.spese[id]; if(!s) return; var imp=Math.min(Math.abs(m.imp),residuoDi(s)); s.pagamenti=pagamentiDi(s).map(function(p){ return {data:p.data,importo:p.importo,modo:p.modo||"",note:p.note||""}; }).concat([{data:m.d,importo:r2(imp),modo:"bonifico",note:"banca: "+m.txt.slice(0,80)}]); normalizzaPagamenti(s); await scriviSpesa(s); m.fatto=true; m.esito="pagamento € "+eur(imp)+" su "+s.fornitore+(s.numFattura?" n. "+s.numFattura:""); }
    else{ var sc=S.scali[id]; if(!sc) return; sc.incassi=sc.incassi||[]; sc.incassi.push({importo:r2(Math.abs(m.imp)),data:m.d,banca:S.ct.bancaImp||((S.cfg.banche||[])[0]||{}).id||"",note:"banca: "+m.txt.slice(0,80)}); await scriviScalo(sc); m.fatto=true; m.esito="incasso € "+eur(Math.abs(m.imp))+" su "+protDi(sc)+" "+sc.nave; }
    render(); avviso("Movimento registrato."); }

  /* ---- fatture emesse (FDA numerati) ---- */
  function annoFda(sc){ var f=sc.fda||{}; return anno(f.data||f.inviato||sc.etd||sc.eta); }
  function emesse(){ var anni={}, righe=[], senza=[];
    listaScali().forEach(function(sc){ var f=sc.fda||{}; if(!f.numero&&!(f.inviato&&haFda(sc))) return; var y=annoFda(sc); anni[y]=1; if(S.ct.anno&&y!==S.ct.anno) return; if(f.numero) righe.push(sc); else senza.push(sc); });
    righe.sort(function(a,b){ return (numFdaInt(a.fda.numero)-numFdaInt(b.fda.numero))||String(a.fda.data||"").localeCompare(String(b.fda.data||"")); });
    senza.sort(function(a,b){ return String(a.fda.inviato||a.etd||a.eta||"").localeCompare(String(b.fda.inviato||b.etd||b.eta||"")); });
    var tot=0,inc=0,res=0; righe.forEach(function(sc){ var f=totFda(sc), i=incassato(sc); tot+=f; inc+=Math.min(i,f); res+=Math.max(0,r2(f-i)); });
    var NS=[], nsTot=0, nsInc=0, nsRes=0; for(var kk in S.spese){ var sn=S.spese[kk]; if(!isNs(sn)&&!isComm(sn)) continue; var scn=S.scali[sn.scalo]||{}, dn=sn.dataFattura||scn.eta||""; anni[anno(dn)]=1; if(S.ct.anno&&anno(dn)!==S.ct.anno) continue; if(S.ct.q&&!cercaOk(S.ct.q,campiSpesa(sn,scn))) continue; var tn=num(sn.totale)||0; nsTot+=tn; if(statoSpesa(sn)==="pagata") nsInc+=tn; else nsRes+=residuoDi(sn); NS.push({s:sn,sc:scn,d:dn}); }
    NS.sort(function(a,b){ return (a.d||"").localeCompare(b.d||"")||String(a.s.numFattura||"").localeCompare(String(b.s.numFattura||"")); });
    var h=testa("Fatture emesse",NS.length+" fatture "+nomeAzienda()+" · € "+eur(nsTot)+(nsRes?" · da incassare € "+eur(nsRes):"")+" — "+righe.length+" FDA numerati · € "+eur(tot),senza.length?'<button class="btn" id="ctNumera" title="Assegna un numero progressivo, in ordine di data, ai FDA inviati che non lo hanno">Numera '+senza.length+' FDA senza numero</button>':'');
    h+='<div class="panel"><div class="panel-h">'+'<div class="field" style="flex:1;min-width:160px"><input id="ctQ" type="search" placeholder="Cerca fattura: n., fornitore, nave, cliente, importo…" value="'+esc(S.ct.q||"")+'" aria-label="Cerca"></div>'+selAnni("ctAnno",anni,S.ct.anno)+'<span class="sub">Il numero si assegna nel <em>Conto PDA / FDA</em> di ogni scalo (pulsante <em>assegna il prossimo numero</em>); formato in Impostazioni → Contabilità.</span></div>';
    var byY={}, avvisi=[]; righe.forEach(function(sc){ var y=annoFda(sc), k=numFdaInt(sc.fda.numero); if(!byY[y]) byY[y]={}; (byY[y][k]=byY[y][k]||[]).push(sc); });
    Object.keys(byY).sort().forEach(function(y){ var ks=Object.keys(byY[y]).map(Number).filter(function(k){ return k>0; }).sort(function(a,b){ return a-b; }); var buchi=[]; for(var i=1;i<ks.length;i++) for(var m=ks[i-1]+1;m<ks[i];m++) buchi.push(m);
      var dup=ks.filter(function(k){ return byY[y][k].length>1; }); if(dup.length) avvisi.push("anno "+y+": numero doppio "+dup.join(", ")); if(buchi.length) avvisi.push("anno "+y+": manca il n. "+buchi.slice(0,15).join(", ")+(buchi.length>15?"…":"")); });
    h+='<div class="panel-h" style="border-top:1px solid var(--line)"><h2>Fatture '+esc(nomeAzienda())+'</h2><span class="sub">registrate come NS FATTURA (agency fees) e ns fatture di commissione ai fornitori: importo = totale della fattura come registrato; a lato tutte le voci della fattura</span><div class="spacer"></div><span class="sub">fatturato € '+eur(nsTot)+' · incassato € '+eur(nsInc)+' · da incassare € '+eur(nsRes)+'</span></div>';
    if(!NS.length) h+='<div class="panel-b sub">Nessuna fattura '+esc(nomeAzienda())+' nel periodo.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>N. fattura</th><th>Data</th><th>Cliente</th><th>Prot.</th><th>Nave</th><th class="num">Totale €</th><th>Stato</th><th>Voci della fattura</th></tr></thead><tbody>';
      NS.forEach(function(r){ var s=r.s; h+='<tr><td><strong>'+esc(s.numFattura||"—")+'</strong>'+(s.tipo==="nc"?' <span class="chip grey">NC</span>':s.tipo==="comm"?' <span class="chip grey">commissione al fornitore</span>':'')+'</td><td>'+dIt(s.dataFattura)+'</td><td>'+esc(isComm(s)?s.fornitore:r.sc.id?clienteDi(r.sc):"—")+'</td><td>'+lnkScalo(r.sc)+'</td><td>'+esc(r.sc.nave||"")+'</td><td class="num"><strong>'+eur(s.totale)+'</strong>'+(num(s.imponibile)!==null||num(s.iva)!==null?'<div class="sub" style="font-size:10.5px">'+(num(s.imponibile)!==null?"imp. "+eur(s.imponibile):"")+(num(s.iva)!==null?" · IVA "+eur(s.iva):"")+'</div>':'')+'</td><td>'+(statoSpesa(s)==="pagata"?'<span class="chip ok">incassata '+dIt(s.dataPagamento||(pagamentiDi(s).slice(-1)[0]||{}).data)+'</span>':statoSpesa(s)==="parziale"?'<span class="chip warn">parziale · resta € '+eur(residuoDi(s))+'</span>':'<span class="chip warn">da incassare</span>')+'</td><td class="voci-td" data-l="Voci">'+vociNsHtml(s,true)+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="5">Totale</td><td class="num">'+eur(nsTot)+'</td><td></td><td></td></tr></tfoot></table></div>'; }
    h+='<div class="panel-h" style="border-top:1px solid var(--line)"><h2>FDA numerati</h2><span class="sub">conti disbursement con numero di fattura</span></div>';
    if(avvisi.length) h+='<div class="warnbox"><strong>Controllo numerazione</strong><ul style="margin:6px 0">'+avvisi.map(function(a){ return '<li>'+esc(a)+'</li>'; }).join("")+'</ul></div>';
    if(!righe.length) h+='<div class="panel-b sub">Nessun FDA numerato'+(S.ct.anno?" nel "+S.ct.anno:"")+'.</div>';
    else{ h+='<div class="scroll"><table><thead><tr><th>N. fattura</th><th>Data</th><th>Cliente</th><th>Prot.</th><th>Nave</th><th>ETA / ETD</th><th class="num">Totale FDA €</th><th class="num">Incassato €</th><th class="num">Residuo €</th><th>Stato</th></tr></thead><tbody>';
      righe.forEach(function(sc){ var f=totFda(sc), i=incassato(sc), st=statoScalo(sc); h+='<tr><td><strong>'+esc(sc.fda.numero)+'</strong></td><td>'+dIt(sc.fda.data||sc.fda.inviato)+'</td><td>'+esc(clienteDi(sc))+'</td><td>'+lnkScalo(sc)+'</td><td>'+esc(sc.nave)+'</td><td class="sub">'+dIt(sc.eta)+(sc.etd?' / '+dIt(sc.etd):'')+'</td><td class="num">'+eur(f)+'</td><td class="num">'+eur(i)+'</td><td class="num">'+eur(Math.max(0,r2(f-i)))+'</td><td><span class="chip '+st.c+'">'+st.t+'</span></td></tr>'; });
      h+='</tbody><tfoot><tr><td colspan="6">Totale</td><td class="num">'+eur(tot)+'</td><td class="num">'+eur(inc)+'</td><td class="num">'+eur(res)+'</td><td></td></tr></tfoot></table></div>'; }
    if(senza.length){ h+='<div class="panel-h" style="border-top:1px solid var(--line)"><h2>FDA inviati senza numero di fattura</h2></div><div class="scroll"><table><tbody>'+senza.map(function(sc){ return '<tr><td>'+dIt(sc.fda.inviato)+'</td><td>'+lnkScalo(sc)+'</td><td><strong>'+esc(sc.nave)+'</strong></td><td class="sub">'+esc(clienteDi(sc))+'</td><td class="num">'+eur(totFda(sc))+'</td></tr>'; }).join("")+'</tbody></table></div>'; }
    CSV=function(){ esporta("fatture_emesse",["Documento","N. fattura","Data","Cliente","Prot.","Nave","Totale fattura","Imponibile","IVA","Incassato","Residuo","Stato","Voci della fattura","Note"],
      NS.map(function(r){ var s=r.s, t=num(s.totale)||0, p=pagatoDi(s); return [nomeAzienda(),s.numFattura||"",dIt(s.dataFattura),r.sc.id?clienteDi(r.sc):"",protDi(r.sc),r.sc.nave||"",t,num(s.imponibile)!==null?num(s.imponibile):"",num(s.iva)!==null?num(s.iva):"",p,residuoDi(s),statoSpesa(s)==="pagata"?"incassata":statoSpesa(s),vociNsTesto(s)||s.descrizione||"",s.note||""]; })
      .concat(righe.map(function(sc){ var f=totFda(sc), i=incassato(sc); return ["FDA",sc.fda.numero,dIt(sc.fda.data||sc.fda.inviato),clienteDi(sc),protDi(sc),sc.nave,f,"","",i,Math.max(0,r2(f-i)),statoScalo(sc).t,"",""]; }))); };
    return h+'</div>'; }
  async function numeraTutti(){ var L=listaScali().filter(function(sc){ var f=sc.fda||{}; return !f.numero&&f.inviato&&haFda(sc)&&(!S.ct.anno||annoFda(sc)===S.ct.anno); });
    L.sort(function(a,b){ return String(a.fda.inviato||"").localeCompare(String(b.fda.inviato||"")); }); if(!L.length) return;
    if(!confirm("Assegnare un numero progressivo a "+L.length+" FDA inviati, in ordine di data di invio? Il numero segue l'ultimo già usato in ciascun anno.")) return;
    for(var i=0;i<L.length;i++){ var sc=L[i]; sc.fda.numero=prossimoNumeroFda(annoFda(sc)); if(!sc.fda.data) sc.fda.data=sc.fda.inviato; await scriviScalo(sc); }
    render(); avviso(L.length+" FDA numerati."); }

  /* ---- statistiche anno su anno ---- */
  var PER=[["cliente","Cliente"],["nave","Nave"],["fornitore","Fornitore"],["operazione","Operazione"],["ormeggio","Ormeggio"],["mese","Mese"]];
  function chiave(sc,per){ if(per==="nave") return upper(sc.nave)||"—"; if(per==="operazione") return sc.operazione||"—"; if(per==="ormeggio") return sc.ormeggio||"—"; if(per==="mese"){ var m=ym(sc.eta); return m?MESI_IT[parseInt(m.slice(5,7),10)-1]:"—"; } return clienteDi(sc); }
  function pct(a,b){ if(!b) return a?"nuovo":"—"; var p=Math.round((a-b)/Math.abs(b)*100); return (p>0?"+":"")+p+"%"; }
  function stat(){ var per=S.ct.statPer||"cliente", anni={}; listaScali().forEach(function(sc){ var y=anno(sc.eta); if(y) anni[y]=1; }); for(var k in S.spese){ var y2=anno(S.spese[k].dataFattura); if(y2) anni[y2]=1; }
    var ys=Object.keys(anni).sort(); var A=S.ct.statAnno||ys[ys.length-1]||String(new Date().getFullYear()), B=String(parseInt(A,10)-1), G={}, T={};
    function g(k){ if(!G[k]) G[k]={}; return G[k]; } function z(){ return {scali:0,pda:0,fda:0,costi:0,fee:0,inc:0,nf:0}; }
    if(per==="fornitore"){ for(var j in S.spese){ var s=S.spese[j], sc=S.scali[s.scalo]||{}, y=anno(s.dataFattura||sc.eta); if(y!==A&&y!==B||isNs(s)||isComm(s)) continue; var o=g(upper(s.fornitore)||"—"); o[y]=o[y]||z(); o[y].nf++; o[y].costi+=num(s.totale)||0; if(statoSpesa(s)!=="pagata") o[y].fee+=residuoDi(s); T[y]=T[y]||z(); T[y].nf++; T[y].costi+=num(s.totale)||0; if(statoSpesa(s)!=="pagata") T[y].fee+=residuoDi(s); } }
    else listaScali().forEach(function(sc){ var y=anno(sc.eta); if(y!==A&&y!==B) return; var o=g(chiave(sc,per)); o[y]=o[y]||z(); T[y]=T[y]||z(); var f=totFda(sc), p=totPda(sc), c=0, fee=0; speseDi(sc.id).forEach(function(s){ var v=num(s.totale)||0; if(isNs(s)) fee+=v; else c+=v; });
      [o[y],T[y]].forEach(function(x){ x.scali++; x.pda+=p; x.fda+=f; x.costi+=c; x.fee+=fee; x.inc+=incassato(sc); }); });
    var keys=Object.keys(G).sort(function(a,b){ var ka=(G[a][A]||z()), kb=(G[b][A]||z()); return per==="fornitore"?(kb.costi-ka.costi):(kb.fda-ka.fda)||(kb.scali-ka.scali); });
    if(per==="mese") keys.sort(function(a,b){ return MESI_IT.indexOf(a)-MESI_IT.indexOf(b); });
    var h=testa("Statistiche · "+A+" rispetto al "+B,keys.length+" "+(PER.filter(function(p){ return p[0]===per; })[0][1].toLowerCase()+(keys.length===1?"":"/i")));
    h+='<div class="panel"><div class="panel-h"><div class="field"><select id="ctStatPer" aria-label="Raggruppa per">'+PER.map(function(p){ return opt(p[0],"per "+p[1].toLowerCase(),per); }).join("")+'</select></div><div class="field"><select id="ctStatAnno" aria-label="Anno">'+ys.slice().reverse().map(function(y){ return opt(y,y+" vs "+(parseInt(y,10)-1),A); }).join("")+'</select></div><span class="sub">'+(per==="fornitore"?"Fatture ricevute per fornitore: numero, totale e quanto resta da pagare.":"Scali per anno di arrivo: consuntivo FDA, costi = fatture dei fornitori registrate (escluse le nostre); FDA − fatture comprende quindi le nostre competenze e le voci interne senza fattura (diritti, bolli…); incassato.")+'</span></div>';
    var tA=T[A]||z(), tB=T[B]||z(), max=0; keys.forEach(function(k){ var a=G[k][A]||z(), b=G[k][B]||z(); max=Math.max(max,per==="fornitore"?a.costi:a.fda,per==="fornitore"?b.costi:b.fda); });
    function bar(v,c){ return '<div style="height:6px;background:'+c+';width:'+(max?Math.max(1,Math.round(v/max*100)):0)+'%;border-radius:3px;margin-top:2px"></div>'; }
    if(!keys.length) h+='<div class="panel-b sub">Nessun dato per '+esc(A)+' o '+esc(B)+'.</div>';
    else if(per==="fornitore"){ h+='<div class="scroll"><table><thead><tr><th>Fornitore</th><th class="num">Fatture '+B+'</th><th class="num">Fatture '+A+'</th><th class="num">Totale '+B+' €</th><th class="num">Totale '+A+' €</th><th class="num">Δ</th><th class="num">Da pagare '+A+' €</th><th style="min-width:120px">Andamento</th></tr></thead><tbody>';
      keys.forEach(function(k){ var a=G[k][A]||z(), b=G[k][B]||z(); h+='<tr><td><strong>'+esc(k)+'</strong></td><td class="num">'+b.nf+'</td><td class="num">'+a.nf+'</td><td class="num">'+eur(b.costi)+'</td><td class="num">'+eur(a.costi)+'</td><td class="num">'+pct(a.costi,b.costi)+'</td><td class="num">'+(a.fee?eur(a.fee):"—")+'</td><td>'+bar(b.costi,"#b9c4c9")+bar(a.costi,"var(--brand)")+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td>Totale</td><td class="num">'+tB.nf+'</td><td class="num">'+tA.nf+'</td><td class="num">'+eur(tB.costi)+'</td><td class="num">'+eur(tA.costi)+'</td><td class="num">'+pct(tA.costi,tB.costi)+'</td><td class="num">'+eur(tA.fee)+'</td><td></td></tr></tfoot></table></div>';
      CSV=function(){ esporta("statistiche_fornitori_"+A,["Fornitore","Fatture "+B,"Fatture "+A,"Totale "+B,"Totale "+A,"Variazione","Da pagare "+A],keys.map(function(k){ var a=G[k][A]||z(), b=G[k][B]||z(); return [k,b.nf,a.nf,b.costi,a.costi,pct(a.costi,b.costi),a.fee]; })); }; }
    else{ h+='<div class="scroll"><table><thead><tr><th>'+esc(PER.filter(function(p){ return p[0]===per; })[0][1])+'</th><th class="num">Scali '+B+'</th><th class="num">Scali '+A+'</th><th class="num">FDA '+B+' €</th><th class="num">FDA '+A+' €</th><th class="num">Δ FDA</th><th class="num">Costi '+A+' €</th><th class="num">FDA − fatture '+B+' €</th><th class="num">FDA − fatture '+A+' €</th><th class="num">Incassato '+A+' €</th><th style="min-width:120px">FDA '+B+' / '+A+'</th></tr></thead><tbody>';
      keys.forEach(function(k){ var a=G[k][A]||z(), b=G[k][B]||z(); h+='<tr><td><strong>'+esc(k)+'</strong></td><td class="num">'+b.scali+'</td><td class="num">'+a.scali+'</td><td class="num">'+eur(b.fda)+'</td><td class="num">'+eur(a.fda)+'</td><td class="num">'+pct(a.fda,b.fda)+'</td><td class="num">'+eur(a.costi)+'</td><td class="num">'+eur(r2(b.fda-b.costi))+'</td><td class="num '+(a.fda-a.costi<0?"neg":"")+'">'+eur(r2(a.fda-a.costi))+'</td><td class="num">'+eur(a.inc)+'</td><td>'+bar(b.fda,"#b9c4c9")+bar(a.fda,"var(--brand)")+'</td></tr>'; });
      h+='</tbody><tfoot><tr><td>Totale</td><td class="num">'+tB.scali+'</td><td class="num">'+tA.scali+'</td><td class="num">'+eur(tB.fda)+'</td><td class="num">'+eur(tA.fda)+'</td><td class="num">'+pct(tA.fda,tB.fda)+'</td><td class="num">'+eur(tA.costi)+'</td><td class="num">'+eur(r2(tB.fda-tB.costi))+'</td><td class="num">'+eur(r2(tA.fda-tA.costi))+'</td><td class="num">'+eur(tA.inc)+'</td><td></td></tr></tfoot></table></div>';
      h+='<div class="panel-b sub">FDA '+A+' € '+eur(tA.fda)+' · costi fornitori '+A+' € '+eur(tA.costi)+' · fatture '+esc(nomeAzienda())+' (agency fees) '+A+' € '+eur(tA.fee)+' · incassato '+A+' € '+eur(tA.inc)+'.</div>';
      CSV=function(){ esporta("statistiche_"+per+"_"+A,[PER.filter(function(p){ return p[0]===per; })[0][1],"Scali "+B,"Scali "+A,"FDA "+B,"FDA "+A,"Variazione FDA","Costi "+B,"Costi "+A,"FDA-fatture "+B,"FDA-fatture "+A,"Incassato "+A],keys.map(function(k){ var a=G[k][A]||z(), b=G[k][B]||z(); return [k,b.scali,a.scali,b.fda,a.fda,pct(a.fda,b.fda),b.costi,a.costi,r2(b.fda-b.costi),r2(a.fda-a.costi),a.inc]; })); }; }
    return h+'</div>'; }

  function tuttiXlsx(){ var fogli=[], salvaTab=S.contaTab, salvaCSV=CSV; ESPORTA_SILENZIOSO=true;
    try{ [["registro",registro],["iva",registroIva],["emesse",emesse],["scadenzario",scadenzario],["clienti",clienti],["eccliente",ecCliente],["primanota",primaNota],["cassa",cassa],["stat",stat]].forEach(function(t){ S.contaTab=t[0]; ULTIMO=null; t[1](); if(CSV) CSV(); if(ULTIMO) fogli.push({nome:TABS.filter(function(x){ return x[0]===t[0]; })[0][1],testata:ULTIMO.testata,righe:ULTIMO.righe}); }); }
    finally{ ESPORTA_SILENZIOSO=false; S.contaTab=salvaTab; CSV=salvaCSV; }
    if(typeof scriviXlsx!=="function"){ avviso("Esportazione XLSX non disponibile."); return; } scriviXlsx("Portolano_contabilita_"+oggi()+".xlsx",fogli); avviso("File Excel con "+fogli.length+" fogli pronto."); }

  window.vistaConta=function(){ CSV=null; SOLL=null; try{ return S.contaTab==="scadenzario"?scadenzario():S.contaTab==="clienti"?clienti():S.contaTab==="eccliente"?ecCliente():S.contaTab==="primanota"?primaNota():S.contaTab==="cassa"?cassa():S.contaTab==="iva"?registroIva():S.contaTab==="banca"?banca():S.contaTab==="emesse"?emesse():S.contaTab==="stat"?stat():registro(); }catch(e){ return testa("Errore","")+'<div class="panel"><div class="panel-b">Errore: '+esc(e.message||e)+'</div></div>'; } };

  var _eventi=eventi;
  window.eventi=function(){ _eventi(); if(S.view!=="conta") return; S.cs=S.cs||{}; eventiCassa();
    document.querySelectorAll("[data-ctab]").forEach(function(b){ b.addEventListener("click",function(){ S.contaTab=b.getAttribute("data-ctab"); render(); }); });
    on("ctCsv","click",function(){ if(CSV) CSV(); });
    on("ctXlsx","click",tuttiXlsx);
    on("ctNumera","click",numeraTutti);
    document.querySelectorAll("[data-soll]").forEach(function(b){ b.addEventListener("click",function(){ if(SOLL) SOLL(b.getAttribute("data-soll")); }); });
    document.querySelectorAll("[data-allegato]").forEach(function(b){ b.addEventListener("click",function(){ if(window.PortolanoAllegati) PortolanoAllegati.apri(b.getAttribute("data-allegato")); }); });
    on("bkFile","change",function(){ var f=this.files&&this.files[0]; if(!f) return; var r=new FileReader(); r.onload=function(){ S.bk.righe=leggiEstratto(String(r.result)); S.bk.testo=""; if(!S.bk.righe.length) avviso("Non riconosco le colonne del file: servono data, importo e descrizione."); render(); }; r.readAsText(f,"utf-8"); });
    on("bkLeggi","click",function(){ S.bk.testo=val("bkTesto"); var t=S.bk.testo.replace(/\t/g,";"); S.bk.righe=leggiEstratto(t); if(!S.bk.righe.length) avviso("Non riconosco le righe: usa data; descrizione; importo (una per riga)."); render(); });
    on("bkSvuota","click",function(){ S.bk={righe:[],testo:""}; render(); });
    on("ctBancaImp","change",function(){ S.ct.bancaImp=this.value; });
    document.querySelectorAll("[data-bkreg]").forEach(function(b){ b.addEventListener("click",function(){ registraMov(parseInt(b.getAttribute("data-bkreg"),10)); }); });
    on("ctQ","input",function(){ S.ct.q=this.value; var p=this.selectionStart; render(); var e=document.getElementById("ctQ"); if(e){ e.focus(); e.setSelectionRange(p,p); } });
    [["ctAnno","anno"],["ctMese","mese"],["ctForn","forn"],["ctStato","stato"],["ctCliente","cliente"],["ctSolo","solo"],["ctBanca","banca"],["ctStatPer","statPer"],["ctStatAnno","statAnno"]].forEach(function(p){ on(p[0],"change",function(){ S.ct[p[1]]=this.value; if(p[1]==="anno"&&S.ct.mese&&S.ct.mese.slice(0,4)!==this.value) S.ct.mese=""; render(); }); });
  };
})();
